package streams

type PhpStreamMmapOperationT = int

const (
	PHP_STREAM_MMAP_SUPPORTED = iota
	PHP_STREAM_MMAP_MAP_RANGE
	PHP_STREAM_MMAP_UNMAP
)

type PhpStreamMmapAccessT = int

const (
	PHP_STREAM_MAP_MODE_READONLY = iota
	PHP_STREAM_MAP_MODE_READWRITE
	PHP_STREAM_MAP_MODE_SHARED_READONLY
	PHP_STREAM_MAP_MODE_SHARED_READWRITE
)
