package zend

import (
	"sik/zend/types"
)

var BuiltinFunctions = []types.ZendFunctionEntry{
	DefZifZendVersion,
	DefZifFuncNumArgs,
	DefZifFuncGetArg,
	DefZifFuncGetArgs,
	DefZifStrlen,
	DefZifStrcmp,
	DefZifStrncmp,
	DefZifStrcasecmp,
	DefZifStrncasecmp,
	DefZifEach,
	DefZifErrorReporting,
	DefZifDefine,
	DefZifDefined,
	DefZifGetClass,
	DefZifGetCalledClass,
	DefZifGetParentClass,
	DefZifMethodExists,
	DefZifPropertyExists,
	DefZifClassExists,
	DefZifInterfaceExists,
	DefZifTraitExists,
	DefZifFunctionExists,
	DefZifClassAlias,
	DefZifGetIncludedFiles,
	DefZifGetRequiredFiles,
	DefZifIsSubclassOf,
	DefZifIsA,
	DefZifGetClassVars,
	DefZifGetObjectVars,
	DefZifGetMangledObjectVars,
	DefZifGetClassMethods,
	DefZifTriggerError,
	DefZifUserError,
	DefZifSetErrorHandler,
	DefZifRestoreErrorHandler,
	DefZifSetExceptionHandler,
	DefZifRestoreExceptionHandler,
	DefZifGetDeclaredClasses,
	DefZifGetDeclaredTraits,
	DefZifGetDeclaredInterfaces,
	DefZifGetDefinedFunctions,
	DefZifGetDefinedVars,
	DefZifCreateFunction,
	DefZifGetResourceType,
	DefZifGetResources,
	DefZifGetLoadedExtensions,
	DefZifExtensionLoaded,
	DefZifGetExtensionFuncs,
	DefZifGetDefinedConstants,
	DefZifDebugBacktrace,
	DefZifDebugPrintBacktrace,
	DefZifGcMemCaches,
	DefZifGcCollectCycles,
	DefZifGcEnabled,
	DefZifGcEnable,
	DefZifGcDisable,
	DefZifGcStatus,
}
var ZendBuiltinModule = MakeZendModuleEntry(
	"Core",
	BuiltinFunctions,
	ZmStartupCore,
	nil,
	nil,
	nil,
	nil,
	ZEND_VERSION,
	0,
	nil,
	nil,
	nil,
)

const LAMBDA_TEMP_FUNCNAME = "__lambda_func"
