// <<generate>>

package zend

const ZEND_MM_CHUNK_SIZE = 2 * 1024 * 1024
const ZEND_MM_PAGE_SIZE = 4 * 1024
const ZEND_MM_PAGES uint32 = ZEND_MM_CHUNK_SIZE / ZEND_MM_PAGE_SIZE
const ZEND_MM_FIRST_PAGE = 1
const ZEND_MM_MIN_SMALL_SIZE = 8
const ZEND_MM_MAX_SMALL_SIZE = 3072
const ZEND_MM_MAX_LARGE_SIZE = ZEND_MM_CHUNK_SIZE - ZEND_MM_PAGE_SIZE*ZEND_MM_FIRST_PAGE
