package zend

import (
	b "sik/builtin"
	"sik/zend/types"
)

var BuiltinFunctions = []types.ZendFunctionEntry{
	DefZifZendVersion,
	DefZifFuncNumArgs,
	DefZifFuncGetArg,
	DefZifFuncGetArgs,
	DefZifStrlen,
	DefZifStrcmp,
	DefZifStrncmp,
	DefZifStrcasecmp,
	DefZifStrncasecmp,
	types.MakeZendFunctionEntryEx("each", 0, ZifEach, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgInfo("arr", ArgInfoByRef(1)),
	}),
	DefZifErrorReporting,
	DefZifDefine,
	DefZifDefined,
	types.MakeZendFunctionEntryEx("get_class", 0, ZifGetClass, []ArgInfo{MakeReturnArgInfo(0),
		MakeArgName("object"),
	}),
	DefZifGetCalledClass,
	types.MakeZendFunctionEntryEx("get_parent_class", 0, ZifGetParentClass, []ArgInfo{MakeReturnArgInfo(0),
		MakeArgName("object"),
	}),
	types.MakeZendFunctionEntryEx("method_exists", 0, ZifMethodExists, []ArgInfo{MakeReturnArgInfo(2),
		MakeArgName("object"),
		MakeArgName("method"),
	}),
	types.MakeZendFunctionEntryEx("property_exists", 0, ZifPropertyExists, []ArgInfo{MakeReturnArgInfo(2),
		MakeArgName("object_or_class"),
		MakeArgName("property_name"),
	}),
	types.MakeZendFunctionEntryEx("class_exists", 0, ZifClassExists, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("classname"),
		MakeArgName("autoload"),
	}),
	types.MakeZendFunctionEntryEx("interface_exists", 0, ZifInterfaceExists, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("classname"),
		MakeArgName("autoload"),
	}),
	types.MakeZendFunctionEntryEx("trait_exists", 0, ZifTraitExists, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("traitname"),
		MakeArgName("autoload"),
	}),
	types.MakeZendFunctionEntryEx("function_exists", 0, ZifFunctionExists, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("function_name"),
	}),
	types.MakeZendFunctionEntryEx("class_alias", 0, ZifClassAlias, []ArgInfo{MakeReturnArgInfo(2),
		MakeArgName("user_class_name"),
		MakeArgName("alias_name"),
		MakeArgName("autoload"),
	}),
	types.MakeZendFunctionEntryEx("get_included_files", 0, ZifGetIncludedFiles, nil),
	types.MakeZendFunctionEntryEx("get_required_files", 0, ZifGetIncludedFiles, nil),
	types.MakeZendFunctionEntryEx("is_subclass_of", 0, ZifIsSubclassOf, []ArgInfo{MakeReturnArgInfo(2),
		MakeArgName("object"),
		MakeArgName("class_name"),
		MakeArgName("allow_string"),
	}),
	types.MakeZendFunctionEntryEx("is_a", 0, ZifIsA, []ArgInfo{MakeReturnArgInfo(2),
		MakeArgName("object"),
		MakeArgName("class_name"),
		MakeArgName("allow_string"),
	}),
	types.MakeZendFunctionEntryEx("get_class_vars", 0, ZifGetClassVars, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("class_name"),
	}),
	types.MakeZendFunctionEntryEx("get_object_vars", 0, ZifGetObjectVars, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("obj"),
	}),
	types.MakeZendFunctionEntryEx("get_mangled_object_vars", 0, ZifGetMangledObjectVars, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("obj"),
	}),
	types.MakeZendFunctionEntryEx("get_class_methods", 0, ZifGetClassMethods, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("class"),
	}),
	types.MakeZendFunctionEntryEx("trigger_error", 0, ZifTriggerError, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("message"),
		MakeArgName("error_type"),
	}),
	types.MakeZendFunctionEntryEx("user_error", 0, ZifTriggerError, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("message"),
		MakeArgName("error_type"),
	}),
	types.MakeZendFunctionEntryEx("set_error_handler", 0, ZifSetErrorHandler, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("error_handler"),
		MakeArgName("error_types"),
	}),
	types.MakeZendFunctionEntryEx("restore_error_handler", 0, ZifRestoreErrorHandler, nil),
	types.MakeZendFunctionEntryEx("set_exception_handler", 0, ZifSetExceptionHandler, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("exception_handler"),
	}),
	types.MakeZendFunctionEntryEx("restore_exception_handler", 0, ZifRestoreExceptionHandler, nil),
	types.MakeZendFunctionEntryEx("get_declared_classes", 0, ZifGetDeclaredClasses, nil),
	types.MakeZendFunctionEntryEx("get_declared_traits", 0, ZifGetDeclaredTraits, nil),
	types.MakeZendFunctionEntryEx("get_declared_interfaces", 0, ZifGetDeclaredInterfaces, nil),
	types.MakeZendFunctionEntryEx("get_defined_functions", 0, ZifGetDefinedFunctions, []ArgInfo{MakeReturnArgInfo(0),
		MakeArgName("exclude_disabled"),
	}),
	types.MakeZendFunctionEntryEx("get_defined_vars", 0, ZifGetDefinedVars, nil),
	types.MakeZendFunctionEntryEx("create_function", ZEND_ACC_DEPRECATED, ZifCreateFunction, []ArgInfo{MakeReturnArgInfo(2),
		MakeArgName("args"),
		MakeArgName("code"),
	}),
	types.MakeZendFunctionEntryEx("get_resource_type", 0, ZifGetResourceType, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("res"),
	}),
	types.MakeZendFunctionEntryEx("get_resources", 0, ZifGetResources, []ArgInfo{MakeReturnArgInfo(0),
		MakeArgName("type"),
	}),
	types.MakeZendFunctionEntryEx("get_loaded_extensions", 0, ZifGetLoadedExtensions, []ArgInfo{MakeReturnArgInfo(0),
		MakeArgName("zend_extensions"),
	}),
	types.MakeZendFunctionEntryEx("extension_loaded", 0, ZifExtensionLoaded, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("extension_name"),
	}),
	types.MakeZendFunctionEntryEx("get_extension_funcs", 0, ZifGetExtensionFuncs, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("extension_name"),
	}),
	types.MakeZendFunctionEntryEx("get_defined_constants", 0, ZifGetDefinedConstants, []ArgInfo{MakeReturnArgInfo(0),
		MakeArgName("categorize"),
	}),
	types.MakeZendFunctionEntryEx("debug_backtrace", 0, ZifDebugBacktrace, []ArgInfo{MakeReturnArgInfo(0),
		MakeArgName("options"),
		MakeArgName("limit"),
	}),
	types.MakeZendFunctionEntryEx("debug_print_backtrace", 0, ZifDebugPrintBacktrace, []ArgInfo{MakeReturnArgInfo(0),
		MakeArgName("options"),
		MakeArgName("limit"),
	}),
	DefZifGcMemCaches,
	DefZifGcCollectCycles,
	DefZifGcEnabled,
	DefZifGcEnable,
	DefZifGcDisable,
	DefZifGcStatus,
}
var ZendBuiltinModule = MakeZendModuleEntry(b.SizeOf("zend_module_entry"), ZEND_MODULE_API_NO, 0, USING_ZTS, nil, nil, "Core", BuiltinFunctions, ZmStartupCore, nil, nil, nil, nil, ZEND_VERSION, 0, nil, nil, nil, nil, 0, 0, nil, 0, "API"+"ZEND_MODULE_API_NO"+ZEND_BUILD_TS)

const LAMBDA_TEMP_FUNCNAME = "__lambda_func"
