package zend

import (
	b "sik/builtin"
	"sik/zend/types"
)

var BuiltinFunctions = []types.ZendFunctionEntry{
	DefZifZendVersion,
	DefZifFuncNumArgs,
	DefZifFuncGetArg,
	DefZifFuncGetArgs,
	DefZifStrlen,
	DefZifStrcmp,
	DefZifStrncmp,
	DefZifStrcasecmp,
	DefZifStrncasecmp,
	DefZifEach,
	DefZifErrorReporting,
	DefZifDefine,
	DefZifDefined,
	DefZifGetClass,
	DefZifGetCalledClass,
	DefZifGetParentClass,
	DefZifMethodExists,
	DefZifPropertyExists,
	DefZifClassExists,
	DefZifInterfaceExists,
	DefZifTraitExists,
	DefZifFunctionExists,
	DefZifClassAlias,
	DefZifGetIncludedFiles,
	types.MakeZendFunctionEntryEx("get_required_files", 0, ZifGetIncludedFiles, nil),
	DefZifIsSubclassOf,
	DefZifIsA,
	DefZifGetClassVars,
	DefZifGetObjectVars,
	DefZifGetMangledObjectVars,
	DefZifGetClassMethods,
	DefZifTriggerError,
	types.MakeZendFunctionEntryEx("user_error", 0, ZifTriggerError, []ArgInfo{MakeReturnArgInfo(1),
		MakeArgName("message"),
		MakeArgName("error_type"),
	}),
	DefZifSetErrorHandler,
	DefZifRestoreErrorHandler,
	DefZifSetExceptionHandler,
	DefZifRestoreExceptionHandler,
	DefZifGetDeclaredClasses,
	DefZifGetDeclaredTraits,
	DefZifGetDeclaredInterfaces,
	DefZifGetDefinedFunctions,
	DefZifGetDefinedVars,
	DefZifCreateFunction,
	DefZifGetResourceType,
	DefZifGetResources,
	DefZifGetLoadedExtensions,
	DefZifExtensionLoaded,
	DefZifGetExtensionFuncs,
	DefZifGetDefinedConstants,
	DefZifDebugBacktrace,
	DefZifDebugPrintBacktrace,
	DefZifGcMemCaches,
	DefZifGcCollectCycles,
	DefZifGcEnabled,
	DefZifGcEnable,
	DefZifGcDisable,
	DefZifGcStatus,
}
var ZendBuiltinModule = MakeZendModuleEntry(b.SizeOf("zend_module_entry"), ZEND_MODULE_API_NO, 0, USING_ZTS, nil, nil, "Core", BuiltinFunctions, ZmStartupCore, nil, nil, nil, nil, ZEND_VERSION, 0, nil, nil, nil, nil, 0, 0, nil, 0, "API"+"ZEND_MODULE_API_NO"+ZEND_BUILD_TS)

const LAMBDA_TEMP_FUNCNAME = "__lambda_func"
