// <<generate>>

package zend

const ZEND_PARSE_PARAMS_QUIET = 1 << 1
const ZEND_PARSE_PARAMS_THROW = 1 << 2
const IS_CALLABLE_CHECK_SYNTAX_ONLY uint32 = 1 << 0
const IS_CALLABLE_CHECK_NO_ACCESS = 1 << 1
const IS_CALLABLE_CHECK_IS_STATIC = 1 << 2
const IS_CALLABLE_CHECK_SILENT uint32 = 1 << 3
const IS_CALLABLE_STRICT uint32 = IS_CALLABLE_CHECK_IS_STATIC
const ZEND_THIS *Zval = &EX(This)
const WRONG_PARAM_COUNT = ZEND_WRONG_PARAM_COUNT()
const RETVAL_FALSE = ZVAL_FALSE(return_value)
const RETVAL_TRUE = ZVAL_TRUE(return_value)
const ZEND_MINIT = ZEND_MODULE_STARTUP_N
const ZEND_MSHUTDOWN = ZEND_MODULE_SHUTDOWN_N
const ZEND_RINIT = ZEND_MODULE_ACTIVATE_N
const ZEND_RSHUTDOWN = ZEND_MODULE_DEACTIVATE_N
const ZEND_MINFO = ZEND_MODULE_INFO_N
const ZEND_MSHUTDOWN_FUNCTION = ZEND_MODULE_SHUTDOWN_D
const ZEND_RINIT_FUNCTION = ZEND_MODULE_ACTIVATE_D
const ZEND_RSHUTDOWN_FUNCTION = ZEND_MODULE_DEACTIVATE_D
const ZEND_MINFO_FUNCTION = ZEND_MODULE_INFO_D
const ZEND_GSHUTDOWN_FUNCTION = ZEND_MODULE_GLOBALS_DTOR_D
const FAST_ZPP = 1

type ZendExpectedType = int

const (
	Z_EXPECTED_LONG = iota
	Z_EXPECTED_BOOL
	Z_EXPECTED_STRING
	Z_EXPECTED_ARRAY
	Z_EXPECTED_FUNC
	Z_EXPECTED_RESOURCE
	Z_EXPECTED_PATH
	Z_EXPECTED_OBJECT
	Z_EXPECTED_DOUBLE
	Z_EXPECTED_LAST
)
const ZPP_ERROR_OK = 0
const ZPP_ERROR_FAILURE = 1
const ZPP_ERROR_WRONG_CALLBACK = 2
const ZPP_ERROR_WRONG_CLASS = 3
const ZPP_ERROR_WRONG_ARG = 4
const ZPP_ERROR_WRONG_COUNT = 5

var ModuleRegistry HashTable
var ModuleRequestStartupHandlers **ZendModuleEntry
var ModuleRequestShutdownHandlers **ZendModuleEntry
var ModulePostDeactivateHandlers **ZendModuleEntry
var ClassCleanupHandlers **ZendClassEntry
var DisabledClassNew []ZendFunctionEntry = []ZendFunctionEntry{{nil, nil, nil, 0, 0}}
