// <<generate>>

package zend

const SMART_STR_OVERHEAD = ZEND_MM_OVERHEAD + _ZSTR_HEADER_SIZE + 1
const SMART_STR_START_SIZE = 256
const SMART_STR_START_LEN = SMART_STR_START_SIZE - SMART_STR_OVERHEAD
const SMART_STR_PAGE = 4096
const VK_ESCAPE = 'e'
const SMART_STRING_OVERHEAD = ZEND_MM_OVERHEAD + 1
const SMART_STRING_START_SIZE = 256
const SMART_STRING_START_LEN = SMART_STRING_START_SIZE - SMART_STRING_OVERHEAD
const SMART_STRING_PAGE = 4096
