// <<generate>>

package zend

// Source: <Zend/zend_language_scanner_defs.h>

/* Generated by re2c 3.0 */

const (
	yycST_IN_SCRIPTING = iota
	yycST_LOOKING_FOR_PROPERTY
	yycST_BACKQUOTE
	yycST_DOUBLE_QUOTES
	yycST_HEREDOC
	yycST_LOOKING_FOR_VARNAME
	yycST_VAR_OFFSET
	yycSHEBANG
	yycINITIAL
	yycST_END_HEREDOC
	yycST_NOWDOC
)
