package zend

const ZEND_MODULE_API_NO = 20190902
const USING_ZTS = 0
const MODULE_PERSISTENT = 1
const MODULE_TEMPORARY = 2

const MODULE_DEP_REQUIRED = 1
const MODULE_DEP_CONFLICTS = 2
const MODULE_DEP_OPTIONAL = 3
