package zend

import "github.com/heyuuu/gophp/zend/types"

const MAY_BE_UNDEF = 1 << types.IS_UNDEF
const MAY_BE_NULL = 1 << types.IS_NULL
const MAY_BE_FALSE = 1 << types.IS_FALSE
const MAY_BE_TRUE = 1 << types.IS_TRUE
const MAY_BE_LONG = 1 << types.IS_LONG
const MAY_BE_DOUBLE = 1 << types.IS_DOUBLE
const MAY_BE_STRING = 1 << types.IS_STRING
const MAY_BE_ARRAY = 1 << types.IS_ARRAY
const MAY_BE_OBJECT = 1 << types.IS_OBJECT
const MAY_BE_RESOURCE = 1 << types.IS_RESOURCE
const MAY_BE_ANY = MAY_BE_NULL | MAY_BE_FALSE | MAY_BE_TRUE | MAY_BE_LONG | MAY_BE_DOUBLE | MAY_BE_STRING | MAY_BE_ARRAY | MAY_BE_OBJECT | MAY_BE_RESOURCE
const MAY_BE_REF = 1 << types.IS_REFERENCE
const MAY_BE_ARRAY_SHIFT = types.IS_REFERENCE
const MAY_BE_ARRAY_OF_NULL = MAY_BE_NULL << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_FALSE = MAY_BE_FALSE << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_TRUE = MAY_BE_TRUE << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_LONG = MAY_BE_LONG << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_DOUBLE = MAY_BE_DOUBLE << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_STRING = MAY_BE_STRING << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_ARRAY = MAY_BE_ARRAY << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_OBJECT = MAY_BE_OBJECT << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_RESOURCE = MAY_BE_RESOURCE << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_ANY = MAY_BE_ANY << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_OF_REF = MAY_BE_REF << MAY_BE_ARRAY_SHIFT
const MAY_BE_ARRAY_KEY_LONG = 1 << 21
const MAY_BE_ARRAY_KEY_STRING = 1 << 22
const MAY_BE_ARRAY_KEY_ANY = MAY_BE_ARRAY_KEY_LONG | MAY_BE_ARRAY_KEY_STRING
const MAY_BE_ERROR = 1 << 23
const MAY_BE_CLASS = 1 << 24
