package zend

// Source: <Zend/zend_ini_scanner_defs.h>

/* Generated by re2c 0.13.5 */

type YYCONDTYPE = int

const (
	yycINITIAL = iota
	yycST_OFFSET
	yycST_SECTION_VALUE
	yycST_VALUE
	yycST_SECTION_RAW
	yycST_DOUBLE_QUOTES
	yycST_VARNAME
	yycST_RAW
)
