// Code generated by "stringer -type=ZppRetType"; DO NOT EDIT.

package zif

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RetTypeBool-1]
	_ = x[RetTypeLong-2]
	_ = x[RetTypeDouble-3]
	_ = x[RetTypeString-4]
	_ = x[RetTypeArray-5]
	_ = x[RetTypeObject-6]
	_ = x[RetTypeZval-7]
	_ = x[RetTypeIntArray-8]
	_ = x[RetTypeStringArray-9]
	_ = x[RetTypeZvalArray-10]
}

const _ZppRetType_name = "RetTypeBoolRetTypeLongRetTypeDoubleRetTypeStringRetTypeArrayRetTypeObjectRetTypeZvalRetTypeIntArrayRetTypeStringArrayRetTypeZvalArray"

var _ZppRetType_index = [...]uint8{0, 11, 22, 35, 48, 60, 73, 84, 99, 117, 133}

func (i ZppRetType) String() string {
	i -= 1
	if i < 0 || i >= ZppRetType(len(_ZppRetType_index)-1) {
		return "ZppRetType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ZppRetType_name[_ZppRetType_index[i]:_ZppRetType_index[i+1]]
}
