// Code generated by "stringer -type=ZppType"; DO NOT EDIT.

package zif

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZppTypeBool-1]
	_ = x[ZppTypeLong-2]
	_ = x[ZppTypeDouble-3]
	_ = x[ZppTypeString-4]
	_ = x[ZppTypeZendBool-5]
	_ = x[ZppTypeZendString-6]
	_ = x[ZppTypeZendArray-7]
	_ = x[ZppTypeEx-8]
	_ = x[ZppTypeRet-9]
	_ = x[ZppTypeOpt-10]
	_ = x[ZppTypeVariadic-11]
}

const _ZppType_name = "ZppTypeBoolZppTypeLongZppTypeDoubleZppTypeStringZppTypeZendBoolZppTypeZendStringZppTypeZendArrayZppTypeExZppTypeRetZppTypeOptZppTypeVariadic"

var _ZppType_index = [...]uint8{0, 11, 22, 35, 48, 63, 80, 96, 105, 115, 125, 140}

func (i ZppType) String() string {
	i -= 1
	if i < 0 || i >= ZppType(len(_ZppType_index)-1) {
		return "ZppType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ZppType_name[_ZppType_index[i]:_ZppType_index[i+1]]
}
