// Code generated by "stringer -type=ZppType"; DO NOT EDIT.

package zif

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZppTypeEx-1]
	_ = x[ZppTypeRet-2]
	_ = x[ZppTypeOpt-3]
	_ = x[ZppTypeBool-4]
	_ = x[ZppTypeLong-5]
	_ = x[ZppTypeStrictLong-6]
	_ = x[ZppTypeDouble-7]
	_ = x[ZppTypeString-8]
	_ = x[ZppTypePath-9]
	_ = x[ZppTypeArrayHt-10]
	_ = x[ZppTypeArrayOrObjectHt-11]
	_ = x[ZppTypeArray-12]
	_ = x[ZppTypeArrayOrObject-13]
	_ = x[ZppTypeClass-14]
	_ = x[ZppTypeObject-15]
	_ = x[ZppTypeResource-16]
	_ = x[ZppTypeCallable-17]
	_ = x[ZppTypeZval-18]
	_ = x[ZppTypeZvalDeref-19]
	_ = x[ZppTypeVariadic-20]
	_ = x[ZppTypeBoolNullable-21]
	_ = x[ZppTypeLongNullable-22]
	_ = x[ZppTypeStrictLongNullable-23]
	_ = x[ZppTypeDoubleNullable-24]
	_ = x[ZppTypeStringNullable-25]
	_ = x[ZppTypePathNullable-26]
	_ = x[ZppTypeZvalNullable-27]
	_ = x[ZppTypeRefZval-28]
	_ = x[ZppTypeRefVariadic-29]
	_ = x[ZppTypeRefArray-30]
	_ = x[ZppTypeDerefArray-31]
	_ = x[ZppTypeRefArrayOrObject-32]
	_ = x[ZppTypeRefArrayHt-33]
}

const _ZppType_name = "ZppTypeExZppTypeRetZppTypeOptZppTypeBoolZppTypeLongZppTypeStrictLongZppTypeDoubleZppTypeStringZppTypePathZppTypeArrayHtZppTypeArrayOrObjectHtZppTypeArrayZppTypeArrayOrObjectZppTypeClassZppTypeObjectZppTypeResourceZppTypeCallableZppTypeZvalZppTypeZvalDerefZppTypeVariadicZppTypeBoolNullableZppTypeLongNullableZppTypeStrictLongNullableZppTypeDoubleNullableZppTypeStringNullableZppTypePathNullableZppTypeZvalNullableZppTypeRefZvalZppTypeRefVariadicZppTypeRefArrayZppTypeDerefArrayZppTypeRefArrayOrObjectZppTypeRefArrayHt"

var _ZppType_index = [...]uint16{0, 9, 19, 29, 40, 51, 68, 81, 94, 105, 119, 141, 153, 173, 185, 198, 213, 228, 239, 255, 270, 289, 308, 333, 354, 375, 394, 413, 427, 445, 460, 477, 500, 517}

func (i ZppType) String() string {
	i -= 1
	if i < 0 || i >= ZppType(len(_ZppType_index)-1) {
		return "ZppType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ZppType_name[_ZppType_index[i]:_ZppType_index[i+1]]
}
