// <<generate>>

package standard

const EXTR_OVERWRITE = 0
const EXTR_SKIP = 1
const EXTR_PREFIX_SAME = 2
const EXTR_PREFIX_ALL = 3
const EXTR_PREFIX_INVALID = 4
const EXTR_PREFIX_IF_EXISTS = 5
const EXTR_IF_EXISTS = 6
const EXTR_REFS = 0x100
const CASE_LOWER = 0
const CASE_UPPER = 1
const DIFF_NORMAL = 1
const DIFF_KEY = 2
const DIFF_ASSOC = 6
const DIFF_COMP_DATA_NONE = -1
const DIFF_COMP_DATA_INTERNAL = 0
const DIFF_COMP_DATA_USER = 1
const DIFF_COMP_KEY_INTERNAL = 0
const DIFF_COMP_KEY_USER = 1
const INTERSECT_NORMAL = 1
const INTERSECT_KEY = 2
const INTERSECT_ASSOC = 6
const INTERSECT_COMP_DATA_NONE = -1
const INTERSECT_COMP_DATA_INTERNAL = 0
const INTERSECT_COMP_DATA_USER = 1
const INTERSECT_COMP_KEY_INTERNAL = 0
const INTERSECT_COMP_KEY_USER = 1

var ArrayGlobals ZendArrayGlobals

const MULTISORT_ORDER = 0
const MULTISORT_TYPE = 1
const MULTISORT_LAST = 2
