// <<generate>>

package standard

import (
	b "sik/builtin"
	"sik/core"
	"sik/zend"
	"sik/zend/types"
)

const BasicFunctionsModulePtr = &BasicFunctionsModule

/* system functions */

var ZifSetTimeLimit func(executeData *zend.ZendExecuteData, return_value *types.Zval)
var ZifHeaderRegisterCallback func(executeData *zend.ZendExecuteData, return_value *types.Zval)

/* From the INI parser */

/* Left for BC (not binary safe!) */

const MT_N = 624

var BasicGlobals PhpBasicGlobals

// Source: <ext/standard/basic_functions.c>

var IncompleteClassEntry *types.ClassEntry = nil

var BasicFunctions []types.ZendFunctionEntry = []types.ZendFunctionEntry{
	types.MakeZendFunctionEntryEx("constant", 0, ZifConstant, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("const_name"),
	}),
	types.MakeZendFunctionEntryEx("bin2hex", 0, ZifBin2hex, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("data"),
	}),
	types.MakeZendFunctionEntryEx("hex2bin", 0, ZifHex2bin, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("data"),
	}),
	types.MakeZendFunctionEntryEx("sleep", 0, ZifSleep, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("seconds"),
	}),
	types.MakeZendFunctionEntryEx("usleep", 0, ZifUsleep, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("micro_seconds"),
	}),
	types.MakeZendFunctionEntryEx("time_nanosleep", 0, ZifTimeNanosleep, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("seconds"),
		zend.MakeArgName("nanoseconds"),
	}),
	types.MakeZendFunctionEntryEx("time_sleep_until", 0, ZifTimeSleepUntil, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("timestamp"),
	}),
	types.MakeZendFunctionEntryEx("strptime", 0, ZifStrptime, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("timestamp"),
		zend.MakeArgName("format"),
	}),
	types.MakeZendFunctionEntryEx("flush", 0, ZifFlush, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("wordwrap", 0, ZifWordwrap, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("width"),
		zend.MakeArgName("break"),
		zend.MakeArgName("cut"),
	}),
	types.MakeZendFunctionEntryEx("htmlspecialchars", 0, ZifHtmlspecialchars, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("string"),
		zend.MakeArgName("quote_style"),
		zend.MakeArgName("encoding"),
		zend.MakeArgName("double_encode"),
	}),
	types.MakeZendFunctionEntryEx("htmlentities", 0, ZifHtmlentities, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("string"),
		zend.MakeArgName("quote_style"),
		zend.MakeArgName("encoding"),
		zend.MakeArgName("double_encode"),
	}),
	types.MakeZendFunctionEntryEx("html_entity_decode", 0, ZifHtmlEntityDecode, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("string"),
		zend.MakeArgName("quote_style"),
		zend.MakeArgName("encoding"),
	}),
	types.MakeZendFunctionEntryEx("htmlspecialchars_decode", 0, ZifHtmlspecialcharsDecode, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("string"),
		zend.MakeArgName("quote_style"),
	}),
	types.MakeZendFunctionEntryEx("get_html_translation_table", 0, ZifGetHtmlTranslationTable, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("table"),
		zend.MakeArgName("quote_style"),
		zend.MakeArgName("encoding"),
	}),
	types.MakeZendFunctionEntryEx("sha1", 0, ZifSha1, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("raw_output"),
	}),
	types.MakeZendFunctionEntryEx("sha1_file", 0, ZifSha1File, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("raw_output"),
	}),
	types.MakeZendFunctionEntryEx("md5", 0, PhpIfMd5, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("raw_output"),
	}),
	types.MakeZendFunctionEntryEx("md5_file", 0, PhpIfMd5File, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("raw_output"),
	}),
	types.MakeZendFunctionEntryEx("crc32", 0, PhpIfCrc32, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("iptcparse", 0, ZifIptcparse, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("iptcdata"),
	}),
	types.MakeZendFunctionEntryEx("iptcembed", 0, ZifIptcembed, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("iptcdata"),
		zend.MakeArgName("jpeg_file_name"),
		zend.MakeArgName("spool"),
	}),
	types.MakeZendFunctionEntryEx("getimagesize", 0, ZifGetimagesize, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("imagefile"),
		zend.MakeArgInfo("info", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("getimagesizefromstring", 0, ZifGetimagesizefromstring, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("imagefile"),
		zend.MakeArgInfo("info", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("image_type_to_mime_type", 0, ZifImageTypeToMimeType, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("imagetype"),
	}),
	types.MakeZendFunctionEntryEx("image_type_to_extension", 0, ZifImageTypeToExtension, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("imagetype"),
		zend.MakeArgName("include_dot"),
	}),
	types.MakeZendFunctionEntryEx("phpversion", 0, ZifPhpversion, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("extension"),
	}),
	types.MakeZendFunctionEntryEx("phpcredits", 0, ZifPhpcredits, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("flag"),
	}),
	types.MakeZendFunctionEntryEx("php_sapi_name", 0, ZifPhpSapiName, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("php_uname", 0, ZifPhpUname, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("php_ini_scanned_files", 0, ZifPhpIniScannedFiles, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("php_ini_loaded_file", 0, ZifPhpIniLoadedFile, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("strnatcmp", 0, ZifStrnatcmp, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("s1"),
		zend.MakeArgName("s2"),
	}),
	types.MakeZendFunctionEntryEx("strnatcasecmp", 0, ZifStrnatcasecmp, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("s1"),
		zend.MakeArgName("s2"),
	}),
	types.MakeZendFunctionEntryEx("substr_count", 0, ZifSubstrCount, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
		zend.MakeArgName("offset"),
		zend.MakeArgName("length"),
	}),
	types.MakeZendFunctionEntryEx("strspn", 0, ZifStrspn, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("str"),
		zend.MakeArgName("mask"),
		zend.MakeArgName("start"),
		zend.MakeArgName("len"),
	}),
	types.MakeZendFunctionEntryEx("strcspn", 0, ZifStrcspn, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("str"),
		zend.MakeArgName("mask"),
		zend.MakeArgName("start"),
		zend.MakeArgName("len"),
	}),
	types.MakeZendFunctionEntryEx("strtok", 0, ZifStrtok, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("token"),
	}),
	types.MakeZendFunctionEntryEx("strtoupper", 0, ZifStrtoupper, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("strtolower", 0, ZifStrtolower, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("strpos", 0, ZifStrpos, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
		zend.MakeArgName("offset"),
	}),
	types.MakeZendFunctionEntryEx("stripos", 0, ZifStripos, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
		zend.MakeArgName("offset"),
	}),
	types.MakeZendFunctionEntryEx("strrpos", 0, ZifStrrpos, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
		zend.MakeArgName("offset"),
	}),
	types.MakeZendFunctionEntryEx("strripos", 0, ZifStrripos, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
		zend.MakeArgName("offset"),
	}),
	types.MakeZendFunctionEntryEx("strrev", 0, ZifStrrev, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("hebrev", 0, ZifHebrev, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("max_chars_per_line"),
	}),
	types.MakeZendFunctionEntryEx("hebrevc", zend.ZEND_ACC_DEPRECATED, ZifHebrevc, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("max_chars_per_line"),
	}),
	types.MakeZendFunctionEntryEx("nl2br", 0, ZifNl2br, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("is_xhtml"),
	}),
	types.MakeZendFunctionEntryEx("basename", 0, ZifBasename, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("path"),
		zend.MakeArgName("suffix"),
	}),
	types.MakeZendFunctionEntryEx("dirname", 0, ZifDirname, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("path"),
		zend.MakeArgName("levels"),
	}),
	types.MakeZendFunctionEntryEx("pathinfo", 0, ZifPathinfo, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("path"),
		zend.MakeArgName("options"),
	}),
	types.MakeZendFunctionEntryEx("stripslashes", 0, ZifStripslashes, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("stripcslashes", 0, ZifStripcslashes, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("strstr", 0, ZifStrstr, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
		zend.MakeArgName("part"),
	}),
	types.MakeZendFunctionEntryEx("stristr", 0, ZifStristr, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
		zend.MakeArgName("part"),
	}),
	types.MakeZendFunctionEntryEx("strrchr", 0, ZifStrrchr, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
	}),
	types.MakeZendFunctionEntryEx("str_shuffle", 0, ZifStrShuffle, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("str_word_count", 0, ZifStrWordCount, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("format"),
		zend.MakeArgName("charlist"),
	}),
	types.MakeZendFunctionEntryEx("str_split", 0, ZifStrSplit, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("split_length"),
	}),
	types.MakeZendFunctionEntryEx("strpbrk", 0, ZifStrpbrk, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("char_list"),
	}),
	types.MakeZendFunctionEntryEx("substr_compare", 0, ZifSubstrCompare, []zend.ArgInfo{zend.MakeReturnArgInfo(3),
		zend.MakeArgName("main_str"),
		zend.MakeArgName("str"),
		zend.MakeArgName("offset"),
		zend.MakeArgName("length"),
		zend.MakeArgName("case_sensitivity"),
	}),
	types.MakeZendFunctionEntryEx("utf8_encode", 0, ZifUtf8Encode, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("data"),
	}),
	types.MakeZendFunctionEntryEx("utf8_decode", 0, ZifUtf8Decode, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("data"),
	}),
	types.MakeZendFunctionEntryEx("strcoll", 0, ZifStrcoll, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str1"),
		zend.MakeArgName("str2"),
	}),
	types.MakeZendFunctionEntryEx("money_format", zend.ZEND_ACC_DEPRECATED, ZifMoneyFormat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("format"),
		zend.MakeArgName("value"),
	}),
	types.MakeZendFunctionEntryEx("substr", 0, ZifSubstr, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("str"),
		zend.MakeArgName("start"),
		zend.MakeArgName("length"),
	}),
	types.MakeZendFunctionEntryEx("substr_replace", 0, ZifSubstrReplace, []zend.ArgInfo{zend.MakeReturnArgInfo(3),
		zend.MakeArgName("str"),
		zend.MakeArgName("replace"),
		zend.MakeArgName("start"),
		zend.MakeArgName("length"),
	}),
	types.MakeZendFunctionEntryEx("quotemeta", 0, ZifQuotemeta, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("ucfirst", 0, ZifUcfirst, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("lcfirst", 0, ZifLcfirst, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("ucwords", 0, ZifUcwords, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("delimiters"),
	}),
	types.MakeZendFunctionEntryEx("strtr", 0, ZifStrtr, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("str"),
		zend.MakeArgName("from"),
		zend.MakeArgName("to"),
	}),
	types.MakeZendFunctionEntryEx("addslashes", 0, ZifAddslashes, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("addcslashes", 0, ZifAddcslashes, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
		zend.MakeArgName("charlist"),
	}),
	types.MakeZendFunctionEntryEx("rtrim", 0, ZifRtrim, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("character_mask"),
	}),
	types.MakeZendFunctionEntryEx("str_replace", 0, ZifStrReplace, []zend.ArgInfo{zend.MakeReturnArgInfo(3),
		zend.MakeArgName("search"),
		zend.MakeArgName("replace"),
		zend.MakeArgName("subject"),
		zend.MakeArgInfo("replace_count", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("str_ireplace", 0, ZifStrIreplace, []zend.ArgInfo{zend.MakeReturnArgInfo(3),
		zend.MakeArgName("search"),
		zend.MakeArgName("replace"),
		zend.MakeArgName("subject"),
		zend.MakeArgInfo("replace_count", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("str_repeat", 0, ZifStrRepeat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("input"),
		zend.MakeArgName("mult"),
	}),
	types.MakeZendFunctionEntryEx("count_chars", 0, ZifCountChars, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("input"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("chunk_split", 0, ZifChunkSplit, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("chunklen"),
		zend.MakeArgName("ending"),
	}),
	types.MakeZendFunctionEntryEx("trim", 0, ZifTrim, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("character_mask"),
	}),
	types.MakeZendFunctionEntryEx("ltrim", 0, ZifLtrim, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("character_mask"),
	}),
	types.MakeZendFunctionEntryEx("strip_tags", 0, ZifStripTags, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("allowable_tags"),
	}),
	types.MakeZendFunctionEntryEx("similar_text", 0, ZifSimilarText, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("str1"),
		zend.MakeArgName("str2"),
		zend.MakeArgInfo("percent", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("explode", 0, ZifExplode, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("separator"),
		zend.MakeArgName("str"),
		zend.MakeArgName("limit"),
	}),
	types.MakeZendFunctionEntryEx("implode", 0, ZifImplode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("glue"),
		zend.MakeArgName("pieces"),
	}),
	types.MakeZendFunctionEntryEx("join", 0, ZifImplode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("glue"),
		zend.MakeArgName("pieces"),
	}),
	types.MakeZendFunctionEntryEx("setlocale", 0, ZifSetlocale, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("category"),
		zend.MakeArgInfo("locales", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("localeconv", 0, ZifLocaleconv, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("soundex", 0, ZifSoundex, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("levenshtein", 0, ZifLevenshtein, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("str1"),
		zend.MakeArgName("str2"),
		zend.MakeArgName("cost_ins"),
		zend.MakeArgName("cost_rep"),
		zend.MakeArgName("cost_del"),
	}),
	types.MakeZendFunctionEntryEx("chr", 0, ZifChr, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("codepoint"),
	}),
	types.MakeZendFunctionEntryEx("ord", 0, ZifOrd, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("character"),
	}),
	types.MakeZendFunctionEntryEx("parse_str", 0, ZifParseStr, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("encoded_string"),
		zend.MakeArgInfo("result", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("str_getcsv", 0, ZifStrGetcsv, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("string"),
		zend.MakeArgName("delimiter"),
		zend.MakeArgName("enclosure"),
		zend.MakeArgName("escape"),
	}),
	types.MakeZendFunctionEntryEx("str_pad", 0, ZifStrPad, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("input"),
		zend.MakeArgName("pad_length"),
		zend.MakeArgName("pad_string"),
		zend.MakeArgName("pad_type"),
	}),
	types.MakeZendFunctionEntryEx("chop", 0, ZifRtrim, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("character_mask"),
	}),
	types.MakeZendFunctionEntryEx("strchr", 0, ZifStrstr, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
		zend.MakeArgName("part"),
	}),
	types.MakeZendFunctionEntryEx("sprintf", 0, ZifUserSprintf, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("format"),
		zend.MakeArgInfo("args", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("printf", 0, ZifUserPrintf, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("format"),
		zend.MakeArgInfo("args", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("vprintf", 0, ZifVprintf, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("format"),
		zend.MakeArgName("args"),
	}),
	types.MakeZendFunctionEntryEx("vsprintf", 0, ZifVsprintf, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("format"),
		zend.MakeArgName("args"),
	}),
	types.MakeZendFunctionEntryEx("fprintf", 0, ZifFprintf, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("format"),
		zend.MakeArgInfo("args", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("vfprintf", 0, ZifVfprintf, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("stream"),
		zend.MakeArgName("format"),
		zend.MakeArgName("args"),
	}),
	types.MakeZendFunctionEntryEx("sscanf", 0, ZifSscanf, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("str"),
		zend.MakeArgName("format"),
		zend.MakeArgInfo("vars", zend.ArgInfoByRef(1), ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("fscanf", 0, ZifFscanf, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("format"),
		zend.MakeArgInfo("vars", zend.ArgInfoByRef(1), ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("parse_url", 0, ZifParseUrl, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("url"),
		zend.MakeArgName("component"),
	}),
	types.MakeZendFunctionEntryEx("urlencode", 0, ZifUrlencode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("urldecode", 0, ZifUrldecode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("rawurlencode", 0, ZifRawurlencode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("rawurldecode", 0, ZifRawurldecode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("http_build_query", 0, ZifHttpBuildQuery, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("formdata"),
		zend.MakeArgName("prefix"),
		zend.MakeArgName("arg_separator"),
		zend.MakeArgName("enc_type"),
	}),
	types.MakeZendFunctionEntryEx("readlink", 0, ZifReadlink, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("linkinfo", 0, ZifLinkinfo, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("symlink", 0, ZifSymlink, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("target"),
		zend.MakeArgName("link"),
	}),
	types.MakeZendFunctionEntryEx("link", 0, ZifLink, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("target"),
		zend.MakeArgName("link"),
	}),
	types.MakeZendFunctionEntryEx("unlink", 0, ZifUnlink, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("exec", 0, ZifExec, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("command"),
		zend.MakeArgInfo("output", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("return_value", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("system", 0, ZifSystem, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("command"),
		zend.MakeArgInfo("return_value", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("escapeshellcmd", 0, ZifEscapeshellcmd, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("command"),
	}),
	types.MakeZendFunctionEntryEx("escapeshellarg", 0, ZifEscapeshellarg, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("passthru", 0, ZifPassthru, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("command"),
		zend.MakeArgInfo("return_value", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("shell_exec", 0, ZifShellExec, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("cmd"),
	}),
	types.MakeZendFunctionEntryEx("proc_open", 0, ZifProcOpen, []zend.ArgInfo{zend.MakeReturnArgInfo(3),
		zend.MakeArgName("command"),
		zend.MakeArgName("descriptorspec"),
		zend.MakeArgInfo("pipes", zend.ArgInfoByRef(1)),
		zend.MakeArgName("cwd"),
		zend.MakeArgName("env"),
		zend.MakeArgName("other_options"),
	}),
	types.MakeZendFunctionEntryEx("proc_close", 0, ZifProcClose, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("process"),
	}),
	types.MakeZendFunctionEntryEx("proc_terminate", 0, ZifProcTerminate, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("process"),
		zend.MakeArgName("signal"),
	}),
	types.MakeZendFunctionEntryEx("proc_get_status", 0, ZifProcGetStatus, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("process"),
	}),
	types.MakeZendFunctionEntryEx("proc_nice", 0, ZifProcNice, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("priority"),
	}),
	types.MakeZendFunctionEntryEx("rand", 0, ZifRand, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("min"),
		zend.MakeArgName("max"),
	}),
	types.MakeZendFunctionEntryEx("srand", 0, ZifMtSrand, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("seed"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("getrandmax", 0, ZifMtGetrandmax, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("mt_rand", 0, ZifMtRand, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("min"),
		zend.MakeArgName("max"),
	}),
	types.MakeZendFunctionEntryEx("mt_srand", 0, ZifMtSrand, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("seed"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("mt_getrandmax", 0, ZifMtGetrandmax, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("random_bytes", 0, ZifRandomBytes, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("length"),
	}),
	types.MakeZendFunctionEntryEx("random_int", 0, ZifRandomInt, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("min"),
		zend.MakeArgName("max"),
	}),
	types.MakeZendFunctionEntryEx("getservbyname", 0, ZifGetservbyname, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("service"),
		zend.MakeArgName("protocol"),
	}),
	types.MakeZendFunctionEntryEx("getservbyport", 0, ZifGetservbyport, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("port"),
		zend.MakeArgName("protocol"),
	}),
	types.MakeZendFunctionEntryEx("getprotobyname", 0, ZifGetprotobyname, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("name"),
	}),
	types.MakeZendFunctionEntryEx("getprotobynumber", 0, ZifGetprotobynumber, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("proto"),
	}),
	types.MakeZendFunctionEntryEx("getmyuid", 0, ZifGetmyuid, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("getmygid", 0, ZifGetmygid, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("getmypid", 0, ZifGetmypid, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("getmyinode", 0, ZifGetmyinode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("getlastmod", 0, ZifGetlastmod, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("base64_decode", 0, ZifBase64Decode, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("strict"),
	}),
	types.MakeZendFunctionEntryEx("base64_encode", 0, ZifBase64Encode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("password_hash", 0, ZifPasswordHash, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("password"),
		zend.MakeArgName("algo"),
		zend.MakeArgName("options"),
	}),
	types.MakeZendFunctionEntryEx("password_get_info", 0, ZifPasswordGetInfo, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("hash"),
	}),
	types.MakeZendFunctionEntryEx("password_needs_rehash", 0, ZifPasswordNeedsRehash, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("hash"),
		zend.MakeArgName("algo"),
		zend.MakeArgName("options"),
	}),
	types.MakeZendFunctionEntryEx("password_verify", 0, ZifPasswordVerify, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("password"),
		zend.MakeArgName("hash"),
	}),
	types.MakeZendFunctionEntryEx("password_algos", 0, ZifPasswordAlgos, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("convert_uuencode", 0, ZifConvertUuencode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("data"),
	}),
	types.MakeZendFunctionEntryEx("convert_uudecode", 0, ZifConvertUudecode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("data"),
	}),
	types.MakeZendFunctionEntryEx("abs", 0, ZifAbs, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("ceil", 0, ZifCeil, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("floor", 0, ZifFloor, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("round", 0, ZifRound, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("number"),
		zend.MakeArgName("precision"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("sin", 0, ZifSin, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("cos", 0, ZifCos, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("tan", 0, ZifTan, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("asin", 0, ZifAsin, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("acos", 0, ZifAcos, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("atan", 0, ZifAtan, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("atanh", 0, ZifAtanh, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("atan2", 0, ZifAtan2, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("y"),
		zend.MakeArgName("x"),
	}),
	types.MakeZendFunctionEntryEx("sinh", 0, ZifSinh, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("cosh", 0, ZifCosh, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("tanh", 0, ZifTanh, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("asinh", 0, ZifAsinh, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("acosh", 0, ZifAcosh, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("expm1", 0, ZifExpm1, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("log1p", 0, ZifLog1p, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("pi", 0, ZifPi, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("is_finite", 0, ZifIsFinite, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("val"),
	}),
	types.MakeZendFunctionEntryEx("is_nan", 0, ZifIsNan, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("val"),
	}),
	types.MakeZendFunctionEntryEx("is_infinite", 0, ZifIsInfinite, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("val"),
	}),
	types.MakeZendFunctionEntryEx("pow", 0, ZifPow, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("base"),
		zend.MakeArgName("exponent"),
	}),
	types.MakeZendFunctionEntryEx("exp", 0, ZifExp, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("log", 0, ZifLog, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("number"),
		zend.MakeArgName("base"),
	}),
	types.MakeZendFunctionEntryEx("log10", 0, ZifLog10, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("sqrt", 0, ZifSqrt, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("hypot", 0, ZifHypot, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("num1"),
		zend.MakeArgName("num2"),
	}),
	types.MakeZendFunctionEntryEx("deg2rad", 0, ZifDeg2rad, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("rad2deg", 0, ZifRad2deg, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
	}),
	types.MakeZendFunctionEntryEx("bindec", 0, ZifBindec, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("binary_number"),
	}),
	types.MakeZendFunctionEntryEx("hexdec", 0, ZifHexdec, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("hexadecimal_number"),
	}),
	types.MakeZendFunctionEntryEx("octdec", 0, ZifOctdec, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("octal_number"),
	}),
	types.MakeZendFunctionEntryEx("decbin", 0, ZifDecbin, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("decimal_number"),
	}),
	types.MakeZendFunctionEntryEx("decoct", 0, ZifDecoct, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("decimal_number"),
	}),
	types.MakeZendFunctionEntryEx("dechex", 0, ZifDechex, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("decimal_number"),
	}),
	types.MakeZendFunctionEntryEx("base_convert", 0, ZifBaseConvert, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("number"),
		zend.MakeArgName("frombase"),
		zend.MakeArgName("tobase"),
	}),
	types.MakeZendFunctionEntryEx("number_format", 0, ZifNumberFormat, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("number"),
		zend.MakeArgName("num_decimal_places"),
		zend.MakeArgName("dec_separator"),
		zend.MakeArgName("thousands_separator"),
	}),
	types.MakeZendFunctionEntryEx("fmod", 0, ZifFmod, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("x"),
		zend.MakeArgName("y"),
	}),
	types.MakeZendFunctionEntryEx("intdiv", 0, ZifIntdiv, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("dividend"),
		zend.MakeArgName("divisor"),
	}),
	types.MakeZendFunctionEntryEx("inet_ntop", 0, ZifInetNtop, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("in_addr"),
	}),
	types.MakeZendFunctionEntryEx("inet_pton", 0, PhpInetPton, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("ip_address"),
	}),
	types.MakeZendFunctionEntryEx("ip2long", 0, ZifIp2long, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("ip_address"),
	}),
	types.MakeZendFunctionEntryEx("long2ip", 0, ZifLong2ip, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("proper_address"),
	}),
	types.MakeZendFunctionEntryEx("getenv", 0, ZifGetenv, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("varname"),
		zend.MakeArgName("local_only"),
	}),
	types.MakeZendFunctionEntryEx("putenv", 0, ZifPutenv, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("setting"),
	}),
	types.MakeZendFunctionEntryEx("getopt", 0, ZifGetopt, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("options"),
		zend.MakeArgName("opts"),
		zend.MakeArgInfo("optind", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("sys_getloadavg", 0, ZifSysGetloadavg, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("microtime", 0, ZifMicrotime, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("get_as_float"),
	}),
	types.MakeZendFunctionEntryEx("gettimeofday", 0, ZifGettimeofday, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("get_as_float"),
	}),
	types.MakeZendFunctionEntryEx("getrusage", 0, ZifGetrusage, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("who"),
	}),
	types.MakeZendFunctionEntryEx("hrtime", 0, ZifHrtime, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("get_as_number"),
	}),
	types.MakeZendFunctionEntryEx("uniqid", 0, ZifUniqid, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("prefix"),
		zend.MakeArgName("more_entropy"),
	}),
	types.MakeZendFunctionEntryEx("quoted_printable_decode", 0, ZifQuotedPrintableDecode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("quoted_printable_encode", 0, ZifQuotedPrintableEncode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("convert_cyr_string", zend.ZEND_ACC_DEPRECATED, ZifConvertCyrString, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
		zend.MakeArgName("from"),
		zend.MakeArgName("to"),
	}),
	types.MakeZendFunctionEntryEx("get_current_user", 0, ZifGetCurrentUser, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("set_time_limit", 0, ZifSetTimeLimit, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("seconds"),
	}),
	types.MakeZendFunctionEntryEx("header_register_callback", 0, ZifHeaderRegisterCallback, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("callback"),
	}),
	types.MakeZendFunctionEntryEx("get_cfg_var", 0, ZifGetCfgVar, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("option_name"),
	}),
	types.MakeZendFunctionEntryEx("get_magic_quotes_gpc", zend.ZEND_ACC_DEPRECATED, ZifGetMagicQuotesGpc, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("get_magic_quotes_runtime", zend.ZEND_ACC_DEPRECATED, ZifGetMagicQuotesRuntime, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("error_log", 0, ZifErrorLog, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("message"),
		zend.MakeArgName("message_type"),
		zend.MakeArgName("destination"),
		zend.MakeArgName("extra_headers"),
	}),
	types.MakeZendFunctionEntryEx("error_get_last", 0, ZifErrorGetLast, []zend.ArgInfo{zend.MakeReturnArgInfo(0)}),
	types.MakeZendFunctionEntryEx("error_clear_last", 0, ZifErrorClearLast, []zend.ArgInfo{zend.MakeReturnArgInfo(0)}),
	types.MakeZendFunctionEntryEx("call_user_func", 0, ZifCallUserFunc, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("function_name"),
		zend.MakeArgInfo("parameters", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("call_user_func_array", 0, ZifCallUserFuncArray, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("function_name"),
		zend.MakeArgName("parameters"),
	}),
	types.MakeZendFunctionEntryEx("forward_static_call", 0, ZifForwardStaticCall, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("function_name"),
		zend.MakeArgInfo("parameters", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("forward_static_call_array", 0, ZifForwardStaticCallArray, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("function_name"),
		zend.MakeArgName("parameters"),
	}),
	types.MakeZendFunctionEntryEx("serialize", 0, ZifSerialize, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("unserialize", 0, ZifUnserialize, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("variable_representation"),
		zend.MakeArgName("allowed_classes"),
	}),
	types.MakeZendFunctionEntryEx("var_dump", 0, ZifVarDump, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("vars", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("var_export", 0, ZifVarExport, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("var"),
		zend.MakeArgName("return"),
	}),
	types.MakeZendFunctionEntryEx("debug_zval_dump", 0, ZifDebugZvalDump, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("vars", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("print_r", 0, ZifPrintR, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("var"),
		zend.MakeArgName("return"),
	}),
	types.MakeZendFunctionEntryEx("memory_get_usage", 0, ZifMemoryGetUsage, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("real_usage"),
	}),
	types.MakeZendFunctionEntryEx("memory_get_peak_usage", 0, ZifMemoryGetPeakUsage, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("real_usage"),
	}),
	types.MakeZendFunctionEntryEx("register_shutdown_function", 0, ZifRegisterShutdownFunction, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("function_name"),
		zend.MakeArgInfo("parameters", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("register_tick_function", 0, ZifRegisterTickFunction, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("function_name"),
		zend.MakeArgInfo("parameters", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("unregister_tick_function", 0, ZifUnregisterTickFunction, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("function_name"),
	}),
	types.MakeZendFunctionEntryEx("highlight_file", 0, ZifHighlightFile, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("file_name"),
		zend.MakeArgName("return"),
	}),
	types.MakeZendFunctionEntryEx("show_source", 0, ZifHighlightFile, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("file_name"),
		zend.MakeArgName("return"),
	}),
	types.MakeZendFunctionEntryEx("highlight_string", 0, ZifHighlightString, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("string"),
		zend.MakeArgName("return"),
	}),
	types.MakeZendFunctionEntryEx("php_strip_whitespace", 0, ZifPhpStripWhitespace, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("file_name"),
	}),
	types.MakeZendFunctionEntryEx("ini_get", 0, ZifIniGet, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("varname"),
	}),
	types.MakeZendFunctionEntryEx("ini_get_all", 0, ZifIniGetAll, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("extension"),
		zend.MakeArgName("details"),
	}),
	types.MakeZendFunctionEntryEx("ini_set", 0, ZifIniSet, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("varname"),
		zend.MakeArgName("newvalue"),
	}),
	types.MakeZendFunctionEntryEx("ini_alter", 0, ZifIniSet, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("varname"),
		zend.MakeArgName("newvalue"),
	}),
	types.MakeZendFunctionEntryEx("ini_restore", 0, ZifIniRestore, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("varname"),
	}),
	types.MakeZendFunctionEntryEx("get_include_path", 0, ZifGetIncludePath, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("set_include_path", 0, ZifSetIncludePath, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("new_include_path"),
	}),
	types.MakeZendFunctionEntryEx("restore_include_path", zend.ZEND_ACC_DEPRECATED, ZifRestoreIncludePath, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("setcookie", 0, ZifSetcookie, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("name"),
		zend.MakeArgName("value"),
		zend.MakeArgName("expires_or_options"),
		zend.MakeArgName("path"),
		zend.MakeArgName("domain"),
		zend.MakeArgName("secure"),
		zend.MakeArgName("httponly"),
	}),
	types.MakeZendFunctionEntryEx("setrawcookie", 0, ZifSetrawcookie, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("name"),
		zend.MakeArgName("value"),
		zend.MakeArgName("expires_or_options"),
		zend.MakeArgName("path"),
		zend.MakeArgName("domain"),
		zend.MakeArgName("secure"),
		zend.MakeArgName("httponly"),
	}),
	types.MakeZendFunctionEntryEx("header", 0, ZifHeader, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("header"),
		zend.MakeArgName("replace"),
		zend.MakeArgName("http_response_code"),
	}),
	types.MakeZendFunctionEntryEx("header_remove", 0, ZifHeaderRemove, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("name"),
	}),
	types.MakeZendFunctionEntryEx("headers_sent", 0, ZifHeadersSent, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgInfo("file", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("line", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("headers_list", 0, ZifHeadersList, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("http_response_code", 0, ZifHttpResponseCode, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("response_code"),
	}),
	types.MakeZendFunctionEntryEx("connection_aborted", 0, ZifConnectionAborted, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("connection_status", 0, ZifConnectionStatus, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ignore_user_abort", 0, ZifIgnoreUserAbort, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("value"),
	}),
	types.MakeZendFunctionEntryEx("parse_ini_file", 0, ZifParseIniFile, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("process_sections"),
		zend.MakeArgName("scanner_mode"),
	}),
	types.MakeZendFunctionEntryEx("parse_ini_string", 0, ZifParseIniString, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("ini_string"),
		zend.MakeArgName("process_sections"),
		zend.MakeArgName("scanner_mode"),
	}),
	types.MakeZendFunctionEntryEx("is_uploaded_file", 0, ZifIsUploadedFile, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("path"),
	}),
	types.MakeZendFunctionEntryEx("move_uploaded_file", 0, ZifMoveUploadedFile, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("path"),
		zend.MakeArgName("new_path"),
	}),
	types.MakeZendFunctionEntryEx("gethostbyaddr", 0, ZifGethostbyaddr, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("ip_address"),
	}),
	types.MakeZendFunctionEntryEx("gethostbyname", 0, ZifGethostbyname, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("hostname"),
	}),
	types.MakeZendFunctionEntryEx("gethostbynamel", 0, ZifGethostbynamel, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("hostname"),
	}),
	types.MakeZendFunctionEntryEx("gethostname", 0, ZifGethostname, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("net_get_interfaces", 0, ZifNetGetInterfaces, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("dns_check_record", 0, ZifDnsCheckRecord, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("host"),
		zend.MakeArgName("type"),
	}),
	types.MakeZendFunctionEntryEx("checkdnsrr", 0, ZifDnsCheckRecord, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("host"),
		zend.MakeArgName("type"),
	}),
	types.MakeZendFunctionEntryEx("dns_get_mx", 0, ZifDnsGetMx, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("hostname"),
		zend.MakeArgInfo("mxhosts", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("weight", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("getmxrr", 0, ZifDnsGetMx, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("hostname"),
		zend.MakeArgInfo("mxhosts", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("weight", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("dns_get_record", 0, ZifDnsGetRecord, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("hostname"),
		zend.MakeArgName("type"),
		zend.MakeArgInfo("authns", zend.ArgInfoType(types.ZEND_TYPE_ENCODE(types.IS_ARRAY, 1)), zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("addtl", zend.ArgInfoType(types.ZEND_TYPE_ENCODE(types.IS_ARRAY, 1)), zend.ArgInfoByRef(1)),
		zend.MakeArgName("raw"),
	}),
	types.MakeZendFunctionEntryEx("intval", 0, ZifIntval, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("var"),
		zend.MakeArgName("base"),
	}),
	types.MakeZendFunctionEntryEx("floatval", 0, ZifFloatval, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("doubleval", 0, ZifFloatval, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("strval", 0, ZifStrval, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("boolval", 0, ZifBoolval, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("gettype", 0, ZifGettype, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("settype", 0, ZifSettype, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("var", zend.ArgInfoByRef(1)),
		zend.MakeArgName("type"),
	}),
	types.MakeZendFunctionEntryEx("is_null", 0, ZifIsNull, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_resource", 0, ZifIsResource, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_bool", 0, ZifIsBool, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_int", 0, ZifIsInt, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_float", 0, ZifIsFloat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_integer", 0, ZifIsInt, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_long", 0, ZifIsInt, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_double", 0, ZifIsFloat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_real", zend.ZEND_ACC_DEPRECATED, ZifIsFloat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_numeric", 0, ZifIsNumeric, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("value"),
	}),
	types.MakeZendFunctionEntryEx("is_string", 0, ZifIsString, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_array", 0, ZifIsArray, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_object", 0, ZifIsObject, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_scalar", 0, ZifIsScalar, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("value"),
	}),
	types.MakeZendFunctionEntryEx("is_callable", 0, ZifIsCallable, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("var"),
		zend.MakeArgName("syntax_only"),
		zend.MakeArgInfo("callable_name", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("is_iterable", 0, ZifIsIterable, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_countable", 0, ZifIsCountable, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("pclose", 0, ZifPclose, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("popen", 0, ZifPopen, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("command"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("readfile", 0, ZifReadfile, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("flags"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("rewind", 0, ZifRewind, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("rmdir", 0, ZifRmdir, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("dirname"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("umask", 0, ZifUmask, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("mask"),
	}),
	types.MakeZendFunctionEntryEx("fclose", 0, ZifFclose, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("feof", 0, ZifFeof, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("fgetc", 0, ZifFgetc, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("fgets", 0, ZifFgets, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("length"),
	}),
	types.MakeZendFunctionEntryEx("fgetss", zend.ZEND_ACC_DEPRECATED, ZifFgetss, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("length"),
		zend.MakeArgName("allowable_tags"),
	}),
	types.MakeZendFunctionEntryEx("fread", 0, ZifFread, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("length"),
	}),
	types.MakeZendFunctionEntryEx("fopen", 0, PhpIfFopen, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("filename"),
		zend.MakeArgName("mode"),
		zend.MakeArgName("use_include_path"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("fpassthru", 0, ZifFpassthru, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("ftruncate", 0, PhpIfFtruncate, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("size"),
	}),
	types.MakeZendFunctionEntryEx("fstat", 0, PhpIfFstat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("fseek", 0, ZifFseek, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("fp"),
		zend.MakeArgName("offset"),
		zend.MakeArgName("whence"),
	}),
	types.MakeZendFunctionEntryEx("ftell", 0, ZifFtell, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("fflush", 0, ZifFflush, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("fwrite", 0, ZifFwrite, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("fp"),
		zend.MakeArgName("str"),
		zend.MakeArgName("length"),
	}),
	types.MakeZendFunctionEntryEx("fputs", 0, ZifFwrite, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("fp"),
		zend.MakeArgName("str"),
		zend.MakeArgName("length"),
	}),
	types.MakeZendFunctionEntryEx("mkdir", 0, ZifMkdir, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("pathname"),
		zend.MakeArgName("mode"),
		zend.MakeArgName("recursive"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("rename", 0, ZifRename, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("old_name"),
		zend.MakeArgName("new_name"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("copy", 0, ZifCopy, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("source_file"),
		zend.MakeArgName("destination_file"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("tempnam", 0, ZifTempnam, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("dir"),
		zend.MakeArgName("prefix"),
	}),
	types.MakeZendFunctionEntryEx("tmpfile", 0, PhpIfTmpfile, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("file", 0, ZifFile, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("flags"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("file_get_contents", 0, ZifFileGetContents, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("flags"),
		zend.MakeArgName("context"),
		zend.MakeArgName("offset"),
		zend.MakeArgName("maxlen"),
	}),
	types.MakeZendFunctionEntryEx("file_put_contents", 0, ZifFilePutContents, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("filename"),
		zend.MakeArgName("data"),
		zend.MakeArgName("flags"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("stream_select", 0, ZifStreamSelect, []zend.ArgInfo{zend.MakeReturnArgInfo(4),
		zend.MakeArgInfo("read_streams", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("write_streams", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("except_streams", zend.ArgInfoByRef(1)),
		zend.MakeArgName("tv_sec"),
		zend.MakeArgName("tv_usec"),
	}),
	types.MakeZendFunctionEntryEx("stream_context_create", 0, ZifStreamContextCreate, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("options"),
		zend.MakeArgName("params"),
	}),
	types.MakeZendFunctionEntryEx("stream_context_set_params", 0, ZifStreamContextSetParams, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("stream_or_context"),
		zend.MakeArgName("options"),
	}),
	types.MakeZendFunctionEntryEx("stream_context_get_params", 0, ZifStreamContextGetParams, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("stream_or_context"),
	}),
	types.MakeZendFunctionEntryEx("stream_context_set_option", 0, ZifStreamContextSetOption, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream_or_context"),
		zend.MakeArgName("wrappername"),
		zend.MakeArgName("optionname"),
		zend.MakeArgName("value"),
	}),
	types.MakeZendFunctionEntryEx("stream_context_get_options", 0, ZifStreamContextGetOptions, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("stream_or_context"),
	}),
	types.MakeZendFunctionEntryEx("stream_context_get_default", 0, ZifStreamContextGetDefault, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("options"),
	}),
	types.MakeZendFunctionEntryEx("stream_context_set_default", 0, ZifStreamContextSetDefault, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("options"),
	}),
	types.MakeZendFunctionEntryEx("stream_filter_prepend", 0, ZifStreamFilterPrepend, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("filtername"),
		zend.MakeArgName("read_write"),
		zend.MakeArgName("filterparams"),
	}),
	types.MakeZendFunctionEntryEx("stream_filter_append", 0, ZifStreamFilterAppend, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("filtername"),
		zend.MakeArgName("read_write"),
		zend.MakeArgName("filterparams"),
	}),
	types.MakeZendFunctionEntryEx("stream_filter_remove", 0, ZifStreamFilterRemove, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("stream_filter"),
	}),
	types.MakeZendFunctionEntryEx("stream_socket_client", 0, ZifStreamSocketClient, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("remoteaddress"),
		zend.MakeArgInfo("errcode", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("errstring", zend.ArgInfoByRef(1)),
		zend.MakeArgName("timeout"),
		zend.MakeArgName("flags"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("stream_socket_server", 0, ZifStreamSocketServer, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("localaddress"),
		zend.MakeArgInfo("errcode", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("errstring", zend.ArgInfoByRef(1)),
		zend.MakeArgName("flags"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("stream_socket_accept", 0, ZifStreamSocketAccept, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("serverstream"),
		zend.MakeArgName("timeout"),
		zend.MakeArgInfo("peername", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("stream_socket_get_name", 0, ZifStreamSocketGetName, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("stream"),
		zend.MakeArgName("want_peer"),
	}),
	types.MakeZendFunctionEntryEx("stream_socket_recvfrom", 0, ZifStreamSocketRecvfrom, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("amount"),
		zend.MakeArgName("flags"),
		zend.MakeArgInfo("remote_addr", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("stream_socket_sendto", 0, ZifStreamSocketSendto, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("data"),
		zend.MakeArgName("flags"),
		zend.MakeArgName("target_addr"),
	}),
	types.MakeZendFunctionEntryEx("stream_socket_enable_crypto", 0, ZifStreamSocketEnableCrypto, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("enable"),
		zend.MakeArgName("cryptokind"),
		zend.MakeArgName("sessionstream"),
	}),
	types.MakeZendFunctionEntryEx("stream_socket_shutdown", 0, ZifStreamSocketShutdown, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("stream"),
		zend.MakeArgName("how"),
	}),
	types.MakeZendFunctionEntryEx("stream_socket_pair", 0, ZifStreamSocketPair, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("domain"),
		zend.MakeArgName("type"),
		zend.MakeArgName("protocol"),
	}),
	types.MakeZendFunctionEntryEx("stream_copy_to_stream", 0, ZifStreamCopyToStream, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("source"),
		zend.MakeArgName("dest"),
		zend.MakeArgName("maxlen"),
		zend.MakeArgName("pos"),
	}),
	types.MakeZendFunctionEntryEx("stream_get_contents", 0, ZifStreamGetContents, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("source"),
		zend.MakeArgName("maxlen"),
		zend.MakeArgName("offset"),
	}),
	types.MakeZendFunctionEntryEx("stream_supports_lock", 0, ZifStreamSupportsLock, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("stream"),
	}),
	types.MakeZendFunctionEntryEx("stream_isatty", 0, ZifStreamIsatty, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("stream"),
	}),
	types.MakeZendFunctionEntryEx("fgetcsv", 0, ZifFgetcsv, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("length"),
		zend.MakeArgName("delimiter"),
		zend.MakeArgName("enclosure"),
		zend.MakeArgName("escape"),
	}),
	types.MakeZendFunctionEntryEx("fputcsv", 0, ZifFputcsv, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("fp"),
		zend.MakeArgName("fields"),
		zend.MakeArgName("delimiter"),
		zend.MakeArgName("enclosure"),
		zend.MakeArgName("escape_char"),
	}),
	types.MakeZendFunctionEntryEx("flock", 0, ZifFlock, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("fp"),
		zend.MakeArgName("operation"),
		zend.MakeArgInfo("wouldblock", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("get_meta_tags", 0, ZifGetMetaTags, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("use_include_path"),
	}),
	types.MakeZendFunctionEntryEx("stream_set_read_buffer", 0, ZifStreamSetReadBuffer, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("buffer"),
	}),
	types.MakeZendFunctionEntryEx("stream_set_write_buffer", 0, ZifStreamSetWriteBuffer, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("buffer"),
	}),
	types.MakeZendFunctionEntryEx("set_file_buffer", 0, ZifStreamSetWriteBuffer, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("buffer"),
	}),
	types.MakeZendFunctionEntryEx("stream_set_chunk_size", 0, ZifStreamSetChunkSize, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("chunk_size"),
	}),
	types.MakeZendFunctionEntryEx("stream_set_blocking", 0, ZifStreamSetBlocking, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("socket"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("socket_set_blocking", 0, ZifStreamSetBlocking, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("socket"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("stream_get_meta_data", 0, ZifStreamGetMetaData, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("stream_get_line", 0, ZifStreamGetLine, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("maxlen"),
		zend.MakeArgName("ending"),
	}),
	types.MakeZendFunctionEntryEx("stream_wrapper_register", 0, ZifStreamWrapperRegister, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("protocol"),
		zend.MakeArgName("classname"),
		zend.MakeArgName("flags"),
	}),
	types.MakeZendFunctionEntryEx("stream_register_wrapper", 0, ZifStreamWrapperRegister, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("protocol"),
		zend.MakeArgName("classname"),
		zend.MakeArgName("flags"),
	}),
	types.MakeZendFunctionEntryEx("stream_wrapper_unregister", 0, ZifStreamWrapperUnregister, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("protocol"),
	}),
	types.MakeZendFunctionEntryEx("stream_wrapper_restore", 0, ZifStreamWrapperRestore, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("protocol"),
	}),
	types.MakeZendFunctionEntryEx("stream_get_wrappers", 0, ZifStreamGetWrappers, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("stream_get_transports", 0, ZifStreamGetTransports, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("stream_resolve_include_path", 0, ZifStreamResolveIncludePath, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("stream_is_local", 0, ZifStreamIsLocal, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("stream"),
	}),
	types.MakeZendFunctionEntryEx("get_headers", 0, ZifGetHeaders, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("url"),
		zend.MakeArgName("format"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("stream_set_timeout", 0, ZifStreamSetTimeout, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("seconds"),
		zend.MakeArgName("microseconds"),
	}),
	types.MakeZendFunctionEntryEx("socket_set_timeout", 0, ZifStreamSetTimeout, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("seconds"),
		zend.MakeArgName("microseconds"),
	}),
	types.MakeZendFunctionEntryEx("socket_get_status", 0, ZifStreamGetMetaData, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	types.MakeZendFunctionEntryEx("realpath", 0, ZifRealpath, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("path"),
	}),
	types.MakeZendFunctionEntryEx("fnmatch", 0, ZifFnmatch, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("pattern"),
		zend.MakeArgName("filename"),
		zend.MakeArgName("flags"),
	}),
	types.MakeZendFunctionEntryEx("fsockopen", 0, ZifFsockopen, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("hostname"),
		zend.MakeArgName("port"),
		zend.MakeArgInfo("errno", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("errstr", zend.ArgInfoByRef(1)),
		zend.MakeArgName("timeout"),
	}),
	types.MakeZendFunctionEntryEx("pfsockopen", 0, ZifPfsockopen, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("hostname"),
		zend.MakeArgName("port"),
		zend.MakeArgInfo("errno", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("errstr", zend.ArgInfoByRef(1)),
		zend.MakeArgName("timeout"),
	}),
	types.MakeZendFunctionEntryEx("pack", 0, ZifPack, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("format"),
		zend.MakeArgInfo("args", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("unpack", 0, ZifUnpack, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("format"),
		zend.MakeArgName("input"),
		zend.MakeArgName("offset"),
	}),
	types.MakeZendFunctionEntryEx("get_browser", 0, ZifGetBrowser, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("browser_name"),
		zend.MakeArgName("return_array"),
	}),
	types.MakeZendFunctionEntryEx("crypt", 0, ZifCrypt, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("salt"),
	}),
	types.MakeZendFunctionEntryEx("opendir", 0, ZifOpendir, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("path"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("closedir", 0, ZifClosedir, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("dir_handle"),
	}),
	types.MakeZendFunctionEntryEx("chdir", 0, ZifChdir, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("directory"),
	}),
	types.MakeZendFunctionEntryEx("chroot", 0, ZifChroot, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("directory"),
	}),
	types.MakeZendFunctionEntryEx("getcwd", 0, ZifGetcwd, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("rewinddir", 0, ZifRewinddir, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("dir_handle"),
	}),
	types.MakeZendFunctionEntryEx("readdir", 0, PhpIfReaddir, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("dir_handle"),
	}),
	types.MakeZendFunctionEntryEx("dir", 0, ZifGetdir, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("directory"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("scandir", 0, ZifScandir, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("dir"),
		zend.MakeArgName("sorting_order"),
		zend.MakeArgName("context"),
	}),
	types.MakeZendFunctionEntryEx("glob", 0, ZifGlob, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("pattern"),
		zend.MakeArgName("flags"),
	}),
	types.MakeZendFunctionEntryEx("fileatime", 0, ZifFileatime, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("filectime", 0, ZifFilectime, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("filegroup", 0, ZifFilegroup, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("fileinode", 0, ZifFileinode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("filemtime", 0, ZifFilemtime, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("fileowner", 0, ZifFileowner, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("fileperms", 0, ZifFileperms, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("filesize", 0, ZifFilesize, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("filetype", 0, ZifFiletype, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("file_exists", 0, ZifFileExists, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("is_writable", 0, ZifIsWritable, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("is_writeable", 0, ZifIsWritable, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("is_readable", 0, ZifIsReadable, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("is_executable", 0, ZifIsExecutable, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("is_file", 0, ZifIsFile, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("is_dir", 0, ZifIsDir, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("is_link", 0, ZifIsLink, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("stat", 0, PhpIfStat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("lstat", 0, PhpIfLstat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("chown", 0, ZifChown, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("user"),
	}),
	types.MakeZendFunctionEntryEx("chgrp", 0, ZifChgrp, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("group"),
	}),
	types.MakeZendFunctionEntryEx("lchown", 0, ZifLchown, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("user"),
	}),
	types.MakeZendFunctionEntryEx("lchgrp", 0, ZifLchgrp, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("group"),
	}),
	types.MakeZendFunctionEntryEx("chmod", 0, ZifChmod, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("touch", 0, ZifTouch, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("time"),
		zend.MakeArgName("atime"),
	}),
	types.MakeZendFunctionEntryEx("clearstatcache", 0, ZifClearstatcache, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("clear_realpath_cache"),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("disk_total_space", 0, ZifDiskTotalSpace, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("path"),
	}),
	types.MakeZendFunctionEntryEx("disk_free_space", 0, ZifDiskFreeSpace, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("path"),
	}),
	types.MakeZendFunctionEntryEx("diskfreespace", 0, ZifDiskFreeSpace, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("path"),
	}),
	types.MakeZendFunctionEntryEx("realpath_cache_size", 0, ZifRealpathCacheSize, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("realpath_cache_get", 0, ZifRealpathCacheGet, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("mail", 0, ZifMail, []zend.ArgInfo{zend.MakeReturnArgInfo(3),
		zend.MakeArgName("to"),
		zend.MakeArgName("subject"),
		zend.MakeArgName("message"),
		zend.MakeArgName("additional_headers"),
		zend.MakeArgName("additional_parameters"),
	}),
	types.MakeZendFunctionEntryEx("ezmlm_hash", zend.ZEND_ACC_DEPRECATED, ZifEzmlmHash, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("addr"),
	}),
	types.MakeZendFunctionEntryEx("openlog", 0, ZifOpenlog, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("ident"),
		zend.MakeArgName("option"),
		zend.MakeArgName("facility"),
	}),
	types.MakeZendFunctionEntryEx("syslog", 0, ZifSyslog, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("priority"),
		zend.MakeArgName("message"),
	}),
	types.MakeZendFunctionEntryEx("closelog", 0, ZifCloselog, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("lcg_value", 0, ZifLcgValue, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("metaphone", 0, ZifMetaphone, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("text"),
		zend.MakeArgName("phones"),
	}),
	types.MakeZendFunctionEntryEx("ob_start", 0, core.ZifObStart, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("user_function"),
		zend.MakeArgName("chunk_size"),
		zend.MakeArgName("flags"),
	}),
	types.MakeZendFunctionEntryEx("ob_flush", 0, core.ZifObFlush, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ob_clean", 0, core.ZifObClean, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ob_end_flush", 0, core.ZifObEndFlush, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ob_end_clean", 0, core.ZifObEndClean, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ob_get_flush", 0, core.ZifObGetFlush, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ob_get_clean", 0, core.ZifObGetClean, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ob_get_length", 0, core.ZifObGetLength, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ob_get_level", 0, core.ZifObGetLevel, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ob_get_status", 0, core.ZifObGetStatus, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("full_status"),
	}),
	types.MakeZendFunctionEntryEx("ob_get_contents", 0, core.ZifObGetContents, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ob_implicit_flush", 0, core.ZifObImplicitFlush, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("flag"),
	}),
	types.MakeZendFunctionEntryEx("ob_list_handlers", 0, core.ZifObListHandlers, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("ksort", 0, ZifKsort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("sort_flags"),
	}),
	types.MakeZendFunctionEntryEx("krsort", 0, ZifKrsort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("sort_flags"),
	}),
	types.MakeZendFunctionEntryEx("natsort", 0, ZifNatsort, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("natcasesort", 0, ZifNatcasesort, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("asort", 0, ZifAsort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("sort_flags"),
	}),
	types.MakeZendFunctionEntryEx("arsort", 0, ZifArsort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("sort_flags"),
	}),
	types.MakeZendFunctionEntryEx("sort", 0, ZifSort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("sort_flags"),
	}),
	types.MakeZendFunctionEntryEx("rsort", 0, ZifRsort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("sort_flags"),
	}),
	types.MakeZendFunctionEntryEx("usort", 0, ZifUsort, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("cmp_function"),
	}),
	types.MakeZendFunctionEntryEx("uasort", 0, ZifUasort, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("cmp_function"),
	}),
	types.MakeZendFunctionEntryEx("uksort", 0, ZifUksort, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("cmp_function"),
	}),
	types.MakeZendFunctionEntryEx("shuffle", 0, ZifShuffle, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("array_walk", 0, ZifArrayWalk, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgInfo("input", zend.ArgInfoByRef(1)),
		zend.MakeArgName("funcname"),
		zend.MakeArgName("userdata"),
	}),
	types.MakeZendFunctionEntryEx("array_walk_recursive", 0, ZifArrayWalkRecursive, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgInfo("input", zend.ArgInfoByRef(1)),
		zend.MakeArgName("funcname"),
		zend.MakeArgName("userdata"),
	}),
	types.MakeZendFunctionEntryEx("count", 0, ZifCount, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("var"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("end", 0, ZifEnd, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("prev", 0, ZifPrev, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("next", 0, ZifNext, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("reset", 0, ZifReset, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("current", 0, ZifCurrent, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("key", 0, ZifKey, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("min", 0, ZifMin, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("args", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("max", 0, ZifMax, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("args", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("in_array", 0, ZifInArray, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("needle"),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("strict"),
	}),
	types.MakeZendFunctionEntryEx("array_search", 0, ZifArraySearch, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("needle"),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("strict"),
	}),
	types.MakeZendFunctionEntryEx("extract", 0, ZifExtract, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF)),
		zend.MakeArgName("extract_type"),
		zend.MakeArgName("prefix"),
	}),
	types.MakeZendFunctionEntryEx("compact", 0, ZifCompact, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("var_names", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_fill", 0, ZifArrayFill, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("start_key"),
		zend.MakeArgName("num"),
		zend.MakeArgName("val"),
	}),
	types.MakeZendFunctionEntryEx("array_fill_keys", 0, ZifArrayFillKeys, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("keys"),
		zend.MakeArgName("val"),
	}),
	types.MakeZendFunctionEntryEx("range", 0, ZifRange, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("low"),
		zend.MakeArgName("high"),
		zend.MakeArgName("step"),
	}),
	types.MakeZendFunctionEntryEx("array_multisort", 0, ZifArrayMultisort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arr1", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF)),
		zend.MakeArgInfo("sort_order", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF)),
		zend.MakeArgInfo("sort_flags", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF)),
		zend.MakeArgInfo("arr2", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF), ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_push", 0, ZifArrayPush, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("stack", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("vars", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_pop", 0, ZifArrayPop, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("stack", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("array_shift", 0, ZifArrayShift, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgInfo("stack", zend.ArgInfoByRef(1)),
	}),
	types.MakeZendFunctionEntryEx("array_unshift", 0, ZifArrayUnshift, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("stack", zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("vars", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_splice", 0, ZifArraySplice, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(1)),
		zend.MakeArgName("offset"),
		zend.MakeArgName("length"),
		zend.MakeArgName("replacement"),
	}),
	types.MakeZendFunctionEntryEx("array_slice", 0, ZifArraySlice, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arg"),
		zend.MakeArgName("offset"),
		zend.MakeArgName("length"),
		zend.MakeArgName("preserve_keys"),
	}),
	types.MakeZendFunctionEntryEx("array_merge", 0, ZifArrayMerge, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_merge_recursive", 0, ZifArrayMergeRecursive, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_replace", 0, ZifArrayReplace, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("arr1"),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_replace_recursive", 0, ZifArrayReplaceRecursive, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("arr1"),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_keys", 0, ZifArrayKeys, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("arg"),
		zend.MakeArgName("search_value"),
		zend.MakeArgName("strict"),
	}),
	types.MakeZendFunctionEntryEx("array_key_first", 0, ZifArrayKeyFirst, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("array_key_last", 0, ZifArrayKeyLast, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("array_values", 0, ZifArrayValues, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("array_count_values", 0, ZifArrayCountValues, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("array_column", 0, ZifArrayColumn, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arg"),
		zend.MakeArgName("column_key"),
		zend.MakeArgName("index_key"),
	}),
	types.MakeZendFunctionEntryEx("array_reverse", 0, ZifArrayReverse, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("input"),
		zend.MakeArgName("preserve_keys"),
	}),
	types.MakeZendFunctionEntryEx("array_reduce", 0, ZifArrayReduce, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arg"),
		zend.MakeArgName("callback"),
		zend.MakeArgName("initial"),
	}),
	types.MakeZendFunctionEntryEx("array_pad", 0, ZifArrayPad, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
		zend.MakeArgName("pad_size"),
		zend.MakeArgName("pad_value"),
	}),
	types.MakeZendFunctionEntryEx("array_flip", 0, ZifArrayFlip, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("array_change_key_case", 0, ZifArrayChangeKeyCase, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("input"),
		zend.MakeArgName("case"),
	}),
	types.MakeZendFunctionEntryEx("array_rand", 0, ZifArrayRand, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("arg"),
		zend.MakeArgName("num_req"),
	}),
	types.MakeZendFunctionEntryEx("array_unique", 0, ZifArrayUnique, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("arg"),
		zend.MakeArgName("flags"),
	}),
	types.MakeZendFunctionEntryEx("array_intersect", 0, ZifArrayIntersect, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arr1"),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_intersect_key", 0, ZifArrayIntersectKey, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arr1"),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_intersect_ukey", 0, ZifArrayIntersectUkey, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_key_compare_func"),
	}),
	types.MakeZendFunctionEntryEx("array_uintersect", 0, ZifArrayUintersect, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_data_compare_func"),
	}),
	types.MakeZendFunctionEntryEx("array_intersect_assoc", 0, ZifArrayIntersectAssoc, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arr1"),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_uintersect_assoc", 0, ZifArrayUintersectAssoc, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_data_compare_func"),
	}),
	types.MakeZendFunctionEntryEx("array_intersect_uassoc", 0, ZifArrayIntersectUassoc, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_key_compare_func"),
	}),
	types.MakeZendFunctionEntryEx("array_uintersect_uassoc", 0, ZifArrayUintersectUassoc, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_data_compare_func"),
		zend.MakeArgName("callback_key_compare_func"),
	}),
	types.MakeZendFunctionEntryEx("array_diff", 0, ZifArrayDiff, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arr1"),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_diff_key", 0, ZifArrayDiffKey, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arr1"),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_diff_ukey", 0, ZifArrayDiffUkey, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_key_comp_func"),
	}),
	types.MakeZendFunctionEntryEx("array_udiff", 0, ZifArrayUdiff, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_data_comp_func"),
	}),
	types.MakeZendFunctionEntryEx("array_diff_assoc", 0, ZifArrayDiffAssoc, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arr1"),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_udiff_assoc", 0, ZifArrayUdiffAssoc, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_key_comp_func"),
	}),
	types.MakeZendFunctionEntryEx("array_diff_uassoc", 0, ZifArrayDiffUassoc, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_data_comp_func"),
	}),
	types.MakeZendFunctionEntryEx("array_udiff_uassoc", 0, ZifArrayUdiffUassoc, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arr1"),
		zend.MakeArgName("arr2"),
		zend.MakeArgName("callback_data_comp_func"),
		zend.MakeArgName("callback_key_comp_func"),
	}),
	types.MakeZendFunctionEntryEx("array_sum", 0, ZifArraySum, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("array_product", 0, ZifArrayProduct, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("array_filter", 0, ZifArrayFilter, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("arg"),
		zend.MakeArgName("callback"),
		zend.MakeArgName("use_keys"),
	}),
	types.MakeZendFunctionEntryEx("array_map", 0, ZifArrayMap, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("callback"),
		zend.MakeArgInfo("arrays", ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("array_chunk", 0, ZifArrayChunk, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("arg"),
		zend.MakeArgName("size"),
		zend.MakeArgName("preserve_keys"),
	}),
	types.MakeZendFunctionEntryEx("array_combine", 0, ZifArrayCombine, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("keys"),
		zend.MakeArgName("values"),
	}),
	types.MakeZendFunctionEntryEx("array_key_exists", 0, ZifArrayKeyExists, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("key"),
		zend.MakeArgName("search"),
	}),
	types.MakeZendFunctionEntryEx("pos", 0, ZifCurrent, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("sizeof", 0, ZifCount, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("var"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("key_exists", 0, ZifArrayKeyExists, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("key"),
		zend.MakeArgName("search"),
	}),
	types.MakeZendFunctionEntryEx("assert", 0, ZifAssert, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("assertion"),
		zend.MakeArgName("description"),
	}),
	types.MakeZendFunctionEntryEx("assert_options", 0, ZifAssertOptions, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("what"),
		zend.MakeArgName("value"),
	}),
	types.MakeZendFunctionEntryEx("version_compare", 0, ZifVersionCompare, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("ver1"),
		zend.MakeArgName("ver2"),
		zend.MakeArgName("oper"),
	}),
	types.MakeZendFunctionEntryEx("ftok", 0, ZifFtok, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("pathname"),
		zend.MakeArgName("proj"),
	}),
	types.MakeZendFunctionEntryEx("str_rot13", 0, ZifStrRot13, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	types.MakeZendFunctionEntryEx("stream_get_filters", 0, ZifStreamGetFilters, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("stream_filter_register", 0, ZifStreamFilterRegister, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filtername"),
		zend.MakeArgName("classname"),
	}),
	types.MakeZendFunctionEntryEx("stream_bucket_make_writeable", 0, ZifStreamBucketMakeWriteable, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("brigade"),
	}),
	types.MakeZendFunctionEntryEx("stream_bucket_prepend", 0, ZifStreamBucketPrepend, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("brigade"),
		zend.MakeArgName("bucket"),
	}),
	types.MakeZendFunctionEntryEx("stream_bucket_append", 0, ZifStreamBucketAppend, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("brigade"),
		zend.MakeArgName("bucket"),
	}),
	types.MakeZendFunctionEntryEx("stream_bucket_new", 0, ZifStreamBucketNew, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("stream"),
		zend.MakeArgName("buffer"),
	}),
	types.MakeZendFunctionEntryEx("output_add_rewrite_var", 0, core.ZifOutputAddRewriteVar, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("name"),
		zend.MakeArgName("value"),
	}),
	types.MakeZendFunctionEntryEx("output_reset_rewrite_vars", 0, core.ZifOutputResetRewriteVars, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	types.MakeZendFunctionEntryEx("sys_get_temp_dir", 0, ZifSysGetTempDir, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
}
var StandardDeps []zend.ZendModuleDep = []zend.ZendModuleDep{
	zend.MakeZendModuleDep("session", nil, nil, zend.MODULE_DEP_OPTIONAL),
	zend.MakeZendModuleDep(nil, nil, nil, 0),
}
var BasicFunctionsModule zend.ZendModuleEntry = zend.MakeZendModuleEntry(b.SizeOf("zend_module_entry"), zend.ZEND_MODULE_API_NO, 0, zend.USING_ZTS, nil, StandardDeps, "standard", BasicFunctions, ZmStartupBasic, ZmShutdownBasic, ZmActivateBasic, ZmDeactivateBasic, ZmInfoBasic, PHP_STANDARD_VERSION, 0, nil, nil, nil, nil, 0, 0, nil, 0, "API"+"ZEND_MODULE_API_NO"+zend.ZEND_BUILD_TS)
