package standard

import (
	b "sik/builtin"
	"sik/core"
	"sik/core/streams"
	"sik/zend"
	"sik/zend/types"
)

const BasicFunctionsModulePtr = &BasicFunctionsModule

/* system functions */

var ZifSetTimeLimit func(executeData *zend.ZendExecuteData, return_value *types.Zval)
var ZifHeaderRegisterCallback func(executeData *zend.ZendExecuteData, return_value *types.Zval)

/* From the INI parser */

/* Left for BC (not binary safe!) */

const MT_N = 624

var BasicGlobals PhpBasicGlobals

// Source: <ext/standard/basic_functions.c>

var IncompleteClassEntry *types.ClassEntry = nil

var BasicFunctions []types.ZendFunctionEntry = []types.ZendFunctionEntry{
	DefZifConstant,
	DefZifBin2hex,
	DefZifHex2bin,
	DefZifSleep,
	DefZifUsleep,
	DefZifTimeNanosleep,
	DefZifTimeSleepUntil,
	DefZifStrptime,
	DefZifFlush,
	DefZifWordwrap,
	DefZifHtmlspecialchars,
	DefZifHtmlentities,
	DefZifHtmlEntityDecode,
	DefZifHtmlspecialcharsDecode,
	DefZifGetHtmlTranslationTable,
	DefZifSha1,
	DefZifSha1File,
	types.MakeZendFunctionEntryEx("md5", 0, PhpIfMd5, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("raw_output"),
	}),
	types.MakeZendFunctionEntryEx("md5_file", 0, PhpIfMd5File, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("filename"),
		zend.MakeArgName("raw_output"),
	}),
	types.MakeZendFunctionEntryEx("crc32", 0, PhpIfCrc32, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("str"),
	}),
	DefZifIptcparse,
	DefZifIptcembed,
	DefZifGetimagesize,
	DefZifGetimagesizefromstring,
	DefZifImageTypeToMimeType,
	DefZifImageTypeToExtension,
	DefZifPhpversion,
	DefZifPhpcredits,
	DefZifPhpSapiName,
	DefZifPhpUname,
	DefZifPhpIniScannedFiles,
	DefZifPhpIniLoadedFile,
	DefZifStrnatcmp,
	DefZifStrnatcasecmp,
	DefZifSubstrCount,
	DefZifStrspn,
	DefZifStrcspn,
	DefZifStrtok,
	DefZifStrtoupper,
	DefZifStrtolower,
	DefZifStrpos,
	DefZifStripos,
	DefZifStrrpos,
	DefZifStrripos,
	DefZifStrrev,
	DefZifHebrev,
	DefZifHebrevc,
	DefZifNl2br,
	DefZifBasename,
	DefZifDirname,
	DefZifPathinfo,
	DefZifStripslashes,
	DefZifStripcslashes,
	DefZifStrstr,
	DefZifStristr,
	DefZifStrrchr,
	DefZifStrShuffle,
	DefZifStrWordCount,
	DefZifStrSplit,
	DefZifStrpbrk,
	DefZifSubstrCompare,
	DefZifUtf8Encode,
	DefZifUtf8Decode,
	DefZifStrcoll,
	DefZifMoneyFormat,
	DefZifSubstr,
	DefZifSubstrReplace,
	DefZifQuotemeta,
	DefZifUcfirst,
	DefZifLcfirst,
	DefZifUcwords,
	DefZifStrtr,
	DefZifAddslashes,
	DefZifAddcslashes,
	DefZifRtrim,
	DefZifStrReplace,
	DefZifStrIreplace,
	DefZifStrRepeat,
	DefZifCountChars,
	DefZifChunkSplit,
	DefZifTrim,
	DefZifLtrim,
	DefZifStripTags,
	DefZifSimilarText,
	DefZifExplode,
	DefZifImplode,
	types.MakeZendFunctionEntryEx("join", 0, ZifImplode, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("glue"),
		zend.MakeArgName("pieces"),
	}),
	DefZifSetlocale,
	DefZifLocaleconv,
	DefZifSoundex,
	DefZifLevenshtein,
	DefZifChr,
	DefZifOrd,
	DefZifParseStr,
	DefZifStrGetcsv,
	DefZifStrPad,
	types.MakeZendFunctionEntryEx("chop", 0, ZifRtrim, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("str"),
		zend.MakeArgName("character_mask"),
	}),
	types.MakeZendFunctionEntryEx("strchr", 0, ZifStrstr, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("haystack"),
		zend.MakeArgName("needle"),
		zend.MakeArgName("part"),
	}),
	types.MakeZendFunctionEntryEx("sprintf", 0, ZifUserSprintf, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("format"),
		zend.MakeArgVariadic("args"),
	}),
	types.MakeZendFunctionEntryEx("printf", 0, ZifUserPrintf, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("format"),
		zend.MakeArgVariadic("args"),
	}),
	DefZifVprintf,
	DefZifVsprintf,
	DefZifFprintf,
	DefZifVfprintf,
	types.MakeZendFunctionEntryEx("sscanf", 0, ZifSscanf, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("str"),
		zend.MakeArgName("format"),
		zend.MakeArgInfo("vars", zend.ArgInfoByRef(1), zend.ArgInfoVariadic()),
	}),
	types.MakeZendFunctionEntryEx("fscanf", 0, ZifFscanf, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("format"),
		zend.MakeArgInfo("vars", zend.ArgInfoByRef(1), zend.ArgInfoVariadic()),
	}),
	DefZifParseUrl,
	DefZifUrlencode,
	DefZifUrldecode,
	DefZifRawurlencode,
	DefZifRawurldecode,
	DefZifHttpBuildQuery,
	DefZifReadlink,
	DefZifLinkinfo,
	DefZifSymlink,
	DefZifLink,
	DefZifUnlink,
	DefZifExec,
	DefZifSystem,
	DefZifEscapeshellcmd,
	DefZifEscapeshellarg,
	DefZifPassthru,
	DefZifShellExec,
	DefZifProcOpen,
	DefZifProcClose,
	DefZifProcTerminate,
	DefZifProcGetStatus,
	DefZifProcNice,
	DefZifRand,
	types.MakeZendFunctionEntryEx("srand", 0, ZifMtSrand, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("seed"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("getrandmax", 0, ZifMtGetrandmax, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	DefZifMtRand,
	DefZifMtSrand,
	DefZifMtGetrandmax,
	DefZifRandomBytes,
	DefZifRandomInt,
	DefZifGetservbyname,
	DefZifGetservbyport,
	DefZifGetprotobyname,
	DefZifGetprotobynumber,
	DefZifGetmyuid,
	DefZifGetmygid,
	DefZifGetmypid,
	DefZifGetmyinode,
	DefZifGetlastmod,
	DefZifBase64Decode,
	DefZifBase64Encode,
	DefZifPasswordHash,
	DefZifPasswordGetInfo,
	DefZifPasswordNeedsRehash,
	DefZifPasswordVerify,
	DefZifPasswordAlgos,
	DefZifConvertUuencode,
	DefZifConvertUudecode,
	DefZifAbs,
	DefZifCeil,
	DefZifFloor,
	DefZifRound,
	DefZifSin,
	DefZifCos,
	DefZifTan,
	DefZifAsin,
	DefZifAcos,
	DefZifAtan,
	DefZifAtanh,
	DefZifAtan2,
	DefZifSinh,
	DefZifCosh,
	DefZifTanh,
	DefZifAsinh,
	DefZifAcosh,
	DefZifExpm1,
	DefZifLog1p,
	DefZifPi,
	DefZifIsFinite,
	DefZifIsNan,
	DefZifIsInfinite,
	DefZifPow,
	DefZifExp,
	DefZifLog,
	DefZifLog10,
	DefZifSqrt,
	DefZifHypot,
	DefZifDeg2rad,
	DefZifRad2deg,
	DefZifBindec,
	DefZifHexdec,
	DefZifOctdec,
	DefZifDecbin,
	DefZifDecoct,
	DefZifDechex,
	DefZifBaseConvert,
	DefZifNumberFormat,
	DefZifFmod,
	DefZifIntdiv,
	DefZifInetNtop,
	types.MakeZendFunctionEntryEx("inet_pton", 0, PhpInetPton, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("ip_address"),
	}),
	DefZifIp2long,
	DefZifLong2ip,
	DefZifGetenv,
	DefZifPutenv,
	DefZifGetopt,
	DefZifSysGetloadavg,
	DefZifMicrotime,
	DefZifGettimeofday,
	DefZifGetrusage,
	DefZifHrtime,
	DefZifUniqid,
	DefZifQuotedPrintableDecode,
	DefZifQuotedPrintableEncode,
	DefZifConvertCyrString,
	DefZifGetCurrentUser,
	types.MakeZendFunctionEntryEx("set_time_limit", 0, ZifSetTimeLimit, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("seconds"),
	}),
	types.MakeZendFunctionEntryEx("header_register_callback", 0, ZifHeaderRegisterCallback, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("callback"),
	}),
	DefZifGetCfgVar,
	DefZifGetMagicQuotesGpc,
	DefZifGetMagicQuotesRuntime,
	DefZifErrorLog,
	DefZifErrorGetLast,
	DefZifErrorClearLast,
	DefZifCallUserFunc,
	DefZifCallUserFuncArray,
	DefZifForwardStaticCall,
	DefZifForwardStaticCallArray,
	DefZifSerialize,
	DefZifUnserialize,
	DefZifVarDump,
	DefZifVarExport,
	DefZifDebugZvalDump,
	DefZifPrintR,
	DefZifMemoryGetUsage,
	DefZifMemoryGetPeakUsage,
	DefZifRegisterShutdownFunction,
	DefZifRegisterTickFunction,
	DefZifUnregisterTickFunction,
	DefZifHighlightFile,
	types.MakeZendFunctionEntryEx("show_source", 0, ZifHighlightFile, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("file_name"),
		zend.MakeArgName("return"),
	}),
	DefZifHighlightString,
	DefZifPhpStripWhitespace,
	DefZifIniGet,
	DefZifIniGetAll,
	DefZifIniSet,
	types.MakeZendFunctionEntryEx("ini_alter", 0, ZifIniSet, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("varname"),
		zend.MakeArgName("newvalue"),
	}),
	DefZifIniRestore,
	DefZifGetIncludePath,
	DefZifSetIncludePath,
	DefZifRestoreIncludePath,
	DefZifSetcookie,
	DefZifSetrawcookie,
	DefZifHeader,
	DefZifHeaderRemove,
	DefZifHeadersSent,
	DefZifHeadersList,
	DefZifHttpResponseCode,
	DefZifConnectionAborted,
	DefZifConnectionStatus,
	DefZifIgnoreUserAbort,
	DefZifParseIniFile,
	DefZifParseIniString,
	DefZifIsUploadedFile,
	DefZifMoveUploadedFile,
	DefZifGethostbyaddr,
	DefZifGethostbyname,
	DefZifGethostbynamel,
	DefZifGethostname,
	DefZifNetGetInterfaces,
	DefZifDnsCheckRecord,
	types.MakeZendFunctionEntryEx("checkdnsrr", 0, ZifDnsCheckRecord, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("host"),
		zend.MakeArgName("type"),
	}),
	DefZifDnsGetMx,
	types.MakeZendFunctionEntryEx("getmxrr", 0, ZifDnsGetMx, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("hostname"),
		zend.MakeArgByRef("mxhosts"),
		zend.MakeArgByRef("weight"),
	}),
	types.MakeZendFunctionEntryEx("dns_get_record", 0, ZifDnsGetRecord, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("hostname"),
		zend.MakeArgName("type"),
		zend.MakeArgInfo("authns", zend.ArgInfoType(types.ZEND_TYPE_ENCODE(types.IS_ARRAY, 1)), zend.ArgInfoByRef(1)),
		zend.MakeArgInfo("addtl", zend.ArgInfoType(types.ZEND_TYPE_ENCODE(types.IS_ARRAY, 1)), zend.ArgInfoByRef(1)),
		zend.MakeArgName("raw"),
	}),
	DefZifIntval,
	DefZifFloatval,
	types.MakeZendFunctionEntryEx("doubleval", 0, ZifFloatval, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	DefZifStrval,
	DefZifBoolval,
	DefZifGettype,
	DefZifSettype,
	DefZifIsNull,
	DefZifIsResource,
	DefZifIsBool,
	DefZifIsInt,
	DefZifIsFloat,
	types.MakeZendFunctionEntryEx("is_integer", 0, ZifIsInt, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_long", 0, ZifIsInt, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_double", 0, ZifIsFloat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	types.MakeZendFunctionEntryEx("is_real", zend.ZEND_ACC_DEPRECATED, ZifIsFloat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("var"),
	}),
	DefZifIsNumeric,
	DefZifIsString,
	DefZifIsArray,
	DefZifIsObject,
	DefZifIsScalar,
	DefZifIsCallable,
	DefZifIsIterable,
	DefZifIsCountable,
	DefZifPclose,
	DefZifPopen,
	DefZifReadfile,
	DefZifRewind,
	DefZifRmdir,
	DefZifUmask,
	DefZifFclose,
	DefZifFeof,
	DefZifFgetc,
	DefZifFgets,
	DefZifFgetss,
	DefZifFread,
	types.MakeZendFunctionEntryEx("fopen", 0, PhpIfFopen, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("filename"),
		zend.MakeArgName("mode"),
		zend.MakeArgName("use_include_path"),
		zend.MakeArgName("context"),
	}),
	DefZifFpassthru,
	types.MakeZendFunctionEntryEx("ftruncate", 0, PhpIfFtruncate, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("size"),
	}),
	types.MakeZendFunctionEntryEx("fstat", 0, PhpIfFstat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	DefZifFseek,
	DefZifFtell,
	DefZifFflush,
	DefZifFwrite,
	types.MakeZendFunctionEntryEx("fputs", 0, ZifFwrite, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("fp"),
		zend.MakeArgName("str"),
		zend.MakeArgName("length"),
	}),
	DefZifMkdir,
	DefZifRename,
	DefZifCopy,
	DefZifTempnam,
	types.MakeZendFunctionEntryEx("tmpfile", 0, PhpIfTmpfile, []zend.ArgInfo{zend.MakeReturnArgInfo(-1)}),
	DefZifFile,
	DefZifFileGetContents,
	DefZifFilePutContents,
	DefZifStreamSelect,
	DefZifStreamContextCreate,
	DefZifStreamContextSetParams,
	DefZifStreamContextGetParams,
	DefZifStreamContextSetOption,
	DefZifStreamContextGetOptions,
	DefZifStreamContextGetDefault,
	DefZifStreamContextSetDefault,
	DefZifStreamFilterPrepend,
	DefZifStreamFilterAppend,
	DefZifStreamFilterRemove,
	DefZifStreamSocketClient,
	DefZifStreamSocketServer,
	DefZifStreamSocketAccept,
	DefZifStreamSocketGetName,
	DefZifStreamSocketRecvfrom,
	DefZifStreamSocketSendto,
	DefZifStreamSocketEnableCrypto,
	DefZifStreamSocketShutdown,
	DefZifStreamSocketPair,
	DefZifStreamCopyToStream,
	DefZifStreamGetContents,
	DefZifStreamSupportsLock,
	DefZifStreamIsatty,
	DefZifFgetcsv,
	DefZifFputcsv,
	DefZifFlock,
	DefZifGetMetaTags,
	DefZifStreamSetReadBuffer,
	DefZifStreamSetWriteBuffer,
	types.MakeZendFunctionEntryEx("set_file_buffer", 0, ZifStreamSetWriteBuffer, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
		zend.MakeArgName("buffer"),
	}),
	DefZifStreamSetChunkSize,
	DefZifStreamSetBlocking,
	types.MakeZendFunctionEntryEx("socket_set_blocking", 0, ZifStreamSetBlocking, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("socket"),
		zend.MakeArgName("mode"),
	}),
	DefZifStreamGetMetaData,
	DefZifStreamGetLine,
	streams.DefZifStreamWrapperRegister,
	types.MakeZendFunctionEntryEx("stream_register_wrapper", 0, ZifStreamWrapperRegister, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("protocol"),
		zend.MakeArgName("classname"),
		zend.MakeArgName("flags"),
	}),
	streams.DefZifStreamWrapperUnregister,
	streams.DefZifStreamWrapperRestore,
	DefZifStreamGetWrappers,
	DefZifStreamGetTransports,
	DefZifStreamResolveIncludePath,
	DefZifStreamIsLocal,
	DefZifGetHeaders,
	DefZifStreamSetTimeout,
	types.MakeZendFunctionEntryEx("socket_set_timeout", 0, ZifStreamSetTimeout, []zend.ArgInfo{zend.MakeReturnArgInfo(2),
		zend.MakeArgName("stream"),
		zend.MakeArgName("seconds"),
		zend.MakeArgName("microseconds"),
	}),
	types.MakeZendFunctionEntryEx("socket_get_status", 0, ZifStreamGetMetaData, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("fp"),
	}),
	DefZifRealpath,
	DefZifFnmatch,
	DefZifFsockopen,
	DefZifPfsockopen,
	DefZifPack,
	DefZifUnpack,
	DefZifGetBrowser,
	DefZifCrypt,
	DefZifOpendir,
	DefZifClosedir,
	DefZifChdir,
	DefZifChroot,
	DefZifGetcwd,
	DefZifRewinddir,
	types.MakeZendFunctionEntryEx("readdir", 0, PhpIfReaddir, []zend.ArgInfo{zend.MakeReturnArgInfo(0),
		zend.MakeArgName("dir_handle"),
	}),
	types.MakeZendFunctionEntryEx("dir", 0, ZifGetdir, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("directory"),
		zend.MakeArgName("context"),
	}),
	DefZifScandir,
	DefZifGlob,
	DefZifFileatime,
	DefZifFilectime,
	DefZifFilegroup,
	DefZifFileinode,
	DefZifFilemtime,
	DefZifFileowner,
	DefZifFileperms,
	DefZifFilesize,
	DefZifFiletype,
	DefZifFileExists,
	DefZifIsWritable,
	types.MakeZendFunctionEntryEx("is_writeable", 0, ZifIsWritable, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	DefZifIsReadable,
	DefZifIsExecutable,
	DefZifIsFile,
	DefZifIsDir,
	DefZifIsLink,
	types.MakeZendFunctionEntryEx("stat", 0, PhpIfStat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	types.MakeZendFunctionEntryEx("lstat", 0, PhpIfLstat, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("filename"),
	}),
	DefZifChown,
	DefZifChgrp,
	DefZifLchown,
	DefZifLchgrp,
	DefZifChmod,
	DefZifTouch,
	DefZifClearstatcache,
	DefZifDiskTotalSpace,
	DefZifDiskFreeSpace,
	types.MakeZendFunctionEntryEx("diskfreespace", 0, ZifDiskFreeSpace, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("path"),
	}),
	DefZifRealpathCacheSize,
	DefZifRealpathCacheGet,
	DefZifMail,
	DefZifEzmlmHash,
	DefZifOpenlog,
	DefZifSyslog,
	DefZifCloselog,
	DefZifLcgValue,
	DefZifMetaphone,
	core.DefZifObStart,
	core.DefZifObFlush,
	core.DefZifObClean,
	core.DefZifObEndFlush,
	core.DefZifObEndClean,
	core.DefZifObGetFlush,
	core.DefZifObGetClean,
	core.DefZifObGetLength,
	core.DefZifObGetLevel,
	core.DefZifObGetStatus,
	core.DefZifObGetContents,
	core.DefZifObImplicitFlush,
	core.DefZifObListHandlers,
	types.MakeZendFunctionEntryEx("ksort", 0, ZifKsort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgByRef("arg"),
		zend.MakeArgName("sort_flags"),
	}),
	types.MakeZendFunctionEntryEx("krsort", 0, ZifKrsort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgByRef("arg"),
		zend.MakeArgName("sort_flags"),
	}),
	DefZifNatsort,
	DefZifNatcasesort,
	DefZifAsort,
	DefZifArsort,
	DefZifSort,
	DefZifRsort,
	DefZifUsort,
	DefZifUasort,
	DefZifUksort,
	DefZifShuffle,
	DefZifArrayWalk,
	DefZifArrayWalkRecursive,
	types.MakeZendFunctionEntryEx("count", 0, ZifCount, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("var"),
		zend.MakeArgName("mode"),
	}),
	DefZifEnd,
	DefZifPrev,
	DefZifNext,
	DefZifReset,
	DefZifCurrent,
	DefZifKey,
	DefZifMin,
	DefZifMax,
	DefZifInArray,
	DefZifArraySearch,
	types.MakeZendFunctionEntryEx("extract", 0, ZifExtract, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arg", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF)),
		zend.MakeArgName("extract_type"),
		zend.MakeArgName("prefix"),
	}),
	DefZifCompact,
	DefZifArrayFill,
	DefZifArrayFillKeys,
	DefZifRange,
	types.MakeZendFunctionEntryEx("array_multisort", 0, ZifArrayMultisort, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgInfo("arr1", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF)),
		zend.MakeArgInfo("sort_order", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF)),
		zend.MakeArgInfo("sort_flags", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF)),
		zend.MakeArgInfo("arr2", zend.ArgInfoByRef(zend.ZEND_SEND_PREFER_REF), zend.ArgInfoVariadic()),
	}),
	DefZifArrayPush,
	DefZifArrayPop,
	DefZifArrayShift,
	DefZifArrayUnshift,
	DefZifArraySplice,
	DefZifArraySlice,
	DefZifArrayMerge,
	DefZifArrayMergeRecursive,
	DefZifArrayReplace,
	DefZifArrayReplaceRecursive,
	DefZifArrayKeys,
	DefZifArrayKeyFirst,
	DefZifArrayKeyLast,
	DefZifArrayValues,
	DefZifArrayCountValues,
	DefZifArrayColumn,
	DefZifArrayReverse,
	DefZifArrayReduce,
	DefZifArrayPad,
	DefZifArrayFlip,
	DefZifArrayChangeKeyCase,
	DefZifArrayRand,
	DefZifArrayUnique,
	DefZifArrayIntersect,
	DefZifArrayIntersectKey,
	DefZifArrayIntersectUkey,
	DefZifArrayUintersect,
	DefZifArrayIntersectAssoc,
	DefZifArrayUintersectAssoc,
	DefZifArrayIntersectUassoc,
	DefZifArrayUintersectUassoc,
	DefZifArrayDiff,
	DefZifArrayDiffKey,
	DefZifArrayDiffUkey,
	DefZifArrayUdiff,
	DefZifArrayDiffAssoc,
	DefZifArrayUdiffAssoc,
	DefZifArrayDiffUassoc,
	DefZifArrayUdiffUassoc,
	DefZifArraySum,
	DefZifArrayProduct,
	DefZifArrayFilter,
	DefZifArrayMap,
	DefZifArrayChunk,
	DefZifArrayCombine,
	DefZifArrayKeyExists,
	types.MakeZendFunctionEntryEx("pos", 0, ZifCurrent, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("arg"),
	}),
	types.MakeZendFunctionEntryEx("sizeof", 0, ZifCount, []zend.ArgInfo{zend.MakeReturnArgInfo(1),
		zend.MakeArgName("var"),
		zend.MakeArgName("mode"),
	}),
	types.MakeZendFunctionEntryEx("key_exists", 0, ZifArrayKeyExists, []zend.ArgInfo{zend.MakeReturnArgInfo(-1),
		zend.MakeArgName("key"),
		zend.MakeArgName("search"),
	}),
	DefZifAssert,
	DefZifAssertOptions,
	DefZifVersionCompare,
	DefZifFtok,
	DefZifStrRot13,
	DefZifStreamGetFilters,
	DefZifStreamFilterRegister,
	DefZifStreamBucketMakeWriteable,
	DefZifStreamBucketPrepend,
	DefZifStreamBucketAppend,
	DefZifStreamBucketNew,
	core.DefZifOutputAddRewriteVar,
	core.DefZifOutputResetRewriteVars,
	DefZifSysGetTempDir,
}
var StandardDeps []zend.ZendModuleDep = []zend.ZendModuleDep{
	zend.MakeZendModuleDep("session", nil, nil, zend.MODULE_DEP_OPTIONAL),
	zend.MakeZendModuleDep(nil, nil, nil, 0),
}
var BasicFunctionsModule zend.ZendModuleEntry = zend.MakeZendModuleEntry(b.SizeOf("zend_module_entry"), zend.ZEND_MODULE_API_NO, 0, zend.USING_ZTS, nil, StandardDeps, "standard", BasicFunctions, ZmStartupBasic, ZmShutdownBasic, ZmActivateBasic, ZmDeactivateBasic, ZmInfoBasic, PHP_STANDARD_VERSION, 0, nil, nil, nil, nil, 0, 0, nil, 0, "API"+"ZEND_MODULE_API_NO"+zend.ZEND_BUILD_TS)
