// <<generate>>

package standard

// Source: <ext/standard/credits_sapi.h>

/*
                      DO NOT EDIT THIS FILE!

 it has been automatically created by scripts/dev/credits from
 the information found in the various ext/.../CREDITS and
 sapi/.../CREDITS files

 if you want to change an entry you have to edit the appropriate
 CREDITS file instead

*/

func init() {
	PhpInfoPrintTableRow(2, "Apache 2.0 Handler", "Ian Holsman, Justin Erenkrantz (based on Apache 2.0 Filter code)")
	PhpInfoPrintTableRow(2, "CGI / FastCGI", "Rasmus Lerdorf, Stig Bakken, Shane Caraveo, Dmitry Stogov")
	PhpInfoPrintTableRow(2, "CLI", "Edin Kadribasic, Marcus Boerger, Johannes Schlueter, Moriyoshi Koizumi, Xinchen Hui")
	PhpInfoPrintTableRow(2, "Embed", "Edin Kadribasic")
	PhpInfoPrintTableRow(2, "FastCGI Process Manager", "Andrei Nigmatulin, dreamcat4, Antony Dovgal, Jerome Loyet")
	PhpInfoPrintTableRow(2, "litespeed", "George Wang")
	PhpInfoPrintTableRow(2, "phpdbg", "Felipe Pena, Joe Watkins, Bob Weinand")
}
