// <<generate>>

package standard

// Source: <ext/standard/credits_ext.h>

/*
                      DO NOT EDIT THIS FILE!

 it has been automatically created by scripts/dev/credits from
 the information found in the various ext/.../CREDITS and
 sapi/.../CREDITS files

 if you want to change an entry you have to edit the appropriate
 CREDITS file instead

*/

func init() {
	PhpInfoPrintTableRow(2, "BC Math", "Andi Gutmans")
	PhpInfoPrintTableRow(2, "Bzip2", "Sterling Hughes")
	PhpInfoPrintTableRow(2, "Calendar", "Shane Caraveo, Colin Viebrock, Hartmut Holzgraefe, Wez Furlong")
	PhpInfoPrintTableRow(2, "COM and .Net", "Wez Furlong")
	PhpInfoPrintTableRow(2, "ctype", "Hartmut Holzgraefe")
	PhpInfoPrintTableRow(2, "cURL", "Sterling Hughes")
	PhpInfoPrintTableRow(2, "Date/Time Support", "Derick Rethans")
	PhpInfoPrintTableRow(2, "DB-LIB (MS SQL, Sybase)", "Wez Furlong, Frank M. Kromann, Adam Baratz")
	PhpInfoPrintTableRow(2, "DBA", "Sascha Schumann, Marcus Boerger")
	PhpInfoPrintTableRow(2, "DOM", "Christian Stocker, Rob Richards, Marcus Boerger")
	PhpInfoPrintTableRow(2, "enchant", "Pierre-Alain Joye, Ilia Alshanetsky")
	PhpInfoPrintTableRow(2, "EXIF", "Rasmus Lerdorf, Marcus Boerger")
	PhpInfoPrintTableRow(2, "FFI", "Dmitry Stogov")
	PhpInfoPrintTableRow(2, "fileinfo", "Ilia Alshanetsky, Pierre Alain Joye, Scott MacVicar, Derick Rethans, Anatol Belski")
	PhpInfoPrintTableRow(2, "Firebird driver for PDO", "Ard Biesheuvel")
	PhpInfoPrintTableRow(2, "FTP", "Stefan Esser, Andrew Skalski")
	PhpInfoPrintTableRow(2, "GD imaging", "Rasmus Lerdorf, Stig Bakken, Jim Winstead, Jouni Ahto, Ilia Alshanetsky, Pierre-Alain Joye, Marcus Boerger")
	PhpInfoPrintTableRow(2, "GetText", "Alex Plotnick")
	PhpInfoPrintTableRow(2, "GNU GMP support", "Stanislav Malyshev")
	PhpInfoPrintTableRow(2, "Iconv", "Rui Hirokawa, Stig Bakken, Moriyoshi Koizumi")
	PhpInfoPrintTableRow(2, "IMAP", "Rex Logan, Mark Musone, Brian Wang, Kaj-Michael Lang, Antoni Pamies Olive, Rasmus Lerdorf, Andrew Skalski, Chuck Hagenbuch, Daniel R Kalowsky")
	PhpInfoPrintTableRow(2, "Input Filter", "Rasmus Lerdorf, Derick Rethans, Pierre-Alain Joye, Ilia Alshanetsky")
	PhpInfoPrintTableRow(2, "Internationalization", "Ed Batutis, Vladimir Iordanov, Dmitry Lakhtyuk, Stanislav Malyshev, Vadim Savchuk, Kirti Velankar")
	PhpInfoPrintTableRow(2, "JSON", "Jakub Zelenka, Omar Kilani, Scott MacVicar")
	PhpInfoPrintTableRow(2, "LDAP", "Amitay Isaacs, Eric Warnke, Rasmus Lerdorf, Gerrit Thomson, Stig Venaas")
	PhpInfoPrintTableRow(2, "LIBXML", "Christian Stocker, Rob Richards, Marcus Boerger, Wez Furlong, Shane Caraveo")
	PhpInfoPrintTableRow(2, "Multibyte String Functions", "Tsukada Takuya, Rui Hirokawa")
	PhpInfoPrintTableRow(2, "MySQL driver for PDO", "George Schlossnagle, Wez Furlong, Ilia Alshanetsky, Johannes Schlueter")
	PhpInfoPrintTableRow(2, "MySQLi", "Zak Greant, Georg Richter, Andrey Hristov, Ulf Wendel")
	PhpInfoPrintTableRow(2, "MySQLnd", "Andrey Hristov, Ulf Wendel, Georg Richter, Johannes Schlüter")
	PhpInfoPrintTableRow(2, "OCI8", "Stig Bakken, Thies C. Arntzen, Andy Sautins, David Benson, Maxim Maletsky, Harald Radi, Antony Dovgal, Andi Gutmans, Wez Furlong, Christopher Jones, Oracle Corporation")
	PhpInfoPrintTableRow(2, "ODBC driver for PDO", "Wez Furlong")
	PhpInfoPrintTableRow(2, "ODBC", "Stig Bakken, Andreas Karajannis, Frank M. Kromann, Daniel R. Kalowsky")
	PhpInfoPrintTableRow(2, "Opcache", "Andi Gutmans, Zeev Suraski, Stanislav Malyshev, Dmitry Stogov, Xinchen Hui")
	PhpInfoPrintTableRow(2, "OpenSSL", "Stig Venaas, Wez Furlong, Sascha Kettler, Scott MacVicar")
	PhpInfoPrintTableRow(2, "Oracle (OCI) driver for PDO", "Wez Furlong")
	PhpInfoPrintTableRow(2, "pcntl", "Jason Greene, Arnaud Le Blanc")
	PhpInfoPrintTableRow(2, "Perl Compatible Regexps", "Andrei Zmievski")
	PhpInfoPrintTableRow(2, "PHP Archive", "Gregory Beaver, Marcus Boerger")
	PhpInfoPrintTableRow(2, "PHP Data Objects", "Wez Furlong, Marcus Boerger, Sterling Hughes, George Schlossnagle, Ilia Alshanetsky")
	PhpInfoPrintTableRow(2, "PHP hash", "Sara Golemon, Rasmus Lerdorf, Stefan Esser, Michael Wallner, Scott MacVicar")
	PhpInfoPrintTableRow(2, "Posix", "Kristian Koehntopp")
	PhpInfoPrintTableRow(2, "PostgreSQL driver for PDO", "Edin Kadribasic, Ilia Alshanetsky")
	PhpInfoPrintTableRow(2, "PostgreSQL", "Jouni Ahto, Zeev Suraski, Yasuo Ohgaki, Chris Kings-Lynne")
	PhpInfoPrintTableRow(2, "Pspell", "Vlad Krupin")
	PhpInfoPrintTableRow(2, "Readline", "Thies C. Arntzen")
	PhpInfoPrintTableRow(2, "Reflection", "Marcus Boerger, Timm Friebe, George Schlossnagle, Andrei Zmievski, Johannes Schlueter")
	PhpInfoPrintTableRow(2, "Sessions", "Sascha Schumann, Andrei Zmievski")
	PhpInfoPrintTableRow(2, "Shared Memory Operations", "Slava Poliakov, Ilia Alshanetsky")
	PhpInfoPrintTableRow(2, "SimpleXML", "Sterling Hughes, Marcus Boerger, Rob Richards")
	PhpInfoPrintTableRow(2, "SNMP", "Rasmus Lerdorf, Harrie Hazewinkel, Mike Jackson, Steven Lawrance, Johann Hanne, Boris Lytochkin")
	PhpInfoPrintTableRow(2, "SOAP", "Brad Lafountain, Shane Caraveo, Dmitry Stogov")
	PhpInfoPrintTableRow(2, "Sockets", "Chris Vandomelen, Sterling Hughes, Daniel Beulshausen, Jason Greene")
	PhpInfoPrintTableRow(2, "Sodium", "Frank Denis")
	PhpInfoPrintTableRow(2, "SPL", "Marcus Boerger, Etienne Kneuss")
	PhpInfoPrintTableRow(2, "SQLite 3.x driver for PDO", "Wez Furlong")
	PhpInfoPrintTableRow(2, "SQLite3", "Scott MacVicar, Ilia Alshanetsky, Brad Dewar")
	PhpInfoPrintTableRow(2, "System V Message based IPC", "Wez Furlong")
	PhpInfoPrintTableRow(2, "System V Semaphores", "Tom May")
	PhpInfoPrintTableRow(2, "System V Shared Memory", "Christian Cartus")
	PhpInfoPrintTableRow(2, "tidy", "John Coggeshall, Ilia Alshanetsky")
	PhpInfoPrintTableRow(2, "tokenizer", "Andrei Zmievski, Johannes Schlueter")
	PhpInfoPrintTableRow(2, "XML", "Stig Bakken, Thies C. Arntzen, Sterling Hughes")
	PhpInfoPrintTableRow(2, "XMLReader", "Rob Richards")
	PhpInfoPrintTableRow(2, "xmlrpc", "Dan Libby")
	PhpInfoPrintTableRow(2, "XMLWriter", "Rob Richards, Pierre-Alain Joye")
	PhpInfoPrintTableRow(2, "XSL", "Christian Stocker, Rob Richards")
	PhpInfoPrintTableRow(2, "Zip", "Pierre-Alain Joye, Remi Collet")
	PhpInfoPrintTableRow(2, "Zlib", "Rasmus Lerdorf, Stefan Roehrich, Zeev Suraski, Jade Nicoletti, Michael Wallner")
}
