// <<generate>>

package standard

// Source: <ext/standard/credits_sapi.h>

/*
                      DO NOT EDIT THIS FILE!

 it has been automatically created by scripts/dev/credits from
 the information found in the various ext/.../CREDITS and
 sapi/.../CREDITS files

 if you want to change an entry you have to edit the appropriate
 CREDITS file instead

*/
