// <<generate>>

package standard

const PHP_HRTIME_PLATFORM_POSIX = 0
const PHP_HRTIME_PLATFORM_WINDOWS = 0
const PHP_HRTIME_PLATFORM_APPLE = 0
const PHP_HRTIME_PLATFORM_HPUX = 0
const PHP_HRTIME_PLATFORM_AIX = 0
const HRTIME_AVAILABLE = PHP_HRTIME_PLATFORM_POSIX || PHP_HRTIME_PLATFORM_WINDOWS || PHP_HRTIME_PLATFORM_APPLE || PHP_HRTIME_PLATFORM_HPUX || PHP_HRTIME_PLATFORM_AIX

type PhpHrtimeT = uint64

const NANO_IN_SEC = 1000000000
