package standard

import (
	"sik/zend"
)

const ENT_HTML_QUOTE_NONE = 0
const ENT_HTML_QUOTE_SINGLE = 1
const ENT_HTML_QUOTE_DOUBLE = 2
const ENT_HTML_IGNORE_ERRORS = 4
const ENT_HTML_SUBSTITUTE_ERRORS = 8
const ENT_HTML_DOC_TYPE_MASK = 16 | 32
const ENT_HTML_DOC_HTML401 = 0
const ENT_HTML_DOC_XML1 = 16
const ENT_HTML_DOC_XHTML = 32
const ENT_HTML_DOC_HTML5 = 16 | 32

/* reserve bit 6 */

const ENT_HTML_SUBSTITUTE_DISALLOWED_CHARS = 128
const ENT_COMPAT zend.ZendLong = ENT_HTML_QUOTE_DOUBLE
const ENT_QUOTES zend.ZendLong = ENT_HTML_QUOTE_DOUBLE | ENT_HTML_QUOTE_SINGLE
const ENT_NOQUOTES zend.ZendLong = ENT_HTML_QUOTE_NONE
const ENT_IGNORE zend.ZendLong = ENT_HTML_IGNORE_ERRORS
const ENT_SUBSTITUTE zend.ZendLong = ENT_HTML_SUBSTITUTE_ERRORS
const ENT_HTML401 = 0
const ENT_XML1 = 16
const ENT_XHTML = 32
const ENT_HTML5 zend.ZendLong = 16 | 32
const ENT_DISALLOWED = 128

const HTML_SPECIALCHARS = 0
const HTML_ENTITIES = 1
