// <<generate>>

package standard

// Source: <ext/standard/html_tables.h>

/*
   +----------------------------------------------------------------------+
   | PHP Version 7                                                        |
   +----------------------------------------------------------------------+
   | Copyright (c) The PHP Group                                          |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

/**************************************************************************
***************************************************************************
**        THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.        **
***************************************************************************
** Please change html_tables/html_table_gen.php instead and then         **
** run it in order to generate this file                                 **
***************************************************************************
**************************************************************************/

/* longest entity name length excluding & and ; */

/* Definitions for mappings *to* Unicode.
 * The origin charset must have at most 256 code points.
 * The multi-byte encodings are not supported */

/* bits 7-8 bits (only single bytes encodings supported )*/

/* bits 1-6 */

/* {{{ Mappings *to* Unicode for ISO-8859-1 */

/* end of stage 2 tables for ISO-8859-1 }}} */

/* end of stage 1 table for ISO-8859-1 }}} */

/* end of stage 2 tables for ISO-8859-5 }}} */

/* end of stage 1 table for ISO-8859-5 }}} */

/* end of stage 2 tables for ISO-8859-15 }}} */

/* end of stage 1 table for ISO-8859-15 }}} */

/* end of stage 2 tables for Windows-1252 }}} */

/* end of stage 1 table for Windows-1252 }}} */

/* end of stage 2 tables for Windows-1251 }}} */

/* end of stage 1 table for Windows-1251 }}} */

/* end of stage 2 tables for KOI8-R }}} */

/* end of stage 1 table for KOI8-R }}} */

/* end of stage 2 tables for CP-866 }}} */

/* end of stage 1 table for CP-866 }}} */

/* end of stage 2 tables for MacRoman }}} */

/* end of stage 1 table for MacRoman }}} */

/* }}} */

/* {{{ Mappings *from* Unicode for ISO-8859-15 */

/* {{{ end of mappings *from* Unicode for ISO-8859-15 */

/* {{{ end of mappings *from* Unicode for Windows-1252 */

/* {{{ end of mappings *from* Unicode for Windows-1251 */

/* {{{ end of mappings *from* Unicode for KOI8-R */

/* {{{ end of mappings *from* Unicode for CP-866 */

/* {{{ end of mappings *from* Unicode for MacRoman */

/* The default entity may be NULL. Binary search is still possible while
   is senseless as there are just two rows (see also find_entity_for_char()). */

/* blocks of these should start at code points k where k % 0xFC0 == 0 */

/* Calculate k & 0x3F Use as offset */

/* Calculate k & 0xFC0 >> 6. Use as offset */

/* For stage 1, Calculate k & 0xFFF000 >> 3*4.
 * If larger than 1D, we have no mapping. Otherwise lookup that index */

/* Replaced "GT" > "gt" and "QUOT" > "quot" for consistency's sake. */

/* End of double code point tables }}} */

/* end of stage 3 Tables for HTML5 }}} */

/* end of stage 2 tables for HTML5 }}} */

/* end of HTML5 multi-stage table for codepoint -> entity }}} */

/* end of HTML5 hash table for entity -> codepoint }}} */

/* end of stage 3 Tables for HTML 4.01 }}} */

/* end of stage 2 tables for HTML 4.01 }}} */

/* end of HTML 4.01 multi-stage table for codepoint -> entity }}} */

/* end of HTML 4.01 hash table for entity -> codepoint }}} */

/* {{{ Basic entities (no apos) hash table for entity -> codepoint */

/* end of Basic entities (no apos) hash table for entity -> codepoint }}} */

/* {{{ Basic entities (with apos) hash table for entity -> codepoint */

/* end of Basic entities (with apos) hash table for entity -> codepoint }}} */
