// <<generate>>

package standard

const PHP_SORT_REGULAR = 0
const PHP_SORT_NUMERIC = 1
const PHP_SORT_STRING = 2
const PHP_SORT_DESC = 3
const PHP_SORT_ASC = 4
const PHP_SORT_LOCALE_STRING = 5
const PHP_SORT_NATURAL = 6
const PHP_SORT_FLAG_CASE = 8
const COUNT_NORMAL = 0
const COUNT_RECURSIVE = 1
const ARRAY_FILTER_USE_BOTH = 1
const ARRAY_FILTER_USE_KEY = 2
