// <<generate>>

package standard

type ImageFiletype = int

const (
	IMAGE_FILETYPE_UNKNOWN = 0
	IMAGE_FILETYPE_GIF     = 1
	IMAGE_FILETYPE_JPEG
	IMAGE_FILETYPE_PNG
	IMAGE_FILETYPE_SWF
	IMAGE_FILETYPE_PSD
	IMAGE_FILETYPE_BMP
	IMAGE_FILETYPE_TIFF_II
	IMAGE_FILETYPE_TIFF_MM
	IMAGE_FILETYPE_JPC
	IMAGE_FILETYPE_JP2
	IMAGE_FILETYPE_JPX
	IMAGE_FILETYPE_JB2
	IMAGE_FILETYPE_SWC
	IMAGE_FILETYPE_IFF
	IMAGE_FILETYPE_WBMP
	IMAGE_FILETYPE_XBM
	IMAGE_FILETYPE_ICO
	IMAGE_FILETYPE_WEBP
	IMAGE_FILETYPE_COUNT
)
