// <<generate>>

package standard

import (
	"sik/zend"
)

const SCAN_MAX_ARGS = 0xff
const SCAN_SUCCESS = zend.SUCCESS
const SCAN_ERROR_EOF = -1
const SCAN_ERROR_INVALID_FORMAT = SCAN_ERROR_EOF - 1
const SCAN_ERROR_VAR_PASSED_BYVAL = SCAN_ERROR_INVALID_FORMAT - 1
const SCAN_ERROR_WRONG_PARAM_COUNT = SCAN_ERROR_VAR_PASSED_BYVAL - 1
const SCAN_ERROR_INTERNAL = SCAN_ERROR_WRONG_PARAM_COUNT - 1
const SCAN_NOSKIP = 0x1
const SCAN_SUPPRESS = 0x2
const SCAN_UNSIGNED = 0x4
const SCAN_WIDTH = 0x8
const SCAN_SIGNOK = 0x10
const SCAN_NODIGITS = 0x20
const SCAN_NOZERO = 0x40
const SCAN_XOK = 0x80
const SCAN_PTOK = 0x100
const SCAN_EXPOK = 0x200
