package standard

var ZmStartupUrlScannerEx func(type_ int, module_number int) int
var ZmShutdownUrlScannerEx func(type_ int, module_number int) int
var ZmActivateUrlScannerEx func(type_ int, module_number int) int
var ZmDeactivateUrlScannerEx func(type_ int, module_number int) int

/* Generated by re2c 0.13.5 */

const UrlScanner = url_scanner_ex

/* FIXME: OnUpdate*Hosts cannot set default to $_SERVER['HTTP_HOST'] at startup */

const YYCURSOR []byte = p
const YYLIMIT []byte = q
const YYMARKER []byte = r
const (
	TAG_NORMAL = 0
	TAG_FORM
)
const (
	ATTR_NORMAL = 0
	ATTR_ACTION
)
const (
	STATE_PLAIN = 0
	STATE_TAG
	STATE_NEXT_ARG
	STATE_ARG
	STATE_BEFORE_VAL
	STATE_VAL
)
