// <<generate>>

package standard

import (
	"sik/core"
	r "sik/runtime"
	g "sik/runtime/grammar"
	"sik/zend"
)

// Source: <ext/standard/url_scanner_ex.h>

/*
  +----------------------------------------------------------------------+
  | PHP Version 7                                                        |
  +----------------------------------------------------------------------+
  | Copyright (c) The PHP Group                                          |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author: Sascha Schumann <sascha@schumann.cx>                         |
  +----------------------------------------------------------------------+
*/

// #define URL_SCANNER_EX_H

var ZmStartupUrlScannerEx func(type_ int, module_number int) int
var ZmShutdownUrlScannerEx func(type_ int, module_number int) int
var ZmActivateUrlScannerEx func(type_ int, module_number int) int
var ZmDeactivateUrlScannerEx func(type_ int, module_number int) int

// # include "zend_smart_str_public.h"

// Source: <ext/standard/url_scanner_ex.c>

/* Generated by re2c 0.13.5 */

// # include "php.h"

// # include < unistd . h >

// # include < limits . h >

// # include < stdio . h >

// # include < stdlib . h >

// # include < string . h >

// # include "SAPI.h"

// # include "php_ini.h"

// # include "php_globals.h"

// # include "php_string.h"

// #define STATE_TAG       SOME_OTHER_STATE_TAG

// # include "basic_functions.h"

// # include "url.h"

// # include "html.h"

// #define url_scanner       url_scanner_ex

// # include "zend_smart_str.h"

func TagDtor(zv *zend.Zval) { zend.Free(zv.value.ptr) }
func PhpIniOnUpdateTags(entry *zend.ZendIniEntry, new_value *zend.ZendString, mh_arg1 any, mh_arg2 any, mh_arg3 any, stage int, type_ int) int {
	var ctx *UrlAdaptStateExT
	var key *byte
	var tmp *byte
	var lasts *byte = nil
	if type_ != 0 {
		ctx = &(BasicGlobals.GetUrlAdaptSessionEx())
	} else {
		ctx = &(BasicGlobals.GetUrlAdaptOutputEx())
	}
	tmp = zend._estrndup(new_value.val, new_value.len_)
	if ctx.GetTags() != nil {
		zend.ZendHashDestroy(ctx.GetTags())
	} else {
		ctx.SetTags(zend.Malloc(g.SizeOf("HashTable")))
		if ctx.GetTags() == nil {
			zend._efree(tmp)
			return zend.FAILURE
		}
	}
	zend._zendHashInit(ctx.GetTags(), 0, TagDtor, 1)
	for key = strtok_r(tmp, ",", &lasts); key != nil; key = strtok_r(nil, ",", &lasts) {
		var val *byte
		val = strchr(key, '=')
		if val != nil {
			var q *byte
			var keylen int
			var str *zend.ZendString
			g.PostInc(&(*val)) = '0'
			for q = key; *q; q++ {
				*q = tolower(*q)
			}
			keylen = q - key
			str = zend.ZendStringInit(key, keylen, 1)

			zend.ZendHashAddMem(ctx.GetTags(), str, val, strlen(val)+1)
			zend.ZendStringReleaseEx(str, 1)
		}
	}
	zend._efree(tmp)
	return zend.SUCCESS
}
func OnUpdateSessionTags(entry *zend.ZendIniEntry, new_value *zend.ZendString, mh_arg1 any, mh_arg2 any, mh_arg3 any, stage int) int {
	return PhpIniOnUpdateTags(entry, new_value, mh_arg1, mh_arg2, mh_arg3, stage, 1)
}
func OnUpdateOutputTags(entry *zend.ZendIniEntry, new_value *zend.ZendString, mh_arg1 any, mh_arg2 any, mh_arg3 any, stage int) int {
	return PhpIniOnUpdateTags(entry, new_value, mh_arg1, mh_arg2, mh_arg3, stage, 0)
}
func PhpIniOnUpdateHosts(entry *zend.ZendIniEntry, new_value *zend.ZendString, mh_arg1 any, mh_arg2 any, mh_arg3 any, stage int, type_ int) int {
	var hosts *zend.HashTable
	var key *byte
	var tmp *byte
	var lasts *byte = nil
	if type_ != 0 {
		hosts = &(BasicGlobals.GetUrlAdaptSessionHostsHt())
	} else {
		hosts = &(BasicGlobals.GetUrlAdaptOutputHostsHt())
	}
	zend.ZendHashClean(hosts)

	/* Use user supplied host whitelist */

	tmp = zend._estrndup(new_value.val, new_value.len_)
	for key = strtok_r(tmp, ",", &lasts); key != nil; key = strtok_r(nil, ",", &lasts) {
		var keylen int
		var tmp_key *zend.ZendString
		var q *byte
		for q = key; *q; q++ {
			*q = tolower(*q)
		}
		keylen = q - key
		if keylen > 0 {
			tmp_key = zend.ZendStringInit(key, keylen, 0)
			zend.ZendHashAddEmptyElement(hosts, tmp_key)
			zend.ZendStringReleaseEx(tmp_key, 0)
		}
	}
	zend._efree(tmp)
	return zend.SUCCESS
}
func OnUpdateSessionHosts(entry *zend.ZendIniEntry, new_value *zend.ZendString, mh_arg1 any, mh_arg2 any, mh_arg3 any, stage int) int {
	return PhpIniOnUpdateHosts(entry, new_value, mh_arg1, mh_arg2, mh_arg3, stage, 1)
}
func OnUpdateOutputHosts(entry *zend.ZendIniEntry, new_value *zend.ZendString, mh_arg1 any, mh_arg2 any, mh_arg3 any, stage int) int {
	return PhpIniOnUpdateHosts(entry, new_value, mh_arg1, mh_arg2, mh_arg3, stage, 0)
}

/* FIXME: OnUpdate*Hosts cannot set default to $_SERVER['HTTP_HOST'] at startup */

// #define YYFILL(n) goto done

// #define YYCTYPE       unsigned char

// #define YYCURSOR       p

// #define YYLIMIT       q

// #define YYMARKER       r

func AppendModifiedUrl(url *zend.SmartStr, dest *zend.SmartStr, url_app *zend.SmartStr, separator *byte) {
	var url_parts *PhpUrl
	zend.SmartStr0(url)
	url_parts = PhpUrlParseEx(url.s.val, url.s.len_)

	/* Ignore malformed URLs */

	if url_parts == nil {
		zend.SmartStrAppendSmartStrEx(dest, url, 0)
		return
	}

	/* Don't modify URLs of the format "#mark" */

	if url_parts.GetFragment() != nil && '#' == url.s.val[0] {
		zend.SmartStrAppendSmartStrEx(dest, url, 0)
		PhpUrlFree(url_parts)
		return
	}

	/* Check protocol. Only http/https is allowed. */

	if url_parts.GetScheme() != nil && !(url_parts.GetScheme().len_ == g.SizeOf("\"http\"")-1 && zend.ZendBinaryStrcasecmp(url_parts.GetScheme().val, url_parts.GetScheme().len_, "http", g.SizeOf("\"http\"")-1) == 0) && !(url_parts.GetScheme().len_ == g.SizeOf("\"https\"")-1 && zend.ZendBinaryStrcasecmp(url_parts.GetScheme().val, url_parts.GetScheme().len_, "https", g.SizeOf("\"https\"")-1) == 0) {
		zend.SmartStrAppendSmartStrEx(dest, url, 0)
		PhpUrlFree(url_parts)
		return
	}

	/* Check host whitelist. If it's not listed, do nothing. */

	if url_parts.GetHost() != nil {
		var tmp *zend.ZendString = zend.ZendStringTolowerEx(url_parts.GetHost(), 0)
		if zend.ZendHashExists(&(BasicGlobals.GetUrlAdaptSessionHostsHt()), tmp) == 0 {
			zend.ZendStringReleaseEx(tmp, 0)
			zend.SmartStrAppendSmartStrEx(dest, url, 0)
			PhpUrlFree(url_parts)
			return
		}
		zend.ZendStringReleaseEx(tmp, 0)
	}

	/*
	 * When URL does not have path and query string add "/?".
	 * i.e. If URL is only "?foo=bar", should not add "/?".
	 */

	if url_parts.GetPath() == nil && url_parts.GetQuery() == nil && url_parts.GetFragment() == nil {

		/* URL is http://php.net or like */

		zend.SmartStrAppendSmartStrEx(dest, url, 0)
		zend.SmartStrAppendcEx(dest, '/', 0)
		zend.SmartStrAppendcEx(dest, '?', 0)
		zend.SmartStrAppendSmartStrEx(dest, url_app, 0)
		PhpUrlFree(url_parts)
		return
	}
	if url_parts.GetScheme() != nil {
		zend.SmartStrAppendlEx(dest, url_parts.GetScheme().val, strlen(url_parts.GetScheme().val), 0)
		zend.SmartStrAppendlEx(dest, "://", strlen("://"), 0)
	} else if (*(url.s.val)) == '/' && (*(url.s.val + 1)) == '/' {
		zend.SmartStrAppendlEx(dest, "//", strlen("//"), 0)
	}
	if url_parts.GetUser() != nil {
		zend.SmartStrAppendlEx(dest, url_parts.GetUser().val, strlen(url_parts.GetUser().val), 0)
		if url_parts.GetPass() != nil {
			zend.SmartStrAppendlEx(dest, url_parts.GetPass().val, strlen(url_parts.GetPass().val), 0)
			zend.SmartStrAppendcEx(dest, ':', 0)
		}
		zend.SmartStrAppendcEx(dest, '@', 0)
	}
	if url_parts.GetHost() != nil {
		zend.SmartStrAppendlEx(dest, url_parts.GetHost().val, strlen(url_parts.GetHost().val), 0)
	}
	if url_parts.GetPort() != 0 {
		zend.SmartStrAppendcEx(dest, ':', 0)
		zend.SmartStrAppendUnsignedEx(dest, long(url_parts.GetPort()), 0)
	}
	if url_parts.GetPath() != nil {
		zend.SmartStrAppendlEx(dest, url_parts.GetPath().val, strlen(url_parts.GetPath().val), 0)
	}
	zend.SmartStrAppendcEx(dest, '?', 0)
	if url_parts.GetQuery() != nil {
		zend.SmartStrAppendlEx(dest, url_parts.GetQuery().val, strlen(url_parts.GetQuery().val), 0)
		zend.SmartStrAppendlEx(dest, separator, strlen(separator), 0)
		zend.SmartStrAppendSmartStrEx(dest, url_app, 0)
	} else {
		zend.SmartStrAppendSmartStrEx(dest, url_app, 0)
	}
	if url_parts.GetFragment() != nil {
		zend.SmartStrAppendcEx(dest, '#', 0)
		zend.SmartStrAppendlEx(dest, url_parts.GetFragment().val, strlen(url_parts.GetFragment().val), 0)
	}
	PhpUrlFree(url_parts)
}

const (
	TAG_NORMAL = 0
	TAG_FORM
)
const (
	ATTR_NORMAL = 0
	ATTR_ACTION
)

func TagArg(ctx *UrlAdaptStateExT, quotes byte, type_ byte) {
	var f byte = 0

	/* arg.s is string WITHOUT NUL.
	   To avoid partial match, NUL is added here */

	ctx.arg.s.val[ctx.arg.s.len_] = '0'
	if !(strcasecmp(ctx.arg.s.val, ctx.GetLookupData())) {
		f = 1
	}
	if quotes {
		zend.SmartStrAppendcEx(&ctx.result, type_, 0)
	}
	if f {
		AppendModifiedUrl(&ctx.val, &ctx.result, &ctx.url_app, core.CoreGlobals.arg_separator.output)
	} else {
		zend.SmartStrAppendSmartStrEx(&ctx.result, &ctx.val, 0)
	}
	if quotes {
		zend.SmartStrAppendcEx(&ctx.result, type_, 0)
	}
}

const (
	STATE_PLAIN = 0
	STATE_TAG
	STATE_NEXT_ARG
	STATE_ARG
	STATE_BEFORE_VAL
	STATE_VAL
)

// #define YYFILL(n) goto stop

// #define YYCTYPE       unsigned char

// #define YYCURSOR       xp

// #define YYLIMIT       end

// #define YYMARKER       q

// #define STATE       ctx -> state

// #define STD_PARA       url_adapt_state_ex_t * ctx , char * start , char * YYCURSOR

// #define STD_ARGS       ctx , start , xp

// #define scdebug(x)

func Passthru(ctx *UrlAdaptStateExT, start *byte, xp *byte) {
	zend.SmartStrAppendlEx(&ctx.result, start, xp-start, 0)
}
func CheckHttpHost(target *byte) int {
	var host *zend.Zval
	var tmp *zend.Zval
	var host_tmp *zend.ZendString
	var colon *byte
	if g.Assign(&tmp, zend.ZendHashStrFind(&zend.EG.symbol_table, "_SERVER", g.SizeOf("\"_SERVER\"")-1)) && tmp.u1.v.type_ == 7 && g.Assign(&host, zend.ZendHashStrFind(tmp.value.arr, "HTTP_HOST", g.SizeOf("\"HTTP_HOST\"")-1)) && host.u1.v.type_ == 6 {
		host_tmp = zend.ZendStringInit(host.value.str.val, host.value.str.len_, 0)

		/* HTTP_HOST could be 'localhost:8888' etc. */

		colon = strchr(host_tmp.val, ':')
		if colon != nil {
			host_tmp.len_ = colon - host_tmp.val
			host_tmp.val[host_tmp.len_] = '0'
		}
		if !(strcasecmp(host_tmp.val, target)) {
			zend.ZendStringReleaseEx(host_tmp, 0)
			return zend.SUCCESS
		}
		zend.ZendStringReleaseEx(host_tmp, 0)
	}
	return zend.FAILURE
}
func CheckHostWhitelist(ctx *UrlAdaptStateExT) int {
	var url_parts *PhpUrl = nil
	var allowed_hosts *zend.HashTable = g.CondF(ctx.GetType() != 0, func() *zend.HashTable { return &(BasicGlobals.GetUrlAdaptSessionHostsHt()) }, func() *zend.HashTable { return &(BasicGlobals.GetUrlAdaptOutputHostsHt()) })
	r.Assert(ctx.GetTagType() == TAG_FORM)
	if ctx.attr_val.s != nil && ctx.attr_val.s.len_ != 0 {
		url_parts = PhpUrlParseEx(ctx.attr_val.s.val, ctx.attr_val.s.len_)
	} else {
		return zend.SUCCESS
	}
	if url_parts == nil {
		return zend.FAILURE
	}
	if url_parts.GetScheme() != nil {

		/* Only http/https should be handled.
		   A bit hacky check this here, but saves a URL parse. */

		if !(url_parts.GetScheme().len_ == g.SizeOf("\"http\"")-1 && zend.ZendBinaryStrcasecmp(url_parts.GetScheme().val, url_parts.GetScheme().len_, "http", g.SizeOf("\"http\"")-1) == 0) && !(url_parts.GetScheme().len_ == g.SizeOf("\"https\"")-1 && zend.ZendBinaryStrcasecmp(url_parts.GetScheme().val, url_parts.GetScheme().len_, "https", g.SizeOf("\"https\"")-1) == 0) {
			PhpUrlFree(url_parts)
			return zend.FAILURE
		}

		/* Only http/https should be handled.
		   A bit hacky check this here, but saves a URL parse. */

	}
	if url_parts.GetHost() == nil {
		PhpUrlFree(url_parts)
		return zend.SUCCESS
	}
	if allowed_hosts.nNumOfElements == 0 && CheckHttpHost(url_parts.GetHost().val) == zend.SUCCESS {
		PhpUrlFree(url_parts)
		return zend.SUCCESS
	}
	if zend.ZendHashFind(allowed_hosts, url_parts.GetHost()) == nil {
		PhpUrlFree(url_parts)
		return zend.FAILURE
	}
	PhpUrlFree(url_parts)
	return zend.SUCCESS
}

/*
 * This function appends a hidden input field after a <form>.
 */

func HandleForm(ctx *UrlAdaptStateExT, start *byte, xp *byte) {
	var doit int = 0
	if ctx.form_app.s.len_ > 0 {
		switch ctx.tag.s.len_ {
		case g.SizeOf("\"form\"") - 1:
			if !(strncasecmp(ctx.tag.s.val, "form", ctx.tag.s.len_)) && CheckHostWhitelist(ctx) == zend.SUCCESS {
				doit = 1
			}
			break
		}
	}
	if doit != 0 {
		zend.SmartStrAppendSmartStrEx(&ctx.result, &ctx.form_app, 0)
	}
}

/*
 *  HANDLE_TAG copies the HTML Tag and checks whether we
 *  have that tag in our table. If we might modify it,
 *  we continue to scan the tag, otherwise we simply copy the complete
 *  HTML stuff to the result buffer.
 */

func HandleTag(ctx *UrlAdaptStateExT, start *byte, xp *byte) {
	var ok int = 0
	var i uint
	if ctx.tag.s != nil {
		ctx.tag.s.len_ = 0
	}
	zend.SmartStrAppendlEx(&ctx.tag, start, xp-start, 0)
	for i = 0; i < ctx.tag.s.len_; i++ {
		ctx.tag.s.val[i] = tolower(int(uint8(ctx.tag.s.val[i])))
	}

	/* intentionally using str_find here, in case the hash value is set, but the string val is changed later */

	if g.Assign(&(ctx.GetLookupData()), zend.ZendHashStrFindPtr(ctx.GetTags(), ctx.tag.s.val, ctx.tag.s.len_)) != nil {
		ok = 1
		if ctx.tag.s.len_ == g.SizeOf("\"form\"")-1 && !(strncasecmp(ctx.tag.s.val, "form", ctx.tag.s.len_)) {
			ctx.SetTagType(TAG_FORM)
		} else {
			ctx.SetTagType(TAG_NORMAL)
		}
	}
	if ok != 0 {
		ctx.SetState(STATE_NEXT_ARG)
	} else {
		ctx.SetState(STATE_PLAIN)
	}
}
func HandleArg(ctx *UrlAdaptStateExT, start *byte, xp *byte) {
	if ctx.arg.s != nil {
		ctx.arg.s.len_ = 0
	}
	zend.SmartStrAppendlEx(&ctx.arg, start, xp-start, 0)
	if ctx.GetTagType() == TAG_FORM && strncasecmp(ctx.arg.s.val, "action", ctx.arg.s.len_) == 0 {
		ctx.SetAttrType(ATTR_ACTION)
	} else {
		ctx.SetAttrType(ATTR_NORMAL)
	}
}
func HandleVal(ctx *UrlAdaptStateExT, start *byte, xp *byte, quotes byte, type_ byte) {
	zend.SmartStrSetl(&ctx.val, start+quotes, xp-start-quotes*2)
	if ctx.GetTagType() == TAG_FORM && ctx.GetAttrType() == ATTR_ACTION {
		zend.SmartStrSetl(&ctx.attr_val, start+quotes, xp-start-quotes*2)
	}
	TagArg(ctx, quotes, type_)
}
func XxMainloop(ctx *UrlAdaptStateExT, newdata *byte, newlen int) {
	var end *byte
	var q *byte
	var xp *byte
	var start *byte
	var rest int
	zend.SmartStrAppendlEx(&ctx.buf, newdata, newlen, 0)
	xp = ctx.buf.s.val
	end = ctx.buf.s.val + ctx.buf.s.len_
	switch ctx.GetState() {
	case STATE_PLAIN:
		goto state_plain
	case STATE_TAG:
		goto state_tag
	case STATE_NEXT_ARG:
		goto state_next_arg
	case STATE_ARG:
		goto state_arg
	case STATE_BEFORE_VAL:
		goto state_before_val
	case STATE_VAL:
		goto state_val
	}
state_plain_begin:
	ctx.SetState(STATE_PLAIN)
state_plain:
	start = xp
	var yych uint8
	var yybm []uint8 = []uint8{128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128}
	if end <= xp {
		goto stop
	}
	yych = *xp
	if (yybm[0+yych] & 128) != 0 {
		goto yy4
	}
	xp++
	Passthru(ctx, start, xp)
	ctx.SetState(STATE_TAG)
	goto state_tag
yy4:
	xp++
	if end <= xp {
		goto stop
	}
	yych = *xp
	if (yybm[0+yych] & 128) != 0 {
		goto yy4
	}
	Passthru(ctx, start, xp)
	goto state_plain
state_tag:
	start = xp
	var yych uint8
	var yybm []uint8 = []uint8{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0, 0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	if end-xp < 2 {
		goto stop
	}
	yych = *xp
	if yych <= '@' {
		if yych != ':' {
			goto yy11
		}
	} else {
		if yych <= 'Z' {
			goto yy9
		}
		if yych <= '`' {
			goto yy11
		}
		if yych >= '{' {
			goto yy11
		}
	}
yy9:
	xp++
	yych = *xp
	goto yy14
yy10:
	HandleTag(ctx, start, xp)
	Passthru(ctx, start, xp)
	if ctx.GetState() == STATE_PLAIN {
		goto state_plain
	} else {
		goto state_next_arg
	}
yy11:
	xp++
	Passthru(ctx, start, xp)
	goto state_plain_begin
yy13:
	xp++
	if end <= xp {
		goto stop
	}
	yych = *xp
yy14:
	if (yybm[0+yych] & 128) != 0 {
		goto yy13
	}
	goto yy10
state_next_arg_begin:
	ctx.SetState(STATE_NEXT_ARG)
state_next_arg:
	start = xp
	var yych uint8
	var yybm []uint8 = []uint8{0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 128, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	if end-xp < 2 {
		goto stop
	}
	yych = *xp
	if yych <= '.' {
		if yych <= 'f' {
			if yych <= 0x8 {
				goto yy25
			}
			if yych <= 'v' {
				goto yy21
			}
			goto yy25
		} else {
			if yych <= '\r' {
				goto yy21
			}
			if yych == ' ' {
				goto yy21
			}
			goto yy25
		}
	} else {
		if yych <= '@' {
			if yych <= '/' {
				goto yy17
			}
			if yych == '>' {
				goto yy19
			}
			goto yy25
		} else {
			if yych <= 'Z' {
				goto yy23
			}
			if yych <= '`' {
				goto yy25
			}
			if yych <= 'z' {
				goto yy23
			}
			goto yy25
		}
	}
yy17:
	xp++
	if g.Assign(&yych, *xp) == '>' {
		goto yy28
	}
yy18:
	Passthru(ctx, start, xp)
	goto state_plain_begin
yy19:
	xp++
yy20:
	Passthru(ctx, start, xp)
	HandleForm(ctx, start, xp)
	goto state_plain_begin
yy21:
	xp++
	yych = *xp
	goto yy27
yy22:
	Passthru(ctx, start, xp)
	goto state_next_arg
yy23:
	xp++
	xp--
	ctx.SetState(STATE_ARG)
	goto state_arg
yy25:
	yych = *(g.PreInc(&xp))
	goto yy18
yy26:
	xp++
	if end <= xp {
		goto stop
	}
	yych = *xp
yy27:
	if (yybm[0+yych] & 128) != 0 {
		goto yy26
	}
	goto yy22
yy28:
	xp++
	yych = *xp
	goto yy20
state_arg:
	start = xp
	var yych uint8
	var yybm []uint8 = []uint8{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0, 0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	if end-xp < 2 {
		goto stop
	}
	yych = *xp
	if yych <= '@' {
		goto yy33
	}
	if yych <= 'Z' {
		goto yy31
	}
	if yych <= '`' {
		goto yy33
	}
	if yych >= '{' {
		goto yy33
	}
yy31:
	xp++
	yych = *xp
	goto yy36
yy32:
	Passthru(ctx, start, xp)
	HandleArg(ctx, start, xp)
	ctx.SetState(STATE_BEFORE_VAL)
	goto state_before_val
yy33:
	xp++
	Passthru(ctx, start, xp)
	ctx.SetState(STATE_NEXT_ARG)
	goto state_next_arg
yy35:
	xp++
	if end <= xp {
		goto stop
	}
	yych = *xp
yy36:
	if (yybm[0+yych] & 128) != 0 {
		goto yy35
	}
	goto yy32
state_before_val:
	start = xp
	var yych uint8
	var yybm []uint8 = []uint8{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	if end-xp < 2 {
		goto stop
	}
	yych = *xp
	if yych == ' ' {
		goto yy39
	}
	if yych == '=' {
		goto yy41
	}
	goto yy43
yy39:
	yych = *(g.Assign(&q, g.PreInc(&xp)))
	if yych == ' ' {
		goto yy46
	}
	if yych == '=' {
		goto yy44
	}
yy40:
	xp--
	goto state_next_arg_begin
yy41:
	xp++
	yych = *xp
	goto yy45
yy42:
	Passthru(ctx, start, xp)
	ctx.SetState(STATE_VAL)
	goto state_val
yy43:
	yych = *(g.PreInc(&xp))
	goto yy40
yy44:
	xp++
	if end <= xp {
		goto stop
	}
	yych = *xp
yy45:
	if (yybm[0+yych] & 128) != 0 {
		goto yy44
	}
	goto yy42
yy46:
	xp++
	if end <= xp {
		goto stop
	}
	yych = *xp
	if yych == ' ' {
		goto yy46
	}
	if yych == '=' {
		goto yy44
	}
	xp = q
	goto yy40
state_val:
	start = xp
	var yych uint8
	var yybm []uint8 = []uint8{224, 224, 224, 224, 224, 224, 224, 224, 224, 192, 192, 224, 224, 192, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 192, 224, 64, 224, 224, 224, 224, 128, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 0, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224}
	if end-xp < 2 {
		goto stop
	}
	yych = *xp
	if yych <= ' ' {
		if yych <= 'f' {
			if yych <= 0x8 {
				goto yy54
			}
			if yych <= '\n' {
				goto yy56
			}
			goto yy54
		} else {
			if yych <= '\r' {
				goto yy56
			}
			if yych <= 0x1f {
				goto yy54
			}
			goto yy56
		}
	} else {
		if yych <= '&' {
			if yych != '"' {
				goto yy54
			}
		} else {
			if yych <= '\'' {
				goto yy53
			}
			if yych == '>' {
				goto yy56
			}
			goto yy54
		}
	}
	yych = *(g.Assign(&q, g.PreInc(&xp)))
	if yych != '>' {
		goto yy65
	}
yy52:
	Passthru(ctx, start, xp)
	goto state_next_arg_begin
yy53:
	yych = *(g.Assign(&q, g.PreInc(&xp)))
	if yych == '>' {
		goto yy52
	}
	goto yy60
yy54:
	xp++
	yych = *xp
	goto yy58
yy55:
	HandleVal(ctx, start, xp, 0, ' ')
	goto state_next_arg_begin
yy56:
	yych = *(g.PreInc(&xp))
	goto yy52
yy57:
	xp++
	if end <= xp {
		goto stop
	}
	yych = *xp
yy58:
	if (yybm[0+yych] & 32) != 0 {
		goto yy57
	}
	goto yy55
yy59:
	xp++
	if end <= xp {
		goto stop
	}
	yych = *xp
yy60:
	if (yybm[0+yych] & 64) != 0 {
		goto yy59
	}
	if yych <= '=' {
		goto yy62
	}
yy61:
	xp = q
	goto yy52
yy62:
	xp++
	HandleVal(ctx, start, xp, 1, '\'')
	goto state_next_arg_begin
yy64:
	xp++
	if end <= xp {
		goto stop
	}
	yych = *xp
yy65:
	if (yybm[0+yych] & 128) != 0 {
		goto yy64
	}
	if yych >= '>' {
		goto yy61
	}
	xp++
	HandleVal(ctx, start, xp, 1, '"')
	goto state_next_arg_begin
stop:
	if end < start {

		/* XXX: Crash avoidance. Need to work with reporter to figure out what goes wrong */

		rest = 0

		/* XXX: Crash avoidance. Need to work with reporter to figure out what goes wrong */

	} else {
		rest = end - start
	}
	if rest != 0 {
		memmove(ctx.buf.s.val, start, rest)
	}
	ctx.buf.s.len_ = rest
}
func PhpUrlScannerAdaptSingleUrl(url *byte, urllen int, name *byte, value *byte, newlen *int, encode int) *byte {
	var result *byte
	var surl zend.SmartStr = zend.SmartStr{0}
	var buf zend.SmartStr = zend.SmartStr{0}
	var url_app zend.SmartStr = zend.SmartStr{0}
	var encoded *zend.ZendString
	zend.SmartStrAppendlEx(&surl, url, urllen, 0)
	if encode != 0 {
		encoded = PhpRawUrlEncode(name, strlen(name))
		zend.SmartStrAppendlEx(&url_app, encoded.val, encoded.len_, 0)
		zend.ZendStringFree(encoded)
	} else {
		zend.SmartStrAppendlEx(&url_app, name, strlen(name), 0)
	}
	zend.SmartStrAppendcEx(&url_app, '=', 0)
	if encode != 0 {
		encoded = PhpRawUrlEncode(value, strlen(value))
		zend.SmartStrAppendlEx(&url_app, encoded.val, encoded.len_, 0)
		zend.ZendStringFree(encoded)
	} else {
		zend.SmartStrAppendlEx(&url_app, value, strlen(value), 0)
	}
	AppendModifiedUrl(&surl, &buf, &url_app, core.CoreGlobals.arg_separator.output)
	zend.SmartStr0(&buf)
	if newlen != nil {
		*newlen = buf.s.len_
	}
	result = zend._estrndup(buf.s.val, buf.s.len_)
	zend.SmartStrFreeEx(&url_app, 0)
	zend.SmartStrFreeEx(&buf, 0)
	return result
}
func UrlAdaptExt(src *byte, srclen int, newlen *int, do_flush zend.ZendBool, ctx *UrlAdaptStateExT) *byte {
	var retval *byte
	XxMainloop(ctx, src, srclen)
	if ctx.result.s == nil {
		zend.SmartStrAppendlEx(&ctx.result, "", 0, 0)
		*newlen = 0
	} else {
		*newlen = ctx.result.s.len_
	}
	zend.SmartStr0(&ctx.result)
	if do_flush != 0 {
		zend.SmartStrAppendEx(&ctx.result, ctx.buf.s, 0)
		*newlen += ctx.buf.s.len_
		zend.SmartStrFreeEx(&ctx.buf, 0)
		zend.SmartStrFreeEx(&ctx.val, 0)
		zend.SmartStrFreeEx(&ctx.attr_val, 0)
	}
	retval = zend._estrndup(ctx.result.s.val, ctx.result.s.len_)
	zend.SmartStrFreeEx(&ctx.result, 0)
	return retval
}
func PhpUrlScannerExActivate(type_ int) int {
	var ctx *UrlAdaptStateExT
	if type_ != 0 {
		ctx = &(BasicGlobals.GetUrlAdaptSessionEx())
	} else {
		ctx = &(BasicGlobals.GetUrlAdaptOutputEx())
	}
	memset(ctx, 0, zend_long((*byte)(&((*UrlAdaptStateExT)(nil).GetTags()))-(*byte)(nil)))
	return zend.SUCCESS
}
func PhpUrlScannerExDeactivate(type_ int) int {
	var ctx *UrlAdaptStateExT
	if type_ != 0 {
		ctx = &(BasicGlobals.GetUrlAdaptSessionEx())
	} else {
		ctx = &(BasicGlobals.GetUrlAdaptOutputEx())
	}
	zend.SmartStrFreeEx(&ctx.result, 0)
	zend.SmartStrFreeEx(&ctx.buf, 0)
	zend.SmartStrFreeEx(&ctx.tag, 0)
	zend.SmartStrFreeEx(&ctx.arg, 0)
	zend.SmartStrFreeEx(&ctx.attr_val, 0)
	return zend.SUCCESS
}
func PhpUrlScannerSessionHandlerImpl(output *byte, output_len int, handled_output **byte, handled_output_len *int, mode int, type_ int) {
	var len_ int
	var url_state *UrlAdaptStateExT
	if type_ != 0 {
		url_state = &(BasicGlobals.GetUrlAdaptSessionEx())
	} else {
		url_state = &(BasicGlobals.GetUrlAdaptOutputEx())
	}
	if url_state.url_app.s.len_ != 0 {
		*handled_output = UrlAdaptExt(output, output_len, &len_, zend_bool(g.Cond((mode&(0x8|0x0|0x4|0x8)) != 0, 1, 0)), url_state)
		if g.SizeOf("unsigned int") < g.SizeOf("size_t") {
			if len_ > UINT_MAX {
				len_ = UINT_MAX
			}
		}
		*handled_output_len = len_
	} else if url_state.url_app.s.len_ == 0 {
		var ctx *UrlAdaptStateExT = url_state
		if ctx.buf.s != nil && ctx.buf.s.len_ != 0 {
			zend.SmartStrAppendEx(&ctx.result, ctx.buf.s, 0)
			zend.SmartStrAppendlEx(&ctx.result, output, output_len, 0)
			*handled_output = zend._estrndup(ctx.result.s.val, ctx.result.s.len_)
			*handled_output_len = ctx.buf.s.len_ + output_len
			zend.SmartStrFreeEx(&ctx.buf, 0)
			zend.SmartStrFreeEx(&ctx.result, 0)
		} else {
			*handled_output = zend._estrndup(output, g.Assign(&(*handled_output_len), output_len))
		}
	} else {
		*handled_output = nil
	}
}
func PhpUrlScannerSessionHandler(output *byte, output_len int, handled_output **byte, handled_output_len *int, mode int) {
	PhpUrlScannerSessionHandlerImpl(output, output_len, handled_output, handled_output_len, mode, 1)
}
func PhpUrlScannerOutputHandler(output *byte, output_len int, handled_output **byte, handled_output_len *int, mode int) {
	PhpUrlScannerSessionHandlerImpl(output, output_len, handled_output, handled_output_len, mode, 0)
}
func PhpUrlScannerAddVarImpl(name *byte, name_len int, value *byte, value_len int, encode int, type_ int) int {
	var sname zend.SmartStr = zend.SmartStr{0}
	var svalue zend.SmartStr = zend.SmartStr{0}
	var hname zend.SmartStr = zend.SmartStr{0}
	var hvalue zend.SmartStr = zend.SmartStr{0}
	var encoded *zend.ZendString
	var url_state *UrlAdaptStateExT
	var handler core.PhpOutputHandlerFuncT
	if type_ != 0 {
		url_state = &(BasicGlobals.GetUrlAdaptSessionEx())
		handler = PhpUrlScannerSessionHandler
	} else {
		url_state = &(BasicGlobals.GetUrlAdaptOutputEx())
		handler = PhpUrlScannerOutputHandler
	}
	if url_state.GetActive() == 0 {
		PhpUrlScannerExActivate(type_)
		core.PhpOutputStartInternal("URL-Rewriter", g.SizeOf("\"URL-Rewriter\"")-1, handler, 0, 0x70)
		url_state.SetActive(1)
	}
	if url_state.url_app.s != nil && url_state.url_app.s.len_ != 0 {
		zend.SmartStrAppendlEx(&url_state.url_app, core.CoreGlobals.arg_separator.output, strlen(core.CoreGlobals.arg_separator.output), 0)
	}
	if encode != 0 {
		encoded = PhpRawUrlEncode(name, name_len)
		zend.SmartStrAppendlEx(&sname, encoded.val, encoded.len_, 0)
		zend.ZendStringFree(encoded)
		encoded = PhpRawUrlEncode(value, value_len)
		zend.SmartStrAppendlEx(&svalue, encoded.val, encoded.len_, 0)
		zend.ZendStringFree(encoded)
		encoded = PhpEscapeHtmlEntitiesEx((*uint8)(name), name_len, 0, 2|1|8, core.sapi_globals.default_charset, 0)
		zend.SmartStrAppendlEx(&hname, encoded.val, encoded.len_, 0)
		zend.ZendStringFree(encoded)
		encoded = PhpEscapeHtmlEntitiesEx((*uint8)(value), value_len, 0, 2|1|8, core.sapi_globals.default_charset, 0)
		zend.SmartStrAppendlEx(&hvalue, encoded.val, encoded.len_, 0)
		zend.ZendStringFree(encoded)
	} else {
		zend.SmartStrAppendlEx(&sname, name, name_len, 0)
		zend.SmartStrAppendlEx(&svalue, value, value_len, 0)
		zend.SmartStrAppendlEx(&hname, name, name_len, 0)
		zend.SmartStrAppendlEx(&hvalue, value, value_len, 0)
	}
	zend.SmartStrAppendSmartStrEx(&url_state.url_app, &sname, 0)
	zend.SmartStrAppendcEx(&url_state.url_app, '=', 0)
	zend.SmartStrAppendSmartStrEx(&url_state.url_app, &svalue, 0)
	zend.SmartStrAppendlEx(&url_state.form_app, "<input type=\"hidden\" name=\"", strlen("<input type=\"hidden\" name=\""), 0)
	zend.SmartStrAppendSmartStrEx(&url_state.form_app, &hname, 0)
	zend.SmartStrAppendlEx(&url_state.form_app, "\" value=\"", strlen("\" value=\""), 0)
	zend.SmartStrAppendSmartStrEx(&url_state.form_app, &hvalue, 0)
	zend.SmartStrAppendlEx(&url_state.form_app, "\" />", strlen("\" />"), 0)
	zend.SmartStrFreeEx(&sname, 0)
	zend.SmartStrFreeEx(&svalue, 0)
	zend.SmartStrFreeEx(&hname, 0)
	zend.SmartStrFreeEx(&hvalue, 0)
	return zend.SUCCESS
}
func PhpUrlScannerAddSessionVar(name *byte, name_len int, value *byte, value_len int, encode int) int {
	return PhpUrlScannerAddVarImpl(name, name_len, value, value_len, encode, 1)
}
func PhpUrlScannerAddVar(name *byte, name_len int, value *byte, value_len int, encode int) int {
	return PhpUrlScannerAddVarImpl(name, name_len, value, value_len, encode, 0)
}
func PhpUrlScannerResetVarsImpl(type_ int) {
	var url_state *UrlAdaptStateExT
	if type_ != 0 {
		url_state = &(BasicGlobals.GetUrlAdaptSessionEx())
	} else {
		url_state = &(BasicGlobals.GetUrlAdaptOutputEx())
	}
	if url_state.form_app.s != nil {
		url_state.form_app.s.len_ = 0
	}
	if url_state.url_app.s != nil {
		url_state.url_app.s.len_ = 0
	}
}
func PhpUrlScannerResetSessionVars() int {
	PhpUrlScannerResetVarsImpl(1)
	return zend.SUCCESS
}
func PhpUrlScannerResetVars() int {
	PhpUrlScannerResetVarsImpl(0)
	return zend.SUCCESS
}
func PhpUrlScannerResetVarImpl(name *zend.ZendString, encode int, type_ int) int {
	var start *byte
	var end *byte
	var limit *byte
	var separator_len int
	var sname zend.SmartStr = zend.SmartStr{0}
	var hname zend.SmartStr = zend.SmartStr{0}
	var url_app zend.SmartStr = zend.SmartStr{0}
	var form_app zend.SmartStr = zend.SmartStr{0}
	var encoded *zend.ZendString
	var ret int = zend.SUCCESS
	var sep_removed zend.ZendBool = 0
	var url_state *UrlAdaptStateExT
	if type_ != 0 {
		url_state = &(BasicGlobals.GetUrlAdaptSessionEx())
	} else {
		url_state = &(BasicGlobals.GetUrlAdaptOutputEx())
	}

	/* Short circuit check. Only check url_app. */

	if url_state.url_app.s == nil || url_state.url_app.s.len_ == 0 {
		return zend.SUCCESS
	}
	if encode != 0 {
		encoded = PhpRawUrlEncode(name.val, name.len_)
		zend.SmartStrAppendlEx(&sname, encoded.val, encoded.len_, 0)
		zend.ZendStringFree(encoded)
		encoded = PhpEscapeHtmlEntitiesEx((*uint8)(name.val), name.len_, 0, 2|1|8, core.sapi_globals.default_charset, 0)
		zend.SmartStrAppendlEx(&hname, encoded.val, encoded.len_, 0)
		zend.ZendStringFree(encoded)
	} else {
		zend.SmartStrAppendlEx(&sname, name.val, name.len_, 0)
		zend.SmartStrAppendlEx(&hname, name.val, name.len_, 0)
	}
	zend.SmartStr0(&sname)
	zend.SmartStr0(&hname)
	zend.SmartStrAppendSmartStrEx(&url_app, &sname, 0)
	zend.SmartStrAppendcEx(&url_app, '=', 0)
	zend.SmartStr0(&url_app)
	zend.SmartStrAppendlEx(&form_app, "<input type=\"hidden\" name=\"", strlen("<input type=\"hidden\" name=\""), 0)
	zend.SmartStrAppendSmartStrEx(&form_app, &hname, 0)
	zend.SmartStrAppendlEx(&form_app, "\" value=\"", strlen("\" value=\""), 0)
	zend.SmartStr0(&form_app)

	/* Short circuit check. Only check url_app. */

	start = (*byte)(zend.ZendMemnstr(url_state.url_app.s.val, url_app.s.val, url_app.s.len_, url_state.url_app.s.val+url_state.url_app.s.len_))
	if start == nil {
		ret = zend.FAILURE
		goto finish
	}

	/* Get end of url var */

	limit = url_state.url_app.s.val + url_state.url_app.s.len_
	end = start + url_app.s.len_
	separator_len = strlen(core.CoreGlobals.arg_separator.output)
	for end < limit {
		if !(memcmp(end, core.CoreGlobals.arg_separator.output, separator_len)) {
			end += separator_len
			sep_removed = 1
			break
		}
		end++
	}

	/* Remove all when this is the only rewrite var */

	if url_state.url_app.s.len_ == end-start {
		PhpUrlScannerResetVarsImpl(type_)
		goto finish
	}

	/* Check preceding separator */

	if sep_removed == 0 && size_t(start-core.CoreGlobals.arg_separator.output) >= separator_len && !(memcmp(start-separator_len, core.CoreGlobals.arg_separator.output, separator_len)) {
		start -= separator_len
	}

	/* Remove partially */

	memmove(start, end, url_state.url_app.s.len_-(end-url_state.url_app.s.val))
	url_state.url_app.s.len_ -= end - start
	url_state.url_app.s.val[url_state.url_app.s.len_] = '0'

	/* Remove form var */

	start = (*byte)(zend.ZendMemnstr(url_state.form_app.s.val, form_app.s.val, form_app.s.len_, url_state.form_app.s.val+url_state.form_app.s.len_))
	if start == nil {

		/* Should not happen */

		ret = zend.FAILURE
		PhpUrlScannerResetVarsImpl(type_)
		goto finish
	}

	/* Get end of form var */

	limit = url_state.form_app.s.val + url_state.form_app.s.len_
	end = start + form_app.s.len_
	for end < limit {
		if (*end) == '>' {
			end += 1
			break
		}
		end++
	}

	/* Remove partially */

	memmove(start, end, url_state.form_app.s.len_-(end-url_state.form_app.s.val))
	url_state.form_app.s.len_ -= end - start
	url_state.form_app.s.val[url_state.form_app.s.len_] = '0'
finish:
	zend.SmartStrFreeEx(&url_app, 0)
	zend.SmartStrFreeEx(&form_app, 0)
	zend.SmartStrFreeEx(&sname, 0)
	zend.SmartStrFreeEx(&hname, 0)
	return ret
}
func PhpUrlScannerResetSessionVar(name *zend.ZendString, encode int) int {
	return PhpUrlScannerResetVarImpl(name, encode, 1)
}
func PhpUrlScannerResetVar(name *zend.ZendString, encode int) int {
	return PhpUrlScannerResetVarImpl(name, encode, 0)
}
func ZmStartupUrlScanner(type_ int, module_number int) int {
	zend.ZendRegisterIniEntries(IniEntries, module_number)
	return zend.SUCCESS
}
func ZmShutdownUrlScanner(type_ int, module_number int) int {
	zend.ZendUnregisterIniEntries(module_number)
	return zend.SUCCESS
}
func ZmActivateUrlScanner(type_ int, module_number int) int {
	BasicGlobals.GetUrlAdaptSessionEx().SetActive(0)
	BasicGlobals.GetUrlAdaptSessionEx().SetTagType(0)
	BasicGlobals.GetUrlAdaptSessionEx().SetAttrType(0)
	BasicGlobals.GetUrlAdaptOutputEx().SetActive(0)
	BasicGlobals.GetUrlAdaptOutputEx().SetTagType(0)
	BasicGlobals.GetUrlAdaptOutputEx().SetAttrType(0)
	return zend.SUCCESS
}
func ZmDeactivateUrlScanner(type_ int, module_number int) int {
	if BasicGlobals.GetUrlAdaptSessionEx().GetActive() != 0 {
		PhpUrlScannerExDeactivate(1)
		BasicGlobals.GetUrlAdaptSessionEx().SetActive(0)
		BasicGlobals.GetUrlAdaptSessionEx().SetTagType(0)
		BasicGlobals.GetUrlAdaptSessionEx().SetAttrType(0)
	}
	zend.SmartStrFreeEx(&(BasicGlobals.GetUrlAdaptSessionEx()).form_app, 0)
	zend.SmartStrFreeEx(&(BasicGlobals.GetUrlAdaptSessionEx()).url_app, 0)
	if BasicGlobals.GetUrlAdaptOutputEx().GetActive() != 0 {
		PhpUrlScannerExDeactivate(0)
		BasicGlobals.GetUrlAdaptOutputEx().SetActive(0)
		BasicGlobals.GetUrlAdaptOutputEx().SetTagType(0)
		BasicGlobals.GetUrlAdaptOutputEx().SetAttrType(0)
	}
	zend.SmartStrFreeEx(&(BasicGlobals.GetUrlAdaptOutputEx()).form_app, 0)
	zend.SmartStrFreeEx(&(BasicGlobals.GetUrlAdaptOutputEx()).url_app, 0)
	return zend.SUCCESS
}
