package standard

// Source: <ext/standard/url_scanner_ex.h>

/*
  +----------------------------------------------------------------------+
  | PHP Version 7                                                        |
  +----------------------------------------------------------------------+
  | Copyright (c) The PHP Group                                          |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author: Sascha Schumann <sascha@schumann.cx>                         |
  +----------------------------------------------------------------------+
*/

var ZmStartupUrlScannerEx func(type_ int, module_number int) int
var ZmShutdownUrlScannerEx func(type_ int, module_number int) int
var ZmActivateUrlScannerEx func(type_ int, module_number int) int
var ZmDeactivateUrlScannerEx func(type_ int, module_number int) int

// Source: <ext/standard/url_scanner_ex.c>

/* Generated by re2c 0.13.5 */

const UrlScanner = url_scanner_ex

/* FIXME: OnUpdate*Hosts cannot set default to $_SERVER['HTTP_HOST'] at startup */

const YYCURSOR []byte = p
const YYLIMIT []byte = q
const YYMARKER []byte = r
const (
	TAG_NORMAL = 0
	TAG_FORM
)
const (
	ATTR_NORMAL = 0
	ATTR_ACTION
)
const (
	STATE_PLAIN = 0
	STATE_TAG
	STATE_NEXT_ARG
	STATE_ARG
	STATE_BEFORE_VAL
	STATE_VAL
)

/*
 * This function appends a hidden input field after a <form>.
 */

/*
 *  HANDLE_TAG copies the HTML Tag and checks whether we
 *  have that tag in our table. If we might modify it,
 *  we continue to scan the tag, otherwise we simply copy the complete
 *  HTML stuff to the result buffer.
 */
