package standard

/* Generated by re2c 0.13.5 */

/* {{{ reference-handling for unserializer: var_* */

const VAR_ENTRIES_MAX = 1018
const VAR_DTOR_ENTRIES_MAX = 255
const VAR_ENTRIES_DBG = 0

/* VAR_FLAG used in var_dtor entries to signify an entry on which
 * __wakeup/__unserialize should be called */

const VAR_WAKEUP_FLAG = 1
const VAR_UNSERIALIZE_FLAG = 2

/* no need to check for length - re2c already did */
