// <<generate>>

package standard

// Source: <ext/standard/var_unserializer.c>

/* Generated by re2c 0.13.5 */

/* {{{ reference-handling for unserializer: var_* */

/* VAR_FLAG used in var_dtor entries to signify an entry on which
 * __wakeup/__unserialize should be called */

/* }}} */

/* no need to check for length - re2c already did */
