// <<generate>>

package standard

import (
	"sik/core"
	g "sik/runtime/grammar"
	"sik/zend"
)

// Source: <ext/standard/var_unserializer.c>

/* Generated by re2c 0.13.5 */

// # include "php.h"

// # include "ext/standard/php_var.h"

// # include "php_incomplete_class.h"

// # include "zend_portability.h"

/* {{{ reference-handling for unserializer: var_* */

// #define VAR_ENTRIES_MAX       1018

// #define VAR_DTOR_ENTRIES_MAX       255

// #define VAR_ENTRIES_DBG       0

/* VAR_FLAG used in var_dtor entries to signify an entry on which
 * __wakeup/__unserialize should be called */

// #define VAR_WAKEUP_FLAG       1

// #define VAR_UNSERIALIZE_FLAG       2

// @type VarEntries struct
// @type VarDtorEntries struct
// @type PhpUnserializeData struct
func PhpVarUnserializeInit() PhpUnserializeDataT {
	var d PhpUnserializeDataT

	/* fprintf(stderr, "UNSERIALIZE_INIT    == lock: %u, level: %u\n", BG(serialize_lock), BG(unserialize).level); */

	if BasicGlobals.GetSerializeLock() || !(BasicGlobals.GetUnserializeLevel()) {
		d = zend._emalloc(g.SizeOf("struct php_unserialize_data"))
		d.SetLast(&d.entries)
		d.SetLastDtor(nil)
		d.SetFirstDtor(d.GetLastDtor())
		d.SetAllowedClasses(nil)
		d.SetRefProps(nil)
		d.SetCurDepth(0)
		d.SetMaxDepth(BasicGlobals.GetUnserializeMaxDepth())
		d.GetEntries().SetUsedSlots(0)
		d.GetEntries().SetNext(nil)
		if !(BasicGlobals.GetSerializeLock()) {
			BasicGlobals.SetUnserializeData(d)
			BasicGlobals.SetUnserializeLevel(1)
		}
	} else {
		d = BasicGlobals.GetUnserializeData()
		BasicGlobals.GetUnserializeLevel()++
	}
	return d
}
func PhpVarUnserializeDestroy(d PhpUnserializeDataT) {
	/* fprintf(stderr, "UNSERIALIZE_DESTROY == lock: %u, level: %u\n", BG(serialize_lock), BG(unserialize).level); */

	if BasicGlobals.GetSerializeLock() || BasicGlobals.GetUnserializeLevel() == 1 {
		VarDestroy(&d)
		zend._efree(d)
	}
	if !(BasicGlobals.GetSerializeLock()) && !(g.PreDec(&(BasicGlobals.GetUnserializeLevel()))) {
		BasicGlobals.SetUnserializeData(nil)
	}
}
func PhpVarUnserializeGetAllowedClasses(d PhpUnserializeDataT) *zend.HashTable {
	return d.GetAllowedClasses()
}
func PhpVarUnserializeSetAllowedClasses(d PhpUnserializeDataT, classes *zend.HashTable) {
	d.SetAllowedClasses(classes)
}
func PhpVarUnserializeSetMaxDepth(d PhpUnserializeDataT, max_depth zend.ZendLong) {
	d.SetMaxDepth(max_depth)
}
func PhpVarUnserializeGetMaxDepth(d PhpUnserializeDataT) zend.ZendLong { return d.GetMaxDepth() }
func PhpVarUnserializeSetCurDepth(d PhpUnserializeDataT, cur_depth zend.ZendLong) {
	d.SetCurDepth(cur_depth)
}
func PhpVarUnserializeGetCurDepth(d PhpUnserializeDataT) zend.ZendLong { return d.GetCurDepth() }
func VarPush(var_hashx *PhpUnserializeDataT, rval *zend.Zval) {
	var var_hash *VarEntries = (*var_hashx).GetLast()
	if var_hash.GetUsedSlots() == 1018 {
		var_hash = zend._emalloc(g.SizeOf("var_entries"))
		var_hash.SetUsedSlots(0)
		var_hash.SetNext(0)
		(*var_hashx).GetLast().SetNext(var_hash)
		(*var_hashx).SetLast(var_hash)
	}
	var_hash.GetData()[g.PostInc(&(var_hash.GetUsedSlots()))] = rval
}
func VarPushDtor(var_hashx *PhpUnserializeDataT, rval *zend.Zval) {
	if rval.u1.v.type_flags != 0 {
		var tmp_var *zend.Zval = VarTmpVar(var_hashx)
		if tmp_var == nil {
			return
		}
		var _z1 *zend.Zval = tmp_var
		var _z2 *zend.Zval = rval
		var _gc *zend.ZendRefcounted = _z2.value.counted
		var _t uint32 = _z2.u1.type_info
		_z1.value.counted = _gc
		_z1.u1.type_info = _t
		if (_t & 0xff00) != 0 {
			zend.ZendGcAddref(&_gc.gc)
		}
	}
}
func TmpVar(var_hashx *PhpUnserializeDataT, num zend.ZendLong) *zend.Zval {
	var var_hash *VarDtorEntries
	var used_slots zend.ZendLong
	if var_hashx == nil || (*var_hashx) == nil || num < 1 {
		return nil
	}
	var_hash = (*var_hashx).GetLastDtor()
	if var_hash == nil || var_hash.GetUsedSlots()+num > 255 {
		var_hash = zend._emalloc(g.SizeOf("var_dtor_entries"))
		var_hash.SetUsedSlots(0)
		var_hash.SetNext(0)
		if (*var_hashx).GetFirstDtor() == nil {
			(*var_hashx).SetFirstDtor(var_hash)
		} else {
			(*var_hashx).GetLastDtor().SetNext(var_hash)
		}
		(*var_hashx).SetLastDtor(var_hash)
	}
	for used_slots = var_hash.GetUsedSlots(); var_hash.GetUsedSlots() < used_slots+num; var_hash.GetUsedSlots()++ {
		&var_hash.data[var_hash.GetUsedSlots()].u1.type_info = 0
		var_hash.GetData()[var_hash.GetUsedSlots()].u2.extra = 0
	}
	return &var_hash.data[used_slots]
}
func VarTmpVar(var_hashx *PhpUnserializeDataT) *zend.Zval { return TmpVar(var_hashx, 1) }
func VarReplace(var_hashx *PhpUnserializeDataT, ozval *zend.Zval, nzval *zend.Zval) {
	var i zend.ZendLong
	var var_hash *VarEntries = &(*var_hashx).entries
	for var_hash != nil {
		for i = 0; i < var_hash.GetUsedSlots(); i++ {
			if var_hash.GetData()[i] == ozval {
				var_hash.GetData()[i] = nzval
			}
		}
		var_hash = var_hash.GetNext()
	}
}
func VarAccess(var_hashx *PhpUnserializeDataT, id zend.ZendLong) *zend.Zval {
	var var_hash *VarEntries = &(*var_hashx).entries
	for id >= 1018 && var_hash != nil && var_hash.GetUsedSlots() == 1018 {
		var_hash = var_hash.GetNext()
		id -= 1018
	}
	if var_hash == nil {
		return nil
	}
	if id < 0 || id >= var_hash.GetUsedSlots() {
		return nil
	}
	return var_hash.GetData()[id]
}
func VarDestroy(var_hashx *PhpUnserializeDataT) {
	var next any
	var i zend.ZendLong
	var var_hash *VarEntries = (*var_hashx).GetEntries().GetNext()
	var var_dtor_hash *VarDtorEntries = (*var_hashx).GetFirstDtor()
	var delayed_call_failed zend.ZendBool = 0
	var wakeup_name zend.Zval
	var unserialize_name zend.Zval
	&wakeup_name.u1.type_info = 0
	&unserialize_name.u1.type_info = 0
	for var_hash != nil {
		next = var_hash.GetNext()
		zend._efree(var_hash)
		var_hash = next
	}
	for var_dtor_hash != nil {
		for i = 0; i < var_dtor_hash.GetUsedSlots(); i++ {
			var zv *zend.Zval = &var_dtor_hash.data[i]
			if zv.u2.extra == 1 {

				/* Perform delayed __wakeup calls */

				if delayed_call_failed == 0 {
					var retval zend.Zval
					if wakeup_name.u1.v.type_ == 0 {
						var __z *zend.Zval = &wakeup_name
						var __s *zend.ZendString = zend.ZendStringInit("__wakeup", g.SizeOf("\"__wakeup\"")-1, 0)
						__z.value.str = __s
						__z.u1.type_info = 6 | 1<<0<<8
					}
					BasicGlobals.GetSerializeLock()++
					if zend._callUserFunctionEx(zv, &wakeup_name, &retval, 0, 0, 1) == zend.FAILURE || retval.u1.v.type_ == 0 {
						delayed_call_failed = 1
						zv.value.obj.gc.u.type_info |= 1 << 8 << 0
					}
					BasicGlobals.GetSerializeLock()--
					zend.ZvalPtrDtor(&retval)
				} else {
					zv.value.obj.gc.u.type_info |= 1 << 8 << 0
				}

				/* Perform delayed __wakeup calls */

			} else if zv.u2.extra == 2 {

				/* Perform delayed __unserialize calls */

				if delayed_call_failed == 0 {
					var retval zend.Zval
					var param zend.Zval
					var _z1 *zend.Zval = &param
					var _z2 *zend.Zval = &var_dtor_hash.data[i+1]
					var _gc *zend.ZendRefcounted = _z2.value.counted
					var _t uint32 = _z2.u1.type_info
					_z1.value.counted = _gc
					_z1.u1.type_info = _t
					if (_t & 0xff00) != 0 {
						zend.ZendGcAddref(&_gc.gc)
					}
					if unserialize_name.u1.v.type_ == 0 {
						var __z *zend.Zval = &unserialize_name
						var __s *zend.ZendString = zend.ZendStringInit("__unserialize", g.SizeOf("\"__unserialize\"")-1, 0)
						__z.value.str = __s
						__z.u1.type_info = 6 | 1<<0<<8
					}
					BasicGlobals.GetSerializeLock()++
					if zend._callUserFunctionEx(zv, &unserialize_name, &retval, 1, &param, 1) == zend.FAILURE || retval.u1.v.type_ == 0 {
						delayed_call_failed = 1
						zv.value.obj.gc.u.type_info |= 1 << 8 << 0
					}
					BasicGlobals.GetSerializeLock()--
					zend.ZvalPtrDtor(&param)
					zend.ZvalPtrDtor(&retval)
				} else {
					zv.value.obj.gc.u.type_info |= 1 << 8 << 0
				}

				/* Perform delayed __unserialize calls */

			}
			zend.IZvalPtrDtor(zv)
		}
		next = var_dtor_hash.GetNext()
		zend._efree(var_dtor_hash)
		var_dtor_hash = next
	}
	zend.ZvalPtrDtorNogc(&wakeup_name)
	zend.ZvalPtrDtorNogc(&unserialize_name)
	if (*var_hashx).GetRefProps() != nil {
		zend.ZendHashDestroy((*var_hashx).GetRefProps())
		zend._efree((*var_hashx).GetRefProps())
	}
}

/* }}} */

func UnserializeStr(p **uint8, len_ int, maxlen int) *zend.ZendString {
	var i int
	var j int
	var str *zend.ZendString = zend.ZendStringSafeAlloc(1, len_, 0, 0)
	var end *uint8 = *((**uint8)(p + maxlen))
	if end < (*p) {
		zend.ZendStringEfree(str)
		return nil
	}
	for i = 0; i < len_; i++ {
		if (*p) >= end {
			zend.ZendStringEfree(str)
			return nil
		}
		if (*(*p)) != '\\' {
			str.val[i] = byte(*(*p))
		} else {
			var ch uint8 = 0
			for j = 0; j < 2; j++ {
				*p++
				if (*(*p)) >= '0' && (*(*p)) <= '9' {
					ch = (ch << 4) + ((*(*p)) - '0')
				} else if (*(*p)) >= 'a' && (*(*p)) <= 'f' {
					ch = (ch << 4) + ((*(*p)) - 'a' + 10)
				} else if (*(*p)) >= 'A' && (*(*p)) <= 'F' {
					ch = (ch << 4) + ((*(*p)) - 'A' + 10)
				} else {
					zend.ZendStringEfree(str)
					return nil
				}
			}
			str.val[i] = byte(ch)
		}
		*p++
	}
	str.val[i] = 0
	str.len_ = i
	return str
}
func UnserializeAllowedClass(class_name *zend.ZendString, var_hashx *PhpUnserializeDataT) int {
	var classes *zend.HashTable = (*var_hashx).GetAllowedClasses()
	var lcname *zend.ZendString
	var res int
	if classes == nil {
		return 1
	}
	if classes.nNumOfElements == 0 {
		return 0
	}
	lcname = (*zend.ZendString)(zend._emalloc(zend_long((*byte)(&((*zend.ZendString)(nil).val))-(*byte)(nil)) + class_name.len_ + 1 + (8-1) & ^(8-1)))
	zend.ZendGcSetRefcount(&lcname.gc, 1)
	lcname.gc.u.type_info = 6
	lcname.h = 0
	lcname.len_ = class_name.len_
	zend.ZendStrTolowerCopy(lcname.val, class_name.val, class_name.len_)
	res = zend.ZendHashExists(classes, lcname)
	zend._efree(lcname)
	return res
}

// #define YYFILL(n) do { } while ( 0 )

// #define YYCTYPE       unsigned char

// #define YYCURSOR       cursor

// #define YYLIMIT       limit

// #define YYMARKER       marker

func ParseIv2(p *uint8, q **uint8) zend.ZendLong {
	var result zend.ZendUlong = 0
	var neg zend.ZendUlong = 0
	var start *uint8
	if (*p) == '-' {
		neg = 1
		p++
	} else if (*p) == '+' {
		p++
	}
	for (*p) == '0' {
		p++
	}
	start = p
	for (*p) >= '0' && (*p) <= '9' {
		result = result*10 + (zend_ulong(*p) - '0')
		p++
	}
	if q != nil {
		*q = p
	}

	/* number too long or overflow */

	if p-start > 20-1 || result > INT64_MAX+neg {
		core.PhpErrorDocref(nil, 1<<1, "Numerical result out of range")
		if neg == 0 {
			return INT64_MAX
		} else {
			return INT64_MIN
		}
	}
	return zend_long(g.Cond(neg == 0, result, -result))
}
func ParseIv(p *uint8) zend.ZendLong { return ParseIv2(p, nil) }

/* no need to check for length - re2c already did */

func ParseUiv(p *uint8) int {
	var cursor uint8
	var result int = 0
	for true {
		cursor = *p
		if cursor >= '0' && cursor <= '9' {
			result = result*10 + size_t(cursor-uint8('0'))
		} else {
			break
		}
		p++
	}
	return result
}

// #define UNSERIALIZE_PARAMETER       zval * rval , const unsigned char * * p , const unsigned char * max , php_unserialize_data_t * var_hash

// #define UNSERIALIZE_PASSTHRU       rval , p , max , var_hash

func ProcessNestedData(rval *zend.Zval, p **uint8, max *uint8, var_hash *PhpUnserializeDataT, ht *zend.HashTable, elements zend.ZendLong, obj *zend.ZendObject) int {
	if var_hash != nil {
		if (*var_hash).GetMaxDepth() > 0 && (*var_hash).GetCurDepth() >= (*var_hash).GetMaxDepth() {
			core.PhpErrorDocref(nil, 1<<1, "Maximum depth of "+"%"+"lld"+" exceeded. "+"The depth limit can be changed using the max_depth unserialize() option "+"or the unserialize_max_depth ini setting", (*var_hash).GetMaxDepth())
			return 0
		}
		(*var_hash).GetCurDepth()++
	}
	for g.PostDec(&elements) > 0 {
		var key zend.Zval
		var data *zend.Zval
		var d zend.Zval
		var old_data *zend.Zval
		var idx zend.ZendUlong
		var info *zend.ZendPropertyInfo = nil
		&key.u1.type_info = 0
		if PhpVarUnserializeInternal(&key, p, max, nil, 1) == 0 {
			zend.ZvalPtrDtor(&key)
			goto failure
		}
		data = nil
		&d.u1.type_info = 0
		if obj == nil {
			if key.u1.v.type_ == 4 {
				idx = key.value.lval
			numeric_key:
				if g.Assign(&old_data, zend.ZendHashIndexFind(ht, idx)) != nil {

					//??? update hash

					VarPushDtor(var_hash, old_data)
					data = zend.ZendHashIndexUpdate(ht, idx, &d)
				} else {
					data = zend.ZendHashIndexAddNew(ht, idx, &d)
				}
			} else if key.u1.v.type_ == 6 {
				if zend._zendHandleNumericStr(key.value.str.val, key.value.str.len_, &idx) != 0 {
					goto numeric_key
				}
				if g.Assign(&old_data, zend.ZendHashFind(ht, key.value.str)) != nil {

					//??? update hash

					VarPushDtor(var_hash, old_data)
					data = zend.ZendHashUpdate(ht, key.value.str, &d)
				} else {
					data = zend.ZendHashAddNew(ht, key.value.str, &d)
				}
			} else {
				zend.ZvalPtrDtor(&key)
				goto failure
			}
		} else {
			if key.u1.v.type_ == 6 {
			string_key:
				if obj != nil && &obj.ce.properties_info.nNumOfElements > 0 {
					var existing_propinfo *zend.ZendPropertyInfo
					var new_key *zend.ZendString
					var unmangled_class *byte = nil
					var unmangled_prop *byte
					var unmangled_prop_len int
					var unmangled *zend.ZendString
					if zend.ZendUnmanglePropertyNameEx(key.value.str, &unmangled_class, &unmangled_prop, &unmangled_prop_len) == zend.FAILURE {
						zend.ZvalPtrDtor(&key)
						goto failure
					}
					unmangled = zend.ZendStringInit(unmangled_prop, unmangled_prop_len, 0)
					existing_propinfo = zend.ZendHashFindPtr(&obj.ce.properties_info, unmangled)
					if (unmangled_class == nil || !(strcmp(unmangled_class, "*")) || !(strcasecmp(unmangled_class, obj.ce.name.val))) && existing_propinfo != nil && (existing_propinfo.flags&(1<<0|1<<1|1<<2)) != 0 {
						if (existing_propinfo.flags & 1 << 1) != 0 {
							new_key = zend.ZendManglePropertyName("*", 1, unmangled.val, unmangled.len_, 0)
							zend.ZendStringReleaseEx(unmangled, 0)
						} else if (existing_propinfo.flags & 1 << 2) != 0 {
							if unmangled_class != nil && strcmp(unmangled_class, "*") != 0 {
								new_key = zend.ZendManglePropertyName(unmangled_class, strlen(unmangled_class), unmangled.val, unmangled.len_, 0)
							} else {
								new_key = zend.ZendManglePropertyName(existing_propinfo.ce.name.val, existing_propinfo.ce.name.len_, unmangled.val, unmangled.len_, 0)
							}
							zend.ZendStringReleaseEx(unmangled, 0)
						} else {
							assert((existing_propinfo.flags & 1 << 0) != 0)
							new_key = unmangled
						}
						zend.ZvalPtrDtorStr(&key)
						var __z *zend.Zval = &key
						var __s *zend.ZendString = new_key
						__z.value.str = __s
						if (zend.ZvalGcFlags(__s.gc.u.type_info) & 1 << 6) != 0 {
							__z.u1.type_info = 6
						} else {
							__z.u1.type_info = 6 | 1<<0<<8
						}
					} else {
						zend.ZendStringReleaseEx(unmangled, 0)
					}
				}
				if g.Assign(&old_data, zend.ZendHashFind(ht, key.value.str)) != nil {
					if old_data.u1.v.type_ == 13 {
						old_data = old_data.value.zv
						info = zend.ZendGetTypedPropertyInfoForSlot(obj, old_data)
						VarPushDtor(var_hash, old_data)
						data = zend.ZendHashUpdateInd(ht, key.value.str, &d)
						if info != nil {

							/* Remember to which property this slot belongs, so we can add a
							 * type source if it is turned into a reference lateron. */

							if (*var_hash).GetRefProps() == nil {
								(*var_hash).SetRefProps(zend._emalloc(g.SizeOf("HashTable")))
								zend._zendHashInit((*var_hash).GetRefProps(), 8, nil, 0)
							}
							zend.ZendHashIndexUpdatePtr((*var_hash).GetRefProps(), zend.ZendUintptrT(data), info)
						}
					} else {
						VarPushDtor(var_hash, old_data)
						data = zend.ZendHashUpdateInd(ht, key.value.str, &d)
					}
				} else {
					data = zend.ZendHashAddNew(ht, key.value.str, &d)
				}
			} else if key.u1.v.type_ == 4 {

				/* object properties should include no integers */

				if &key.u1.v.type_ != 6 {
					zend._convertToString(&key)
				}
				goto string_key
			} else {
				zend.ZvalPtrDtor(&key)
				goto failure
			}
		}
		if PhpVarUnserializeInternal(data, p, max, var_hash, 0) == 0 {
			zend.ZvalPtrDtor(&key)
			goto failure
		}
		if info != nil {
			if zend.ZendVerifyPropAssignableByRef(info, data, 1) == 0 {
				zend.ZvalPtrDtor(data)
				data.u1.type_info = 0
				zend.ZvalPtrDtorNogc(&key)
				goto failure
			}
			if data.u1.v.type_ == 10 {
				zend.ZendRefAddTypeSource(&(data.value.ref).sources, info)
			}
		}
		if BasicGlobals.GetUnserializeLevel() > 1 {
			VarPushDtor(var_hash, data)
		}
		zend.ZvalPtrDtorStr(&key)
		if elements != 0 && (*((*p) - 1)) != ';' && (*((*p) - 1)) != '}' {
			*p--
			goto failure
		}
	}
	if var_hash != nil {
		(*var_hash).GetCurDepth()--
	}
	return 1
failure:
	if var_hash != nil {
		(*var_hash).GetCurDepth()--
	}
	return 0
}
func FinishNestedData(rval *zend.Zval, p **uint8, max *uint8, var_hash *PhpUnserializeDataT) int {
	if (*p) >= max || (*(*p)) != '}' {
		return 0
	}
	*p++
	return 1
}
func ObjectCustom(rval *zend.Zval, p **uint8, max *uint8, var_hash *PhpUnserializeDataT, ce *zend.ZendClassEntry) int {
	var datalen zend.ZendLong
	datalen = ParseIv2((*p)+2, p)
	*p += 2
	if datalen < 0 || max-(*p) <= datalen {
		zend.ZendError(1<<1, "Insufficient data for unserializing - "+"%"+"lld"+" required, "+"%"+"lld"+" present", datalen, zend_long(max-(*p)))
		return 0
	}

	/* Check that '}' is present before calling ce->unserialize() to mitigate issues
	 * with unserialize reading past the end of the passed buffer if the string is not
	 * appropriately terminated (usually NUL terminated, but '}' is also sufficient.) */

	if (*p)[datalen] != '}' {
		return 0
	}
	if ce.unserialize == nil {
		zend.ZendError(1<<1, "Class %s has no unserializer", ce.name.val)
		zend.ObjectInitEx(rval, ce)
	} else if ce.unserialize(rval, ce, (*uint8)(*p), datalen, (*zend.ZendUnserializeData)(var_hash)) != zend.SUCCESS {
		return 0
	}
	*p += datalen + 1
	return 1
}
func ObjectCommon(rval *zend.Zval, p **uint8, max *uint8, var_hash *PhpUnserializeDataT, elements zend.ZendLong, has_unserialize zend.ZendBool) int {
	var ht *zend.HashTable
	var has_wakeup zend.ZendBool
	if has_unserialize != 0 {
		var ary zend.Zval
		var tmp *zend.Zval
		if elements >= 0x80000000 {
			return 0
		}
		var __arr *zend.ZendArray = zend._zendNewArray(elements)
		var __z *zend.Zval = &ary
		__z.value.arr = __arr
		__z.u1.type_info = 7 | 1<<0<<8 | 1<<1<<8

		/* Avoid reallocation due to packed -> mixed conversion. */

		zend.ZendHashRealInitMixed(ary.value.arr)
		if ProcessNestedData(rval, p, max, var_hash, ary.value.arr, elements, nil) == 0 {
			if rval.u1.v.type_ == 10 {
				rval = &(*rval).value.ref.val
			}
			rval.value.obj.gc.u.type_info |= 1 << 8 << 0
			zend.ZvalPtrDtor(&ary)
			return 0
		}

		/* Delay __unserialize() call until end of serialization. We use two slots here to
		 * store both the object and the unserialized data array. */

		if rval.u1.v.type_ == 10 {
			rval = &(*rval).value.ref.val
		}
		tmp = TmpVar(var_hash, 2)
		var _z1 *zend.Zval = tmp
		var _z2 *zend.Zval = rval
		var _gc *zend.ZendRefcounted = _z2.value.counted
		var _t uint32 = _z2.u1.type_info
		_z1.value.counted = _gc
		_z1.u1.type_info = _t
		if (_t & 0xff00) != 0 {
			zend.ZendGcAddref(&_gc.gc)
		}
		tmp.u2.extra = 2
		tmp++
		var _z1 *zend.Zval = tmp
		var _z2 *zend.Zval = &ary
		var _gc *zend.ZendRefcounted = _z2.value.counted
		var _t uint32 = _z2.u1.type_info
		_z1.value.counted = _gc
		_z1.u1.type_info = _t
		return FinishNestedData(rval, p, max, var_hash)
	}
	has_wakeup = rval.value.obj.ce != BasicGlobals.GetIncompleteClass() && zend.ZendHashStrExists(&(rval.value.obj.ce).function_table, "__wakeup", g.SizeOf("\"__wakeup\"")-1) != 0
	ht = rval.value.obj.handlers.get_properties(&(*rval))
	if elements >= zend_long(0x80000000-ht.nNumOfElements) {
		return 0
	}
	zend.ZendHashExtend(ht, ht.nNumOfElements+elements, ht.u.flags&1<<2)
	if ProcessNestedData(rval, p, max, var_hash, ht, elements, rval.value.obj) == 0 {
		if has_wakeup != 0 {
			if rval.u1.v.type_ == 10 {
				rval = &(*rval).value.ref.val
			}
			rval.value.obj.gc.u.type_info |= 1 << 8 << 0
		}
		return 0
	}
	if rval.u1.v.type_ == 10 {
		rval = &(*rval).value.ref.val
	}
	if has_wakeup != 0 {

		/* Delay __wakeup call until end of serialization */

		var wakeup_var *zend.Zval = VarTmpVar(var_hash)
		var _z1 *zend.Zval = wakeup_var
		var _z2 *zend.Zval = rval
		var _gc *zend.ZendRefcounted = _z2.value.counted
		var _t uint32 = _z2.u1.type_info
		_z1.value.counted = _gc
		_z1.u1.type_info = _t
		if (_t & 0xff00) != 0 {
			zend.ZendGcAddref(&_gc.gc)
		}
		wakeup_var.u2.extra = 1
	}
	return FinishNestedData(rval, p, max, var_hash)
}
func PhpVarUnserialize(rval *zend.Zval, p **uint8, max *uint8, var_hash *PhpUnserializeDataT) int {
	var orig_var_entries *VarEntries = (*var_hash).GetLast()
	var orig_used_slots zend.ZendLong = g.CondF1(orig_var_entries != nil, func() zend.ZendLong { return orig_var_entries.GetUsedSlots() }, 0)
	var result int
	result = PhpVarUnserializeInternal(rval, p, max, var_hash, 0)
	if result == 0 {

		/* If the unserialization failed, mark all elements that have been added to var_hash
		 * as NULL. This will forbid their use by other unserialize() calls in the same
		 * unserialization context. */

		var e *VarEntries = orig_var_entries
		var s zend.ZendLong = orig_used_slots
		for e != nil {
			for ; s < e.GetUsedSlots(); s++ {
				e.GetData()[s] = nil
			}
			e = e.GetNext()
			s = 0
		}
	}
	return result
}
func PhpVarUnserializeInternal(rval *zend.Zval, p **uint8, max *uint8, var_hash *PhpUnserializeDataT, as_key int) int {
	var cursor *uint8
	var limit *uint8
	var marker *uint8
	var start *uint8
	var rval_ref *zend.Zval
	limit = max
	cursor = *p
	if cursor >= limit {
		return 0
	}
	if var_hash != nil && (*p)[0] != 'R' {
		VarPush(var_hash, rval)
	}
	start = cursor
	var yych uint8
	var yybm []uint8 = []uint8{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	if limit-cursor < 7 {

	}
	yych = *cursor
	if yych <= 'a' {
		if yych <= 'O' {
			if yych <= 'C' {
				if yych <= 'B' {
					goto yy15
				}
				goto yy12
			} else {
				if yych <= 'M' {
					goto yy15
				}
				if yych <= 'N' {
					goto yy5
				}
				goto yy12
			}
		} else {
			if yych <= 'R' {
				if yych <= 'Q' {
					goto yy15
				}
			} else {
				if yych <= 'S' {
					goto yy10
				}
				if yych <= '`' {
					goto yy15
				}
				goto yy11
			}
		}
	} else {
		if yych <= 'i' {
			if yych <= 'c' {
				if yych <= 'b' {
					goto yy6
				}
				goto yy15
			} else {
				if yych <= 'd' {
					goto yy8
				}
				if yych <= 'h' {
					goto yy15
				}
				goto yy7
			}
		} else {
			if yych <= 's' {
				if yych <= 'q' {
					goto yy15
				}
				if yych <= 'r' {
					goto yy4
				}
				goto yy9
			} else {
				if yych == '}' {
					goto yy13
				}
				goto yy15
			}
		}
	}
	yych = *(g.Assign(&marker, g.PreInc(&cursor)))
	if yych == ':' {
		goto yy84
	}
yy3:
	return 0
yy4:
	yych = *(g.Assign(&marker, g.PreInc(&cursor)))
	if yych == ':' {
		goto yy79
	}
	goto yy3
yy5:
	yych = *(g.PreInc(&cursor))
	if yych == ';' {
		goto yy77
	}
	goto yy3
yy6:
	yych = *(g.Assign(&marker, g.PreInc(&cursor)))
	if yych == ':' {
		goto yy70
	}
	goto yy3
yy7:
	yych = *(g.Assign(&marker, g.PreInc(&cursor)))
	if yych == ':' {
		goto yy64
	}
	goto yy3
yy8:
	yych = *(g.Assign(&marker, g.PreInc(&cursor)))
	if yych == ':' {
		goto yy41
	}
	goto yy3
yy9:
	yych = *(g.Assign(&marker, g.PreInc(&cursor)))
	if yych == ':' {
		goto yy35
	}
	goto yy3
yy10:
	yych = *(g.Assign(&marker, g.PreInc(&cursor)))
	if yych == ':' {
		goto yy29
	}
	goto yy3
yy11:
	yych = *(g.Assign(&marker, g.PreInc(&cursor)))
	if yych == ':' {
		goto yy23
	}
	goto yy3
yy12:
	yych = *(g.Assign(&marker, g.PreInc(&cursor)))
	if yych == ':' {
		goto yy16
	}
	goto yy3
yy13:
	cursor++

	/* this is the case where we have less data than planned */

	core.PhpErrorDocref(nil, 1<<3, "Unexpected end of serialized data")
	return 0
yy15:
	yych = *(g.PreInc(&cursor))
	goto yy3
yy16:
	yych = *(g.PreInc(&cursor))
	if (yybm[0+yych] & 128) != 0 {
		goto yy18
	}
yy17:
	cursor = marker
	goto yy3
yy18:
	cursor++
	if limit-cursor < 2 {

	}
	yych = *cursor
	if (yybm[0+yych] & 128) != 0 {
		goto yy18
	}
	if yych != ':' {
		goto yy17
	}
	yych = *(g.PreInc(&cursor))
	if yych != '"' {
		goto yy17
	}
	cursor++
	var len int
	var len2 int
	var len3 int
	var maxlen int
	var elements zend_long
	var str *byte
	var class_name *zend.ZendString
	var ce *zend.ZendClassEntry
	var incomplete_class zend.ZendBool = 0
	var custom_object zend.ZendBool = 0
	var has_unserialize zend.ZendBool = 0
	var user_func zend.Zval
	var retval zend.Zval
	var args []zend.Zval
	if var_hash == nil {
		return 0
	}
	if (*start) == 'C' {
		custom_object = 1
	}
	len_ = ParseUiv(start + 2)
	len2 = len_
	maxlen = max - cursor
	if maxlen < len_ || len_ == 0 {
		*p = start + 2
		return 0
	}
	str = (*byte)(cursor)
	cursor += len_
	if (*cursor) != '"' {
		*p = cursor
		return 0
	}
	if (*(cursor + 1)) != ':' {
		*p = cursor + 1
		return 0
	}
	len3 = strspn(str, "0123456789_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ177200201202203204205206207210211212213214215216217220221222223224225226227230231232233234235236237240241242243244245246247250251252253254255256257260261262263264265266267270271272273274275276277300301302303304305306307310311312313314315316317320321322323324325326327330331332333334335336337340341342343344345346347350351352353354355356357360361362363364365366367370371372373374375376377\\")
	if len3 != len_ {
		*p = cursor + len3 - len_
		return 0
	}
	class_name = zend.ZendStringInit(str, len_, 0)
	for {
		if UnserializeAllowedClass(class_name, var_hash) == 0 {
			incomplete_class = 1
			ce = BasicGlobals.GetIncompleteClass()
			break
		}

		/* Try to find class directly */

		BasicGlobals.GetSerializeLock()++
		ce = zend.ZendLookupClass(class_name)
		if ce != nil {
			BasicGlobals.GetSerializeLock()--
			if zend.EG.exception != nil {
				zend.ZendStringReleaseEx(class_name, 0)
				return 0
			}
			break
		}
		BasicGlobals.GetSerializeLock()--
		if zend.EG.exception != nil {
			zend.ZendStringReleaseEx(class_name, 0)
			return 0
		}

		/* Check for unserialize callback */

		if core.CoreGlobals.unserialize_callback_func == nil || core.CoreGlobals.unserialize_callback_func[0] == '0' {
			incomplete_class = 1
			ce = BasicGlobals.GetIncompleteClass()
			break
		}

		/* Call unserialize callback */

		var _s *byte = core.CoreGlobals.unserialize_callback_func
		var __z *zend.Zval = &user_func
		var __s *zend.ZendString = zend.ZendStringInit(_s, strlen(_s), 0)
		__z.value.str = __s
		__z.u1.type_info = 6 | 1<<0<<8
		var __z *zend.Zval = &args[0]
		var __s *zend.ZendString = class_name
		__z.value.str = __s
		if (zend.ZvalGcFlags(__s.gc.u.type_info) & 1 << 6) != 0 {
			__z.u1.type_info = 6
		} else {
			zend.ZendGcAddref(&__s.gc)
			__z.u1.type_info = 6 | 1<<0<<8
		}
		BasicGlobals.GetSerializeLock()++
		if zend._callUserFunctionEx(nil, &user_func, &retval, 1, args, 0) != zend.SUCCESS {
			BasicGlobals.GetSerializeLock()--
			if zend.EG.exception != nil {
				zend.ZendStringReleaseEx(class_name, 0)
				zend.ZvalPtrDtor(&user_func)
				zend.ZvalPtrDtor(&args[0])
				return 0
			}
			core.PhpErrorDocref(nil, 1<<1, "defined (%s) but not found", user_func.value.str.val)
			incomplete_class = 1
			ce = BasicGlobals.GetIncompleteClass()
			zend.ZvalPtrDtor(&user_func)
			zend.ZvalPtrDtor(&args[0])
			break
		}
		BasicGlobals.GetSerializeLock()--
		zend.ZvalPtrDtor(&retval)
		if zend.EG.exception != nil {
			zend.ZendStringReleaseEx(class_name, 0)
			zend.ZvalPtrDtor(&user_func)
			zend.ZvalPtrDtor(&args[0])
			return 0
		}

		/* The callback function may have defined the class */

		BasicGlobals.GetSerializeLock()++
		if g.Assign(&ce, zend.ZendLookupClass(class_name)) == nil {
			core.PhpErrorDocref(nil, 1<<1, "Function %s() hasn't defined the class it was called for", user_func.value.str.val)
			incomplete_class = 1
			ce = BasicGlobals.GetIncompleteClass()
		}
		BasicGlobals.GetSerializeLock()--
		zend.ZvalPtrDtor(&user_func)
		zend.ZvalPtrDtor(&args[0])
		break

	}
	*p = cursor
	if custom_object != 0 {
		var ret int
		ret = ObjectCustom(rval, p, max, var_hash, ce)
		if ret != 0 && incomplete_class != 0 {
			PhpStoreClassName(rval, class_name.val, len2)
		}
		zend.ZendStringReleaseEx(class_name, 0)
		return ret
	}
	if (*p) >= max-2 {
		zend.ZendError(1<<1, "Bad unserialize data")
		zend.ZendStringReleaseEx(class_name, 0)
		return 0
	}
	elements = ParseIv2((*p)+2, p)
	if elements < 0 || elements > max-cursor {
		zend.ZendStringReleaseEx(class_name, 0)
		return 0
	}
	*p += 2
	has_unserialize = incomplete_class == 0 && zend.ZendHashStrExists(&ce.function_table, "__unserialize", g.SizeOf("\"__unserialize\"")-1) != 0

	/* If this class implements Serializable, it should not land here but in object_custom().
	 * The passed string obviously doesn't descend from the regular serializer. However, if
	 * there is both Serializable::unserialize() and __unserialize(), then both may be used,
	 * depending on the serialization format. */

	if ce.serialize != nil && has_unserialize == 0 {
		zend.ZendError(1<<1, "Erroneous data format for unserializing '%s'", ce.name.val)
		zend.ZendStringReleaseEx(class_name, 0)
		return 0
	}
	if zend.ObjectInitEx(rval, ce) == zend.FAILURE {
		zend.ZendStringReleaseEx(class_name, 0)
		return 0
	}
	if incomplete_class != 0 {
		PhpStoreClassName(rval, class_name.val, len2)
	}
	zend.ZendStringReleaseEx(class_name, 0)
	return ObjectCommon(rval, p, max, var_hash, elements, has_unserialize)
yy23:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		goto yy17
	}
	if yych >= ':' {
		goto yy17
	}
yy24:
	cursor++
	if limit-cursor < 2 {

	}
	yych = *cursor
	if yych <= '/' {
		goto yy17
	}
	if yych <= '9' {
		goto yy24
	}
	if yych >= ';' {
		goto yy17
	}
	yych = *(g.PreInc(&cursor))
	if yych != '{' {
		goto yy17
	}
	cursor++
	var elements zend.ZendLong = ParseIv(start + 2)

	/* use iv() not uiv() in order to check data range */

	*p = cursor
	if var_hash == nil {
		return 0
	}
	if elements < 0 || elements >= 0x80000000 || elements > max-cursor {
		return 0
	}
	if elements != 0 {
		var __arr *zend.ZendArray = zend._zendNewArray(elements)
		var __z *zend.Zval = rval
		__z.value.arr = __arr
		__z.u1.type_info = 7 | 1<<0<<8 | 1<<1<<8

		/* we can't convert from packed to hash during unserialization, because
		   reference to some zvals might be keept in var_hash (to support references) */

		zend.ZendHashRealInitMixed(rval.value.arr)

		/* we can't convert from packed to hash during unserialization, because
		   reference to some zvals might be keept in var_hash (to support references) */

	} else {
		var __z *zend.Zval = rval
		__z.value.arr = (*zend.ZendArray)(&zend.ZendEmptyArray)
		__z.u1.type_info = 7
		return FinishNestedData(rval, p, max, var_hash)
	}

	/* The array may contain references to itself, in which case we'll be modifying an
	 * rc>1 array. This is okay, since the array is, ostensibly, only visible to
	 * unserialize (in practice unserialization handlers also see it). Ideally we should
	 * prohibit "r:" references to non-objects, as we only generate them for objects. */

	if ProcessNestedData(rval, p, max, var_hash, rval.value.arr, elements, nil) == 0 {
		return 0
	}
	return FinishNestedData(rval, p, max, var_hash)
yy29:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		goto yy17
	}
	if yych >= ':' {
		goto yy17
	}
yy30:
	cursor++
	if limit-cursor < 2 {

	}
	yych = *cursor
	if yych <= '/' {
		goto yy17
	}
	if yych <= '9' {
		goto yy30
	}
	if yych >= ';' {
		goto yy17
	}
	yych = *(g.PreInc(&cursor))
	if yych != '"' {
		goto yy17
	}
	cursor++
	var len int
	var maxlen int
	var str *zend_string
	len_ = ParseUiv(start + 2)
	maxlen = max - cursor
	if maxlen < len_ {
		*p = start + 2
		return 0
	}
	if g.Assign(&str, UnserializeStr(&cursor, len_, maxlen)) == nil {
		return 0
	}
	if (*cursor) != '"' {
		zend.ZendStringEfree(str)
		*p = cursor
		return 0
	}
	if (*(cursor + 1)) != ';' {
		zend._efree(str)
		*p = cursor + 1
		return 0
	}
	cursor += 2
	*p = cursor
	var __z *zend.Zval = rval
	var __s *zend.ZendString = str
	__z.value.str = __s
	if (zend.ZvalGcFlags(__s.gc.u.type_info) & 1 << 6) != 0 {
		__z.u1.type_info = 6
	} else {
		__z.u1.type_info = 6 | 1<<0<<8
	}
	return 1
yy35:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		goto yy17
	}
	if yych >= ':' {
		goto yy17
	}
yy36:
	cursor++
	if limit-cursor < 2 {

	}
	yych = *cursor
	if yych <= '/' {
		goto yy17
	}
	if yych <= '9' {
		goto yy36
	}
	if yych >= ';' {
		goto yy17
	}
	yych = *(g.PreInc(&cursor))
	if yych != '"' {
		goto yy17
	}
	cursor++
	var len_ int
	var maxlen int
	var str *byte
	len_ = ParseUiv(start + 2)
	maxlen = max - cursor
	if maxlen < len_ {
		*p = start + 2
		return 0
	}
	str = (*byte)(cursor)
	cursor += len_
	if (*cursor) != '"' {
		*p = cursor
		return 0
	}
	if (*(cursor + 1)) != ';' {
		*p = cursor + 1
		return 0
	}
	cursor += 2
	*p = cursor
	if len_ == 0 {
		var __z *zend.Zval = rval
		var __s *zend.ZendString = zend.ZendEmptyString
		__z.value.str = __s
		__z.u1.type_info = 6
	} else if len_ == 1 {
		var __z *zend.Zval = rval
		var __s *zend.ZendString = zend.ZendOneCharString[zend_uchar*str]
		__z.value.str = __s
		__z.u1.type_info = 6
	} else if as_key != 0 {
		var __z *zend.Zval = rval
		var __s *zend.ZendString = zend.ZendStringInitInterned(str, len_, 0)
		__z.value.str = __s
		if (zend.ZvalGcFlags(__s.gc.u.type_info) & 1 << 6) != 0 {
			__z.u1.type_info = 6
		} else {
			__z.u1.type_info = 6 | 1<<0<<8
		}
	} else {
		var __z *zend.Zval = rval
		var __s *zend.ZendString = zend.ZendStringInit(str, len_, 0)
		__z.value.str = __s
		__z.u1.type_info = 6 | 1<<0<<8
	}
	return 1
yy41:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		if yych <= ',' {
			if yych == '+' {
				goto yy45
			}
			goto yy17
		} else {
			if yych <= '-' {
				goto yy43
			}
			if yych <= '.' {
				goto yy48
			}
			goto yy17
		}
	} else {
		if yych <= 'I' {
			if yych <= '9' {
				goto yy46
			}
			if yych <= 'H' {
				goto yy17
			}
			goto yy44
		} else {
			if yych != 'N' {
				goto yy17
			}
		}
	}
	yych = *(g.PreInc(&cursor))
	if yych == 'A' {
		goto yy63
	}
	goto yy17
yy43:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		if yych == '.' {
			goto yy48
		}
		goto yy17
	} else {
		if yych <= '9' {
			goto yy46
		}
		if yych != 'I' {
			goto yy17
		}
	}
yy44:
	yych = *(g.PreInc(&cursor))
	if yych == 'N' {
		goto yy59
	}
	goto yy17
yy45:
	yych = *(g.PreInc(&cursor))
	if yych == '.' {
		goto yy48
	}
	if yych <= '/' {
		goto yy17
	}
	if yych >= ':' {
		goto yy17
	}
yy46:
	cursor++
	if limit-cursor < 3 {

	}
	yych = *cursor
	if yych <= ':' {
		if yych <= '.' {
			if yych <= '-' {
				goto yy17
			}
			goto yy57
		} else {
			if yych <= '/' {
				goto yy17
			}
			if yych <= '9' {
				goto yy46
			}
			goto yy17
		}
	} else {
		if yych <= 'E' {
			if yych <= ';' {
				goto yy51
			}
			if yych <= 'D' {
				goto yy17
			}
			goto yy53
		} else {
			if yych == 'e' {
				goto yy53
			}
			goto yy17
		}
	}
yy48:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		goto yy17
	}
	if yych >= ':' {
		goto yy17
	}
yy49:
	cursor++
	if limit-cursor < 3 {

	}
	yych = *cursor
	if yych <= ';' {
		if yych <= '/' {
			goto yy17
		}
		if yych <= '9' {
			goto yy49
		}
		if yych <= ':' {
			goto yy17
		}
	} else {
		if yych <= 'E' {
			if yych <= 'D' {
				goto yy17
			}
			goto yy53
		} else {
			if yych == 'e' {
				goto yy53
			}
			goto yy17
		}
	}
yy51:
	cursor++
	*p = cursor
	var __z *zval = rval
	__z.value.dval = zend.ZendStrtod((*byte)(start+2), nil)
	__z.u1.type_info = 5
	return 1
yy53:
	yych = *(g.PreInc(&cursor))
	if yych <= ',' {
		if yych != '+' {
			goto yy17
		}
	} else {
		if yych <= '-' {
			goto yy54
		}
		if yych <= '/' {
			goto yy17
		}
		if yych <= '9' {
			goto yy55
		}
		goto yy17
	}
yy54:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		goto yy17
	}
	if yych >= ':' {
		goto yy17
	}
yy55:
	cursor++
	if limit <= cursor {

	}
	yych = *cursor
	if yych <= '/' {
		goto yy17
	}
	if yych <= '9' {
		goto yy55
	}
	if yych == ';' {
		goto yy51
	}
	goto yy17
yy57:
	cursor++
	if limit-cursor < 3 {

	}
	yych = *cursor
	if yych <= ';' {
		if yych <= '/' {
			goto yy17
		}
		if yych <= '9' {
			goto yy57
		}
		if yych <= ':' {
			goto yy17
		}
		goto yy51
	} else {
		if yych <= 'E' {
			if yych <= 'D' {
				goto yy17
			}
			goto yy53
		} else {
			if yych == 'e' {
				goto yy53
			}
			goto yy17
		}
	}
yy59:
	yych = *(g.PreInc(&cursor))
	if yych != 'F' {
		goto yy17
	}
yy60:
	yych = *(g.PreInc(&cursor))
	if yych != ';' {
		goto yy17
	}
	cursor++
	*p = cursor
	if !(strncmp((*byte)(start+2), "NAN", 3)) {
		var __z *zend.Zval = rval
		__z.value.dval = zend._zendGetNan()
		__z.u1.type_info = 5
	} else if !(strncmp((*byte)(start+2), "INF", 3)) {
		var __z *zend.Zval = rval
		__z.value.dval = zend._zendGetInf()
		__z.u1.type_info = 5
	} else if !(strncmp((*byte)(start+2), "-INF", 4)) {
		var __z *zend.Zval = rval
		__z.value.dval = -(zend._zendGetInf())
		__z.u1.type_info = 5
	} else {
		rval.u1.type_info = 1
	}
	return 1
yy63:
	yych = *(g.PreInc(&cursor))
	if yych == 'N' {
		goto yy60
	}
	goto yy17
yy64:
	yych = *(g.PreInc(&cursor))
	if yych <= ',' {
		if yych != '+' {
			goto yy17
		}
	} else {
		if yych <= '-' {
			goto yy65
		}
		if yych <= '/' {
			goto yy17
		}
		if yych <= '9' {
			goto yy66
		}
		goto yy17
	}
yy65:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		goto yy17
	}
	if yych >= ':' {
		goto yy17
	}
yy66:
	cursor++
	if limit <= cursor {

	}
	yych = *cursor
	if yych <= '/' {
		goto yy17
	}
	if yych <= '9' {
		goto yy66
	}
	if yych != ';' {
		goto yy17
	}
	cursor++
	*p = cursor
	var __z *zend.Zval = rval
	__z.value.lval = ParseIv(start + 2)
	__z.u1.type_info = 4
	return 1
yy70:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		goto yy17
	}
	if yych <= '0' {
		goto yy71
	}
	if yych <= '1' {
		goto yy72
	}
	goto yy17
yy71:
	yych = *(g.PreInc(&cursor))
	if yych == ';' {
		goto yy75
	}
	goto yy17
yy72:
	yych = *(g.PreInc(&cursor))
	if yych != ';' {
		goto yy17
	}
	cursor++
	*p = cursor
	rval.u1.type_info = 3
	return 1
yy75:
	cursor++
	*p = cursor
	rval.u1.type_info = 2
	return 1
yy77:
	cursor++
	*p = cursor
	rval.u1.type_info = 1
	return 1
yy79:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		goto yy17
	}
	if yych >= ':' {
		goto yy17
	}
yy80:
	cursor++
	if limit <= cursor {

	}
	yych = *cursor
	if yych <= '/' {
		goto yy17
	}
	if yych <= '9' {
		goto yy80
	}
	if yych != ';' {
		goto yy17
	}
	cursor++
	var id zend_long
	*p = cursor
	if var_hash == nil {
		return 0
	}
	id = ParseUiv(start+2) - 1
	if id == -1 || g.Assign(&rval_ref, VarAccess(var_hash, id)) == nil {
		return 0
	}
	if rval_ref == rval {
		return 0
	}
	if rval_ref.u1.v.type_ == 10 {
		rval_ref = &(*rval_ref).value.ref.val
	}
	if rval_ref.u1.v.type_ != 8 {
		return 0
	}
	var _z1 *zend.Zval = rval
	var _z2 *zend.Zval = rval_ref
	var _gc *zend.ZendRefcounted = _z2.value.counted
	var _t uint32 = _z2.u1.type_info
	_z1.value.counted = _gc
	_z1.u1.type_info = _t
	if (_t & 0xff00) != 0 {
		zend.ZendGcAddref(&_gc.gc)
	}
	return 1
yy84:
	yych = *(g.PreInc(&cursor))
	if yych <= '/' {
		goto yy17
	}
	if yych >= ':' {
		goto yy17
	}
yy85:
	cursor++
	if limit <= cursor {

	}
	yych = *cursor
	if yych <= '/' {
		goto yy17
	}
	if yych <= '9' {
		goto yy85
	}
	if yych != ';' {
		goto yy17
	}
	cursor++
	var id zend.ZendLong
	*p = cursor
	if var_hash == nil {
		return 0
	}
	id = ParseUiv(start+2) - 1
	if id == -1 || g.Assign(&rval_ref, VarAccess(var_hash, id)) == nil {
		return 0
	}
	if rval_ref.u1.v.type_ == 0 || rval_ref.u1.v.type_ == 10 && &(*rval_ref).value.ref.val.u1.v.type_ == 0 {
		return 0
	}
	if rval_ref.u1.v.type_ != 10 {
		var info *zend.ZendPropertyInfo = nil
		if (*var_hash).GetRefProps() != nil {
			info = zend.ZendHashIndexFindPtr((*var_hash).GetRefProps(), zend.ZendUintptrT(rval_ref))
		}
		var _ref *zend.ZendReference = (*zend.ZendReference)(zend._emalloc(g.SizeOf("zend_reference")))
		zend.ZendGcSetRefcount(&_ref.gc, 1)
		_ref.gc.u.type_info = 10
		var _z1 *zend.Zval = &_ref.val
		var _z2 *zend.Zval = rval_ref
		var _gc *zend.ZendRefcounted = _z2.value.counted
		var _t uint32 = _z2.u1.type_info
		_z1.value.counted = _gc
		_z1.u1.type_info = _t
		_ref.sources.ptr = nil
		rval_ref.value.ref = _ref
		rval_ref.u1.type_info = 10 | 1<<0<<8
		if info != nil {
			zend.ZendRefAddTypeSource(&(rval_ref.value.ref).sources, info)
		}
	}
	var _z1 *zend.Zval = rval
	var _z2 *zend.Zval = rval_ref
	var _gc *zend.ZendRefcounted = _z2.value.counted
	var _t uint32 = _z2.u1.type_info
	_z1.value.counted = _gc
	_z1.u1.type_info = _t
	if (_t & 0xff00) != 0 {
		zend.ZendGcAddref(&_gc.gc)
	}
	return 1
	return 0
}
