// <<generate>>

package core

const CONFIGURE_COMMAND = " './configure'  '--with-iconv=/opt/homebrew/Cellar/libiconv/1.16'"
const PHP_ODBC_CFLAGS = ""
const PHP_ODBC_LFLAGS = ""
const PHP_ODBC_LIBS = ""
const PHP_ODBC_TYPE = ""
const PHP_OCI8_DIR = ""
const PHP_OCI8_ORACLE_VERSION = ""
const PHP_PROG_SENDMAIL = "/usr/sbin/sendmail"
const PEAR_INSTALLDIR = ""
const PHP_INCLUDE_PATH = ".:"
const PHP_EXTENSION_DIR = "/usr/local/lib/php/extensions/no-debug-non-zts-20190902"
const PHP_PREFIX = "/usr/local"
const PHP_BINDIR = "/usr/local/bin"
const PHP_SBINDIR = "/usr/local/sbin"
const PHP_MANDIR = "/usr/local/php/man"
const PHP_LIBDIR = "/usr/local/lib/php"
const PHP_DATADIR = "/usr/local/share/php"
const PHP_SYSCONFDIR = "/usr/local/etc"
const PHP_LOCALSTATEDIR = "/usr/local/var"
const PHP_CONFIG_FILE_PATH = "/usr/local/lib"
const PHP_CONFIG_FILE_SCAN_DIR = ""
const PHP_SHLIB_SUFFIX = "so"
const PHP_SHLIB_EXT_PREFIX = ""
