// <<generate>>

package core

import (
	b "sik/builtin"
	"sik/zend"
)

// Source: <main/main.c>

/*
   +----------------------------------------------------------------------+
   | PHP Version 7                                                        |
   +----------------------------------------------------------------------+
   | Copyright (c) The PHP Group                                          |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
   | Authors: Andi Gutmans <andi@php.net>                                 |
   |          Rasmus Lerdorf <rasmus@lerdorf.on.ca>                       |
   |          Zeev Suraski <zeev@php.net>                                 |
   +----------------------------------------------------------------------+
*/

// failed # include "ext/date/php_date.h"

var PhpRegisterInternalExtensionsFunc func() int = PhpRegisterInternalExtensions
var CoreGlobals PhpCoreGlobals

/* {{{ PHP_INI_MH
 */

var PhpInternalEncodingChanged func() = nil

/* {{{ PHP_INI_MH
 */

var OnChangeBrowscap func(entry *zend.ZendIniEntry, new_value *zend.ZendString, mh_arg1 any, mh_arg2 any, mh_arg3 any, stage int) int

/* Need to be read from the environment (?):
 * PHP_AUTO_PREPEND_FILE
 * PHP_AUTO_APPEND_FILE
 * PHP_DOCUMENT_ROOT
 * PHP_USER_DIR
 * PHP_INCLUDE_PATH
 */

const DEFAULT_SENDMAIL_PATH = PHP_PROG_SENDMAIL + " -t -i"

/* {{{ PHP_INI
 */

var IniEntries []zend.ZendIniEntryDef = []zend.ZendIniEntryDef{
	{"highlight.comment", nil, nil, nil, nil, zend.HL_COMMENT_COLOR, PhpIniColorDisplayerCb, b.SizeOf("HL_COMMENT_COLOR") - 1, b.SizeOf("\"highlight.comment\"") - 1, PHP_INI_ALL},
	{"highlight.default", nil, nil, nil, nil, zend.HL_DEFAULT_COLOR, PhpIniColorDisplayerCb, b.SizeOf("HL_DEFAULT_COLOR") - 1, b.SizeOf("\"highlight.default\"") - 1, PHP_INI_ALL},
	{"highlight.html", nil, nil, nil, nil, zend.HL_HTML_COLOR, PhpIniColorDisplayerCb, b.SizeOf("HL_HTML_COLOR") - 1, b.SizeOf("\"highlight.html\"") - 1, PHP_INI_ALL},
	{"highlight.keyword", nil, nil, nil, nil, zend.HL_KEYWORD_COLOR, PhpIniColorDisplayerCb, b.SizeOf("HL_KEYWORD_COLOR") - 1, b.SizeOf("\"highlight.keyword\"") - 1, PHP_INI_ALL},
	{"highlight.string", nil, nil, nil, nil, zend.HL_STRING_COLOR, PhpIniColorDisplayerCb, b.SizeOf("HL_STRING_COLOR") - 1, b.SizeOf("\"highlight.string\"") - 1, PHP_INI_ALL},
	{
		"display_errors",
		OnUpdateDisplayErrors,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetDisplayErrors())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		DisplayErrorsMode,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"display_errors\"") - 1,
		PHP_INI_ALL,
	},
	{
		"display_startup_errors",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetDisplayStartupErrors())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"display_startup_errors\"") - 1,
		PHP_INI_ALL,
	},
	{
		"enable_dl",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetEnableDl())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"enable_dl\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"expose_php",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetExposePhp())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"expose_php\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"docref_root",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetDocrefRoot())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"",
		nil,
		b.SizeOf("\"\"") - 1,
		b.SizeOf("\"docref_root\"") - 1,
		PHP_INI_ALL,
	},
	{
		"docref_ext",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetDocrefExt())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"",
		nil,
		b.SizeOf("\"\"") - 1,
		b.SizeOf("\"docref_ext\"") - 1,
		PHP_INI_ALL,
	},
	{
		"html_errors",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetHtmlErrors())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"html_errors\"") - 1,
		PHP_INI_ALL,
	},
	{
		"xmlrpc_errors",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetXmlrpcErrors())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"xmlrpc_errors\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"xmlrpc_error_number",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetXmlrpcErrorNumber())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		nil,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"xmlrpc_error_number\"") - 1,
		PHP_INI_ALL,
	},
	{
		"max_input_time",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetMaxInputTime())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"-1",
		nil,
		b.SizeOf("\"-1\"") - 1,
		b.SizeOf("\"max_input_time\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"ignore_user_abort",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetIgnoreUserAbort())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"ignore_user_abort\"") - 1,
		PHP_INI_ALL,
	},
	{
		"implicit_flush",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetImplicitFlush())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"implicit_flush\"") - 1,
		PHP_INI_ALL,
	},
	{
		"log_errors",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetLogErrors())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"log_errors\"") - 1,
		PHP_INI_ALL,
	},
	{
		"log_errors_max_len",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetLogErrorsMaxLen())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1024",
		nil,
		b.SizeOf("\"1024\"") - 1,
		b.SizeOf("\"log_errors_max_len\"") - 1,
		PHP_INI_ALL,
	},
	{
		"ignore_repeated_errors",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetIgnoreRepeatedErrors())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"ignore_repeated_errors\"") - 1,
		PHP_INI_ALL,
	},
	{
		"ignore_repeated_source",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetIgnoreRepeatedSource())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"ignore_repeated_source\"") - 1,
		PHP_INI_ALL,
	},
	{
		"report_memleaks",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetReportMemleaks())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"report_memleaks\"") - 1,
		PHP_INI_ALL,
	},
	{
		"report_zend_debug",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetReportZendDebug())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"report_zend_debug\"") - 1,
		PHP_INI_ALL,
	},
	{
		"output_buffering",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetOutputBuffering())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		nil,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"output_buffering\"") - 1,
		PHP_INI_PERDIR | PHP_INI_SYSTEM,
	},
	{
		"output_handler",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetOutputHandler())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"output_handler\"") - 1,
		PHP_INI_PERDIR | PHP_INI_SYSTEM,
	},
	{
		"register_argc_argv",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetRegisterArgcArgv())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"register_argc_argv\"") - 1,
		PHP_INI_PERDIR | PHP_INI_SYSTEM,
	},
	{
		"auto_globals_jit",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetAutoGlobalsJit())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"auto_globals_jit\"") - 1,
		PHP_INI_PERDIR | PHP_INI_SYSTEM,
	},
	{
		"short_open_tag",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*zend.ZendCompilerGlobals)(nil).short_tags)) - (*byte)(nil))),
		any(&zend.CompilerGlobals),
		nil,
		DEFAULT_SHORT_OPEN_TAG,
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("DEFAULT_SHORT_OPEN_TAG") - 1,
		b.SizeOf("\"short_open_tag\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"track_errors",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetTrackErrors())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"track_errors\"") - 1,
		PHP_INI_ALL,
	},
	{
		"unserialize_callback_func",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetUnserializeCallbackFunc())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"unserialize_callback_func\"") - 1,
		PHP_INI_ALL,
	},
	{
		"serialize_precision",
		OnSetSerializePrecision,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetSerializePrecision())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"-1",
		nil,
		b.SizeOf("\"-1\"") - 1,
		b.SizeOf("\"serialize_precision\"") - 1,
		PHP_INI_ALL,
	},
	{
		"arg_separator.output",
		zend.OnUpdateStringUnempty,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetArgSeparator().GetOutput())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"&",
		nil,
		b.SizeOf("\"&\"") - 1,
		b.SizeOf("\"arg_separator.output\"") - 1,
		PHP_INI_ALL,
	},
	{
		"arg_separator.input",
		zend.OnUpdateStringUnempty,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetArgSeparator().GetInput())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"&",
		nil,
		b.SizeOf("\"&\"") - 1,
		b.SizeOf("\"arg_separator.input\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"auto_append_file",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetAutoAppendFile())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"auto_append_file\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"auto_prepend_file",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetAutoPrependFile())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"auto_prepend_file\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"doc_root",
		zend.OnUpdateStringUnempty,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetDocRoot())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"doc_root\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"default_charset",
		OnUpdateDefaultCharset,
		any(zend_long((*byte)(&((*sapi_globals_struct)(nil).GetDefaultCharset())) - (*byte)(nil))),
		any(&sapi_globals),
		nil,
		PHP_DEFAULT_CHARSET,
		nil,
		b.SizeOf("PHP_DEFAULT_CHARSET") - 1,
		b.SizeOf("\"default_charset\"") - 1,
		PHP_INI_ALL,
	},
	{
		"default_mimetype",
		OnUpdateDefaultMimeTye,
		any(zend_long((*byte)(&((*sapi_globals_struct)(nil).GetDefaultMimetype())) - (*byte)(nil))),
		any(&sapi_globals),
		nil,
		SAPI_DEFAULT_MIMETYPE,
		nil,
		b.SizeOf("SAPI_DEFAULT_MIMETYPE") - 1,
		b.SizeOf("\"default_mimetype\"") - 1,
		PHP_INI_ALL,
	},
	{
		"internal_encoding",
		OnUpdateInternalEncoding,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetInternalEncoding())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"internal_encoding\"") - 1,
		PHP_INI_ALL,
	},
	{
		"input_encoding",
		OnUpdateInputEncoding,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetInputEncoding())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"input_encoding\"") - 1,
		PHP_INI_ALL,
	},
	{
		"output_encoding",
		OnUpdateOutputEncoding,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetOutputEncoding())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"output_encoding\"") - 1,
		PHP_INI_ALL,
	},
	{
		"error_log",
		OnUpdateErrorLog,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetErrorLog())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"error_log\"") - 1,
		PHP_INI_ALL,
	},
	{
		"extension_dir",
		zend.OnUpdateStringUnempty,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetExtensionDir())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		PHP_EXTENSION_DIR,
		nil,
		b.SizeOf("PHP_EXTENSION_DIR") - 1,
		b.SizeOf("\"extension_dir\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"sys_temp_dir",
		zend.OnUpdateStringUnempty,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetSysTempDir())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"sys_temp_dir\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"include_path",
		zend.OnUpdateStringUnempty,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetIncludePath())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		PHP_INCLUDE_PATH,
		nil,
		b.SizeOf("PHP_INCLUDE_PATH") - 1,
		b.SizeOf("\"include_path\"") - 1,
		PHP_INI_ALL,
	},
	{"max_execution_time", OnUpdateTimeout, nil, nil, nil, "30", nil, b.SizeOf("\"30\"") - 1, b.SizeOf("\"max_execution_time\"") - 1, PHP_INI_ALL},
	{
		"open_basedir",
		OnUpdateBaseDir,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetOpenBasedir())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"open_basedir\"") - 1,
		PHP_INI_ALL,
	},
	{
		"file_uploads",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetFileUploads())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"file_uploads\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"upload_max_filesize",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetUploadMaxFilesize())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"2M",
		nil,
		b.SizeOf("\"2M\"") - 1,
		b.SizeOf("\"upload_max_filesize\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"post_max_size",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*sapi_globals_struct)(nil).GetPostMaxSize())) - (*byte)(nil))),
		any(&sapi_globals),
		nil,
		"8M",
		nil,
		b.SizeOf("\"8M\"") - 1,
		b.SizeOf("\"post_max_size\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"upload_tmp_dir",
		zend.OnUpdateStringUnempty,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetUploadTmpDir())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"upload_tmp_dir\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"max_input_nesting_level",
		zend.OnUpdateLongGEZero,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetMaxInputNestingLevel())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"64",
		nil,
		b.SizeOf("\"64\"") - 1,
		b.SizeOf("\"max_input_nesting_level\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"max_input_vars",
		zend.OnUpdateLongGEZero,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetMaxInputVars())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1000",
		nil,
		b.SizeOf("\"1000\"") - 1,
		b.SizeOf("\"max_input_vars\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"user_dir",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetUserDir())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"user_dir\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"variables_order",
		zend.OnUpdateStringUnempty,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetVariablesOrder())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"EGPCS",
		nil,
		b.SizeOf("\"EGPCS\"") - 1,
		b.SizeOf("\"variables_order\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"request_order",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetRequestOrder())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"request_order\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"error_append_string",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetErrorAppendString())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"error_append_string\"") - 1,
		PHP_INI_ALL,
	},
	{
		"error_prepend_string",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetErrorPrependString())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"error_prepend_string\"") - 1,
		PHP_INI_ALL,
	},
	{"SMTP", nil, nil, nil, nil, "localhost", nil, b.SizeOf("\"localhost\"") - 1, b.SizeOf("\"SMTP\"") - 1, PHP_INI_ALL},
	{"smtp_port", nil, nil, nil, nil, "25", nil, b.SizeOf("\"25\"") - 1, b.SizeOf("\"smtp_port\"") - 1, PHP_INI_ALL},
	{
		"mail.add_x_header",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetMailXHeader())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"mail.add_x_header\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"mail.log",
		OnUpdateMailLog,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetMailLog())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"mail.log\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{"browscap", OnChangeBrowscap, nil, nil, nil, nil, nil, b.SizeOf("NULL") - 1, b.SizeOf("\"browscap\"") - 1, PHP_INI_SYSTEM},
	{"memory_limit", OnChangeMemoryLimit, nil, nil, nil, "128M", nil, b.SizeOf("\"128M\"") - 1, b.SizeOf("\"memory_limit\"") - 1, PHP_INI_ALL},
	{"precision", OnSetPrecision, nil, nil, nil, "14", nil, b.SizeOf("\"14\"") - 1, b.SizeOf("\"precision\"") - 1, PHP_INI_ALL},
	{"sendmail_from", nil, nil, nil, nil, nil, nil, b.SizeOf("NULL") - 1, b.SizeOf("\"sendmail_from\"") - 1, PHP_INI_ALL},
	{"sendmail_path", nil, nil, nil, nil, DEFAULT_SENDMAIL_PATH, nil, b.SizeOf("DEFAULT_SENDMAIL_PATH") - 1, b.SizeOf("\"sendmail_path\"") - 1, PHP_INI_SYSTEM},
	{
		"mail.force_extra_parameters",
		OnChangeMailForceExtra,
		nil,
		nil,
		nil,
		nil,
		nil,
		b.SizeOf("NULL") - 1,
		b.SizeOf("\"mail.force_extra_parameters\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{"disable_functions", nil, nil, nil, nil, "", nil, b.SizeOf("\"\"") - 1, b.SizeOf("\"disable_functions\"") - 1, PHP_INI_SYSTEM},
	{"disable_classes", nil, nil, nil, nil, "", nil, b.SizeOf("\"\"") - 1, b.SizeOf("\"disable_classes\"") - 1, PHP_INI_SYSTEM},
	{"max_file_uploads", nil, nil, nil, nil, "20", nil, b.SizeOf("\"20\"") - 1, b.SizeOf("\"max_file_uploads\"") - 1, PHP_INI_SYSTEM | PHP_INI_PERDIR},
	{
		"allow_url_fopen",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetAllowUrlFopen())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"allow_url_fopen\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"allow_url_include",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetAllowUrlInclude())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"0",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"0\"") - 1,
		b.SizeOf("\"allow_url_include\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"enable_post_data_reading",
		zend.OnUpdateBool,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetEnablePostDataReading())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"1",
		zend.ZendIniBooleanDisplayerCb,
		b.SizeOf("\"1\"") - 1,
		b.SizeOf("\"enable_post_data_reading\"") - 1,
		PHP_INI_SYSTEM | PHP_INI_PERDIR,
	},
	{
		"realpath_cache_size",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*zend.VirtualCwdGlobals)(nil).realpath_cache_size_limit)) - (*byte)(nil))),
		any(&zend.CwdGlobals),
		nil,
		"4096K",
		nil,
		b.SizeOf("\"4096K\"") - 1,
		b.SizeOf("\"realpath_cache_size\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"realpath_cache_ttl",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*zend.VirtualCwdGlobals)(nil).realpath_cache_ttl)) - (*byte)(nil))),
		any(&zend.CwdGlobals),
		nil,
		"120",
		nil,
		b.SizeOf("\"120\"") - 1,
		b.SizeOf("\"realpath_cache_ttl\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"user_ini.filename",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetUserIniFilename())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		".user.ini",
		nil,
		b.SizeOf("\".user.ini\"") - 1,
		b.SizeOf("\"user_ini.filename\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"user_ini.cache_ttl",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetUserIniCacheTtl())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"300",
		nil,
		b.SizeOf("\"300\"") - 1,
		b.SizeOf("\"user_ini.cache_ttl\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"hard_timeout",
		zend.OnUpdateLong,
		any(zend_long((*byte)(&((*zend.ZendExecutorGlobals)(nil).hard_timeout)) - (*byte)(nil))),
		any(&zend.ExecutorGlobals),
		nil,
		"2",
		nil,
		b.SizeOf("\"2\"") - 1,
		b.SizeOf("\"hard_timeout\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"syslog.facility",
		OnSetFacility,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetSyslogFacility())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"LOG_USER",
		nil,
		b.SizeOf("\"LOG_USER\"") - 1,
		b.SizeOf("\"syslog.facility\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"syslog.ident",
		zend.OnUpdateString,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetSyslogIdent())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"php",
		nil,
		b.SizeOf("\"php\"") - 1,
		b.SizeOf("\"syslog.ident\"") - 1,
		PHP_INI_SYSTEM,
	},
	{
		"syslog.filter",
		OnSetLogFilter,
		any(zend_long((*byte)(&((*PhpCoreGlobals)(nil).GetSyslogFilter())) - (*byte)(nil))),
		any(&CoreGlobals),
		nil,
		"no-ctrl",
		nil,
		b.SizeOf("\"no-ctrl\"") - 1,
		b.SizeOf("\"syslog.filter\"") - 1,
		PHP_INI_ALL,
	},
	{nil, nil, nil, nil, nil, nil, nil, 0, 0, 0},
}
var ModuleInitialized int = 0
var ModuleStartup int = 1
var ModuleShutdown int = 0

/* {{{ php_during_module_startup */

/* {{{ php_html_puts */

/* {{{ php_request_startup
 */

/* {{{ core_globals_dtor
 */

/* A very long time ago php_module_startup() was refactored in a way
 * which broke calling it with more than one additional module.
 * This alternative to php_register_extensions() works around that
 * by walking the shallower structure.
 *
 * See algo: https://bugs.php.net/bug.php?id=63159
 */

/* {{{ php_module_startup
 */
