// <<generate>>

package core

const PHP_TMP_FILE_DEFAULT = 0
const PHP_TMP_FILE_OPEN_BASEDIR_CHECK_ON_FALLBACK uint32 = 1 << 0
const PHP_TMP_FILE_SILENT = 1 << 1
const PHP_TMP_FILE_OPEN_BASEDIR_CHECK_ON_EXPLICIT_DIR = 1 << 2
const PHP_TMP_FILE_OPEN_BASEDIR_CHECK_ALWAYS uint32 = PHP_TMP_FILE_OPEN_BASEDIR_CHECK_ON_FALLBACK | PHP_TMP_FILE_OPEN_BASEDIR_CHECK_ON_EXPLICIT_DIR
const PHP_TMP_FILE_OPEN_BASEDIR_CHECK = PHP_TMP_FILE_OPEN_BASEDIR_CHECK_ON_FALLBACK
const P_tmpdir = ""
