package core

/* automatically generated by configure */

const PHP_MAJOR_VERSION = 7
const PHP_MINOR_VERSION = 4
const PHP_RELEASE_VERSION = 33
const PHP_EXTRA_VERSION = ""
const PHP_VERSION = "7.4.33"
const PHP_VERSION_ID = 70433
