// Code generated by "stringer -type runMode"; DO NOT EDIT.

package sapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[modeUnknown-0]
	_ = x[modeHelp-1]
	_ = x[modeVersion-2]
	_ = x[modeInfo-3]
	_ = x[modeModules-4]
	_ = x[modeIni-5]
	_ = x[modeCliCode-6]
	_ = x[modeCliFile-7]
	_ = x[modeCliServer-8]
	_ = x[modeCgiServer-9]
}

const _runMode_name = "modeUnknownmodeHelpmodeVersionmodeInfomodeModulesmodeInimodeCliCodemodeCliFilemodeCliServermodeCgiServer"

var _runMode_index = [...]uint8{0, 11, 19, 30, 38, 49, 56, 67, 78, 91, 104}

func (i runMode) String() string {
	if i >= runMode(len(_runMode_index)-1) {
		return "runMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _runMode_name[_runMode_index[i]:_runMode_index[i+1]]
}
