// Code generated by "stringer -type=Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NAME_FULLY_QUALIFIED-263]
	_ = x[NAME_RELATIVE-264]
	_ = x[NAME_QUALIFIED-265]
	_ = x[VARIABLE-266]
	_ = x[INLINE_HTML-267]
	_ = x[ENCAPSED_AND_WHITESPACE-268]
	_ = x[STRING_VARNAME-270]
	_ = x[NUM_STRING-271]
	_ = x[PRINT-280]
	_ = x[YIELD-281]
	_ = x[YIELD_FROM-282]
	_ = x[INSTANCEOF-283]
	_ = x[NEW-284]
	_ = x[CLONE-285]
	_ = x[EXIT-286]
	_ = x[IF-287]
	_ = x[ELSEIF-288]
	_ = x[ELSE-289]
	_ = x[ENDIF-290]
	_ = x[ECHO-291]
	_ = x[DO-292]
	_ = x[WHILE-293]
	_ = x[ENDWHILE-294]
	_ = x[FOR-295]
	_ = x[ENDFOR-296]
	_ = x[FOREACH-297]
	_ = x[ENDFOREACH-298]
	_ = x[DECLARE-299]
	_ = x[ENDDECLARE-300]
	_ = x[AS-301]
	_ = x[SWITCH-302]
	_ = x[ENDSWITCH-303]
	_ = x[CASE-304]
	_ = x[DEFAULT-305]
	_ = x[MATCH-306]
	_ = x[BREAK-307]
	_ = x[CONTINUE-308]
	_ = x[GOTO-309]
	_ = x[FUNCTION-310]
	_ = x[FN-311]
	_ = x[CONST-312]
	_ = x[RETURN-313]
	_ = x[TRY-314]
	_ = x[CATCH-315]
	_ = x[FINALLY-316]
	_ = x[THROW-317]
	_ = x[USE-318]
	_ = x[INSTEADOF-319]
	_ = x[GLOBAL-320]
	_ = x[STATIC-321]
	_ = x[ABSTRACT-322]
	_ = x[FINAL-323]
	_ = x[PRIVATE-324]
	_ = x[PROTECTED-325]
	_ = x[PUBLIC-326]
	_ = x[READONLY-327]
	_ = x[VAR-328]
	_ = x[UNSET-329]
	_ = x[HALT_COMPILER-332]
	_ = x[CLASS-333]
	_ = x[TRAIT-334]
	_ = x[INTERFACE-335]
	_ = x[ENUM-336]
	_ = x[EXTENDS-337]
	_ = x[IMPLEMENTS-338]
	_ = x[NAMESPACE-339]
	_ = x[LIST-340]
	_ = x[ARRAY-341]
	_ = x[CALLABLE-342]
	_ = x[ATTRIBUTE-351]
	_ = x[OBJECT_OPERATOR-384]
	_ = x[NULLSAFE_OBJECT_OPERATOR-385]
	_ = x[DOUBLE_ARROW-386]
	_ = x[COMMENT-387]
	_ = x[DOC_COMMENT-388]
	_ = x[OPEN_TAG-389]
	_ = x[OPEN_TAG_WITH_ECHO-390]
	_ = x[CLOSE_TAG-391]
	_ = x[WHITESPACE-392]
	_ = x[START_HEREDOC-393]
	_ = x[END_HEREDOC-394]
	_ = x[DOLLAR_OPEN_CURLY_BRACES-395]
	_ = x[CURLY_OPEN-396]
	_ = x[PAAMAYIM_NEKUDOTAYIM-397]
	_ = x[DOUBLE_COLON-397]
	_ = x[NS_SEPARATOR-398]
	_ = x[ELLIPSIS-399]
	_ = x[AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG-403]
	_ = x[AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG-404]
	_ = x[BAD_CHARACTER-405]
}

const (
	_Token_name_0 = "NAME_FULLY_QUALIFIEDNAME_RELATIVENAME_QUALIFIEDVARIABLEINLINE_HTMLENCAPSED_AND_WHITESPACE"
	_Token_name_1 = "STRING_VARNAMENUM_STRING"
	_Token_name_2 = "PRINTYIELDYIELD_FROMINSTANCEOFNEWCLONEEXITIFELSEIFELSEENDIFECHODOWHILEENDWHILEFORENDFORFOREACHENDFOREACHDECLAREENDDECLAREASSWITCHENDSWITCHCASEDEFAULTMATCHBREAKCONTINUEGOTOFUNCTIONFNCONSTRETURNTRYCATCHFINALLYTHROWUSEINSTEADOFGLOBALSTATICABSTRACTFINALPRIVATEPROTECTEDPUBLICREADONLYVARUNSET"
	_Token_name_3 = "HALT_COMPILERCLASSTRAITINTERFACEENUMEXTENDSIMPLEMENTSNAMESPACELISTARRAYCALLABLE"
	_Token_name_4 = "ATTRIBUTE"
	_Token_name_5 = "OBJECT_OPERATORNULLSAFE_OBJECT_OPERATORDOUBLE_ARROWCOMMENTDOC_COMMENTOPEN_TAGOPEN_TAG_WITH_ECHOCLOSE_TAGWHITESPACESTART_HEREDOCEND_HEREDOCDOLLAR_OPEN_CURLY_BRACESCURLY_OPENPAAMAYIM_NEKUDOTAYIMNS_SEPARATORELLIPSIS"
	_Token_name_6 = "AMPERSAND_FOLLOWED_BY_VAR_OR_VARARGAMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARGBAD_CHARACTER"
)

var (
	_Token_index_0 = [...]uint8{0, 20, 33, 47, 55, 66, 89}
	_Token_index_1 = [...]uint8{0, 14, 24}
	_Token_index_2 = [...]uint16{0, 5, 10, 20, 30, 33, 38, 42, 44, 50, 54, 59, 63, 65, 70, 78, 81, 87, 94, 104, 111, 121, 123, 129, 138, 142, 149, 154, 159, 167, 171, 179, 181, 186, 192, 195, 200, 207, 212, 215, 224, 230, 236, 244, 249, 256, 265, 271, 279, 282, 287}
	_Token_index_3 = [...]uint8{0, 13, 18, 23, 32, 36, 43, 53, 62, 66, 71, 79}
	_Token_index_5 = [...]uint8{0, 15, 39, 51, 58, 69, 77, 95, 104, 114, 127, 138, 162, 172, 192, 204, 212}
	_Token_index_6 = [...]uint8{0, 35, 74, 87}
)

func (i Token) String() string {
	switch {
	case 263 <= i && i <= 268:
		i -= 263
		return _Token_name_0[_Token_index_0[i]:_Token_index_0[i+1]]
	case 270 <= i && i <= 271:
		i -= 270
		return _Token_name_1[_Token_index_1[i]:_Token_index_1[i+1]]
	case 280 <= i && i <= 329:
		i -= 280
		return _Token_name_2[_Token_index_2[i]:_Token_index_2[i+1]]
	case 332 <= i && i <= 342:
		i -= 332
		return _Token_name_3[_Token_index_3[i]:_Token_index_3[i+1]]
	case i == 351:
		return _Token_name_4
	case 384 <= i && i <= 399:
		i -= 384
		return _Token_name_5[_Token_index_5[i]:_Token_index_5[i+1]]
	case 403 <= i && i <= 405:
		i -= 403
		return _Token_name_6[_Token_index_6[i]:_Token_index_6[i+1]]
	default:
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
