package php

import "github.com/heyuuu/gophp/php/types"

func moduleStartupRegisterConstants(ctx *Context) {
	//RegisterStringConstant(ctx, 0, "PHP_VERSION", PHP_VERSION)
	//RegisterLongConstant(ctx, 0, "PHP_MAJOR_VERSION", PHP_MAJOR_VERSION)
	//RegisterLongConstant(ctx, 0, "PHP_MINOR_VERSION", PHP_MINOR_VERSION)
	//RegisterLongConstant(ctx, 0, "PHP_RELEASE_VERSION", PHP_RELEASE_VERSION)
	//RegisterStringConstant(ctx, 0, "PHP_EXTRA_VERSION", PHP_EXTRA_VERSION)
	//RegisterLongConstant(ctx, 0, "PHP_VERSION_ID", PHP_VERSION_ID)
	//RegisterLongConstant(ctx, 0, "PHP_ZTS", 0)
	//RegisterLongConstant(ctx, 0, "PHP_DEBUG", 0)
	//RegisterStringConstant(ctx, 0, "PHP_OS", PHP_OS)
	//RegisterStringConstant(ctx, 0, "PHP_OS_FAMILY", PHP_OS_FAMILY)
	//RegisterConstantEx(ctx, 0, "PHP_SAPI", String(SM__().Name()), types.ConstPersistent|types.ConstCs|types.ConstNoFileCache)
	//RegisterStringConstant(ctx, 0, "DEFAULT_INCLUDE_PATH", PHP_INCLUDE_PATH)
	//RegisterStringConstant(ctx, 0, "PEAR_INSTALL_DIR", PEAR_INSTALLDIR)
	//RegisterStringConstant(ctx, 0, "PEAR_EXTENSION_DIR", PHP_EXTENSION_DIR)
	//RegisterStringConstant(ctx, 0, "PHP_EXTENSION_DIR", PHP_EXTENSION_DIR)
	//RegisterStringConstant(ctx, 0, "PHP_PREFIX", PHP_PREFIX)
	//RegisterStringConstant(ctx, 0, "PHP_BINDIR", PHP_BINDIR)
	//RegisterStringConstant(ctx, 0, "PHP_MANDIR", PHP_MANDIR)
	//RegisterStringConstant(ctx, 0, "PHP_LIBDIR", PHP_LIBDIR)
	//RegisterStringConstant(ctx, 0, "PHP_DATADIR", PHP_DATADIR)
	//RegisterStringConstant(ctx, 0, "PHP_SYSCONFDIR", PHP_SYSCONFDIR)
	//RegisterStringConstant(ctx, 0, "PHP_LOCALSTATEDIR", PHP_LOCALSTATEDIR)
	//RegisterStringConstant(ctx, 0, "PHP_CONFIG_FILE_PATH", PHP_CONFIG_FILE_PATH)
	//RegisterStringConstant(ctx, 0, "PHP_CONFIG_FILE_SCAN_DIR", PHP_CONFIG_FILE_SCAN_DIR)
	//RegisterStringConstant(ctx, 0, "PHP_SHLIB_SUFFIX", PHP_SHLIB_SUFFIX)
	//RegisterStringConstant(ctx, 0, "PHP_EOL", PHP_EOL)
	//RegisterLongConstant(ctx, 0, "PHP_MAXPATHLEN", MAXPATHLEN)
	RegisterLongConstant(ctx, 0, "PHP_INT_MAX", types.MaxLong)
	RegisterLongConstant(ctx, 0, "PHP_INT_MIN", types.MinLong)
	//RegisterLongConstant(ctx, 0, "PHP_INT_SIZE", SizeofLong)
	//RegisterLongConstant(ctx, 0, "PHP_FD_SETSIZE", FD_SETSIZE)
	//RegisterLongConstant(ctx, 0, "PHP_FLOAT_DIG", DBL_DIG)
	//RegisterDoubleConstant(ctx, 0, "PHP_FLOAT_EPSILON", DBL_EPSILON)
	//RegisterDoubleConstant(ctx, 0, "PHP_FLOAT_MAX", DBL_MAX)
	//RegisterDoubleConstant(ctx, 0, "PHP_FLOAT_MIN", DBL_MIN)
	//PhpBinaryInit(ctx, ctx.Engine())
	//RegisterConstantEx(ctx, 0, "PHP_BINARY", String(ctx.PG().PhpBinary()), types.ConstPersistent|types.ConstCs|types.ConstNoFileCache)
	//PhpOutputRegisterConstants(ctx)
	//PhpRfc1867RegisterConstants(ctx)
}
