// Code generated by "stringer -type=ErrorType"; DO NOT EDIT.

package perr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[E_ERROR-1]
	_ = x[E_WARNING-2]
	_ = x[E_PARSE-4]
	_ = x[E_NOTICE-8]
	_ = x[E_CORE_ERROR-16]
	_ = x[E_CORE_WARNING-32]
	_ = x[E_COMPILE_ERROR-64]
	_ = x[E_COMPILE_WARNING-128]
	_ = x[E_USER_ERROR-256]
	_ = x[E_USER_WARNING-512]
	_ = x[E_USER_NOTICE-1024]
	_ = x[E_STRICT-2048]
	_ = x[E_RECOVERABLE_ERROR-4096]
	_ = x[E_DEPRECATED-8192]
	_ = x[E_USER_DEPRECATED-16384]
	_ = x[E_ALL-32767]
	_ = x[E_CORE-48]
}

const _ErrorType_name = "E_ERRORE_WARNINGE_PARSEE_NOTICEE_CORE_ERRORE_CORE_WARNINGE_COREE_COMPILE_ERRORE_COMPILE_WARNINGE_USER_ERRORE_USER_WARNINGE_USER_NOTICEE_STRICTE_RECOVERABLE_ERRORE_DEPRECATEDE_USER_DEPRECATEDE_ALL"

var _ErrorType_map = map[ErrorType]string{
	1:     _ErrorType_name[0:7],
	2:     _ErrorType_name[7:16],
	4:     _ErrorType_name[16:23],
	8:     _ErrorType_name[23:31],
	16:    _ErrorType_name[31:43],
	32:    _ErrorType_name[43:57],
	48:    _ErrorType_name[57:63],
	64:    _ErrorType_name[63:78],
	128:   _ErrorType_name[78:95],
	256:   _ErrorType_name[95:107],
	512:   _ErrorType_name[107:121],
	1024:  _ErrorType_name[121:134],
	2048:  _ErrorType_name[134:142],
	4096:  _ErrorType_name[142:161],
	8192:  _ErrorType_name[161:173],
	16384: _ErrorType_name[173:190],
	32767: _ErrorType_name[190:195],
}

func (i ErrorType) String() string {
	if str, ok := _ErrorType_map[i]; ok {
		return str
	}
	return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
}
